// examples/vue/src/pages/ui/components/authenticator/gen2/hub-events/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import { signOut } from 'aws-amplify/auth';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from './amplify_outputs';

Amplify.configure(amplifyOutputs);
</script>

<template>
  <authenticator>
    <template v-slot="{ user }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut()">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/gen2/hub-events/hub-events.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';
import { signOut } from 'aws-amplify/auth';
import amplifyOutputs from './amplify_outputs';

@Component({
  selector: 'hub-events',
  templateUrl: 'hub-events.component.html',
})
export class HubEventsComponent {
  constructor() {
    Amplify.configure(amplifyOutputs);
  }

  public signOut(): void {
    signOut();
  }
}
