// examples/angular/src/pages/ui/components/authenticator/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';

import awsExports from './aws-exports';

@Component({
  selector: 'forgot-password',
  templateUrl: 'forgot-password.component.html',
})
export class ForgotPasswordComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator initialState="forgotPassword">
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>

// examples/svelte/src/routes/ui/components/authenticator/forgot-password/+page.svelte
<script lang="ts">
  import '@aws-amplify/ui-svelte/styles.css';
  import { Amplify } from 'aws-amplify';
  import { Authenticator } from '@aws-amplify/ui-svelte';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
</script>

<Authenticator initialState="forgotPassword">
  {#snippet children({ user, signOut })}
    <h1>Hello {user.username}!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>
