// examples/next/pages/ui/components/authenticator/sign-in/index.tsx
import { Authenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';

import awsExports from '@environments/auth-with-username-no-attributes-environment/src/aws-exports';

Amplify.configure(awsExports);

export default function AuthenticatorWithUsername() {
  return (
    <>
      <Authenticator>
        {({ state, send }) => {
          return (
            <>
              <h1>Hello {state.context.user.username}</h1>
              <button onClick={() => send('SIGN_OUT')}>Sign out</button>
            </>
          );
        }}
      </Authenticator>
    </>
  );
}

// examples/vue/src/pages/ui/components/authenticator/sign-in/index.vue
<template>
  <Authenticator>
    <template v-slot="{ user }">
      <h1 class="text-6xl mb-10">Hello {{ user.username }}!</h1>
      <button
        className="px-2 bg-white rounded shadow"
        @click="send('SIGN_OUT')"
      >
        Sign Out
      </button>
    </template>
  </Authenticator>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import aws_exports from "auth-with-username-no-attributes-environment/src/aws-exports";

import Amplify from "aws-amplify";
import "@aws-amplify/ui-vue/styles.css";

import { Authenticator, useAuth } from "@aws-amplify/ui-vue";

Amplify.configure({
  ...aws_exports,
  auth: {
    login_mechanisms: ["username"],
  },
});

export default defineComponent({
  name: "App",
  components: { Authenticator },
  setup() {
    const { send } = useAuth();
    return { send };
  },
});
</script>
