// packages/vue/src/components/primitives/base-form-fields.vue
<script setup lang="ts">
import { toRefs, onBeforeMount } from 'vue';
import { FormFields, SortedFormFields, sortFormFields } from '@aws-amplify/ui';

import BaseFormField from './base-form-field.vue';

interface BaseFormFields {
  formFields: FormFields;
}
const props = withDefaults(defineProps<BaseFormFields>(), {
  formFields: () => ({}),
});

const { formFields } = toRefs(props);
let sortedFormFields: SortedFormFields;

onBeforeMount(() => {
  sortedFormFields = sortFormFields(formFields.value);
});
</script>
<template>
  <base-form-field
    v-for="[name, formField] in sortedFormFields"
    :name="name"
    :key="name"
    :formField="formField"
  ></base-form-field>
</template>

// packages/react/src/components/Authenticator/shared/BaseFormFields.tsx
import * as React from 'react';

import { FormFields, sortFormFields } from '@aws-amplify/ui';
import { FormField } from './FormField';

export interface BaseFormFieldsProps {
  formFields: FormFields;
}
export function BaseFormFields({ formFields }: BaseFormFieldsProps) {
  const sortedFormFields = React.useMemo(
    () => sortFormFields(formFields),
    [formFields]
  );

  return (
    <>
      {sortedFormFields.flatMap(([name, options]) => (
        <FormField name={name} key={name} formFieldOptions={options} />
      ))}
    </>
  );
}
