// packages/svelte/src/lib/components/primitives/FormField.svelte
<script lang="ts">
  import { nanoid } from 'nanoid';
  import { type FullAutoFill } from 'svelte/elements';

  import { type FormFieldOptions, getErrors, translate } from '@aws-amplify/ui';
  import { useAuthenticator } from '../../stores/authenticator.svelte';
  import PasswordField from '../controls/PasswordField.svelte';
  import AliasField from '../controls/AliasField.svelte';

  interface BaseFormField {
    name?: string;
    formField?: FormFieldOptions;
  }

  const { name = '', formField = {} }: BaseFormField = $props();

  const { validationErrors } = $derived(useAuthenticator());

  const { type } = formField;

  const isPasswordField = $derived(type === 'password');

  const errorId = nanoid(12);

  const errors = $derived(getErrors(validationErrors[name]));
  const hasError = $derived(errors?.length > 0);
  const ariaDescribedBy = $derived(hasError ? errorId : undefined);
  const autocomplete = $derived(formField.autocomplete ?? '') as unknown as FullAutoFill;
</script>

{#if isPasswordField}
  <PasswordField
    {name}
    {hasError}
    {autocomplete}
    label={formField.label ?? ''}
    placeholder={formField.placeholder}
    required={formField.isRequired}
    labelHidden={formField.labelHidden}
    describedBy={ariaDescribedBy}
  />
{:else}
  <AliasField
    {name}
    {hasError}
    {autocomplete}
    label={formField.label ?? ''}
    placeholder={formField.placeholder}
    required={formField.isRequired}
    labelHidden={formField.labelHidden}
    dialCode={formField.dialCode}
    dialCodeList={formField.dialCodeList}
    type={formField.type}
    describedBy={ariaDescribedBy}
  />
{/if}

{#if hasError}
  <div id={ariaDescribedBy}>
    {#each errors as error, idx (idx)}
      <p role="alert" data-variation="error" class="amplify-text amplify-text--error">
        {translate(error)}
      </p>
    {/each}
  </div>
{/if}

// packages/react/src/components/Authenticator/shared/FormField.tsx
import * as React from 'react';
import { FormFieldOptions, getErrors } from '@aws-amplify/ui';

import { PasswordField } from '../../../primitives/PasswordField';
import { PhoneNumberField } from '../../../primitives/PhoneNumberField';
import { TextField } from '../../../primitives/TextField';
import { useAuthenticator } from '../hooks/useAuthenticator';
import { ValidationErrors } from './ValidationErrors';
import { useStableId } from '../../../primitives/utils/useStableId';

export interface FormFieldProps extends Omit<FormFieldOptions, 'label'> {
  // label is a required prop for the UI field components used in FormField
  label: string;
  name: string;
}

export function FormField({
  autocomplete: autoComplete,
  dialCode,
  name,
  type,
  ...props
}: FormFieldProps) {
  const { validationErrors } = useAuthenticator(({ validationErrors }) => [
    validationErrors,
  ]);

  const errors = React.useMemo(
    () => getErrors(validationErrors[name]),
    [name, validationErrors]
  );
  const hasError = errors?.length > 0;
  const errorId = useStableId();
  const ariaDescribedBy = hasError ? errorId : undefined;

  if (type === 'tel') {
    return (
      <>
        <PhoneNumberField
          {...props}
          name={name}
          defaultCountryCode={dialCode}
          countryCodeName="country_code"
          autoComplete={autoComplete}
          hasError={hasError}
          aria-describedby={ariaDescribedBy}
        />
        <ValidationErrors errors={errors} id={errorId} />
      </>
    );
  } else if (type === 'password') {
    return (
      <>
        <PasswordField
          {...props}
          name={name}
          autoComplete={autoComplete}
          hasError={hasError}
          aria-describedby={ariaDescribedBy}
        />
        <ValidationErrors errors={errors} id={errorId} />
      </>
    );
  } else {
    return (
      <>
        <TextField
          {...props}
          name={name}
          autoComplete={autoComplete}
          hasError={hasError}
          type={type}
          aria-describedby={ariaDescribedBy}
        />
        <ValidationErrors errors={errors} id={errorId} />
      </>
    );
  }
}
