// examples/next/pages/ui/components/authenticator/sign-in-federated/index.tsx
import { Authenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';

import awsExports from 'environments/auth-with-federated/src/aws-exports';

Amplify.configure({
  ...awsExports,
  auth: {
    login_mechanisms: ['email', 'facebook', 'google', 'amazon'],
  },
});

export default function AuthenticatorWithFacebook() {
  return (
    <Authenticator>
      {({ send }) => {
        return (
          <>
            <button onClick={() => send('SIGN_OUT')}>Sign out</button>
          </>
        );
      }}
    </Authenticator>
  );
}

// examples/angular/src/pages/ui/components/authenticator/sign-in-federated/sign-in-federated.component.ts
import { Component, OnInit } from '@angular/core';
import Amplify from 'aws-amplify';
import awsExports from '@environments/auth-with-federated/src/aws-exports';

@Component({
  selector: 'sign-in-federated',
  templateUrl: 'sign-in-federated.component.html',
})
export class SignInFederatedComponent implements OnInit {
  constructor() {
    Amplify.configure({
      ...awsExports,
      auth: {
        login_mechanisms: ['email', 'facebook', 'google', 'amazon'],
      },
    });
  }

  ngOnInit() {}
}

<amplify-authenticator
  [loginMechanisms]="['email', 'facebook', 'google', 'amazon']"
>
  <ng-template
    amplifyOverride="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>
