// examples/angular/src/pages/ui/components/authenticator/sign-in-sms-mfa/sign-in-sms-mfa.component.ts
import { Component, OnInit } from '@angular/core';

import { Amplify } from 'aws-amplify';
import { I18n } from 'aws-amplify/utils';

import { translations } from '@aws-amplify/ui';

import awsExports from './aws-exports';

@Component({
  selector: 'sign-in-sms-mfa',
  templateUrl: 'sign-in-sms-mfa.component.html',
})
export class SignInSMSMFAComponent implements OnInit {
  constructor() {
    Amplify.configure(awsExports);
  }

  ngOnInit() {
    I18n.putVocabularies(translations);
    I18n.setLanguage('en');
    I18n.putVocabulariesForLanguage('en', {
      'Invalid code or auth state for the user.': 'translated text',
    });
  }
}

<amplify-authenticator>
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.attributes?.email }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>

// examples/vue/src/pages/ui/components/authenticator/sign-in-sms-mfa/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import { I18n } from 'aws-amplify/utils';
import '@aws-amplify/ui-vue/styles.css';
import { Authenticator } from '@aws-amplify/ui-vue';
import { translations } from '@aws-amplify/ui';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

// @todo-migration remove cast
I18n.putVocabularies(translations);
I18n.setLanguage('en');

I18n.putVocabulariesForLanguage('en', {
  'Invalid code or auth state for the user.': 'translated text',
});
</script>

<template>
  <authenticator>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.attributes?.email }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
