// examples/next/pages/ui/components/authenticator/sign-in-with-phone/index.tsx
import { Amplify } from 'aws-amplify';
import { I18n } from 'aws-amplify/utils';

import { withAuthenticator, translations } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';

Amplify.configure(awsExports);

I18n.putVocabularies(translations);
I18n.setLanguage('en');
I18n.putVocabulariesForLanguage('en', {
  'Password does not conform to policy: Password not long enough':
    'Your password is too short! Try a longer password!',
});

const formFields = {
  signIn: {
    username: {
      dialCode: '+82',
    },
  },
  signUp: {
    phone_number: {
      dialCode: '+227',
      dialCodeList: ['+1', '+82', '+227', '+100'],
    },
  },
};

function App({ user, signOut }) {
  return (
    <>
      <h2>Welcome, {user.username}</h2>
      <button onClick={signOut}>Sign out</button>
    </>
  );
}

export default withAuthenticator(App, {
  formFields: formFields,
});

// examples/svelte/src/routes/ui/components/authenticator/sign-in-with-phone/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { I18n } from 'aws-amplify/utils';
  import { Authenticator, translations } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);

  I18n.putVocabularies(translations);
  I18n.setLanguage('en');
  I18n.putVocabulariesForLanguage('en', {
    'Password does not conform to policy: Password not long enough':
      'Your password is too short! Try a longer password!',
  });

  const formFields = {
    signIn: {
      username: {
        dialCode: '+82',
      },
    },
    signUp: {
      phone_number: {
        dialCode: '+227',
        dialCodeList: ['+1', '+82', '+227', '+100'],
      },
    },
  };
</script>


<Authenticator formFields={formFields}>
  {#snippet children({user, signOut})}
    <h1>Hello { user.username }!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>
