// examples/next/pages/ui/components/authenticator/useAuthenticator/index.tsx
import router from 'next/router';

import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
import { Authenticator } from '@aws-amplify/ui-react';

Amplify.configure(awsExports);

export default function App() {
  const navigateHome = () => router.push('useAuthenticator/home');

  return (
    <Authenticator>
      <button onClick={navigateHome}>Navigate to Home</button>
    </Authenticator>
  );
}

// examples/vue/src/pages/ui/components/authenticator/gen2/useAuthenticator/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { Amplify } from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from './amplify_outputs';

Amplify.configure(amplifyOutputs);

const { route } = toRefs(useAuthenticator());
const props = useAuthenticator();
</script>

<template>
  <authenticator>
    <template v-slot>
      <router-link to="useAuthenticator/home">
        <button>Navigate to Home</button>
      </router-link>
    </template>
  </authenticator>
</template>
