// packages/react/src/components/Authenticator/SignUp/SignUp.tsx
import { translate } from '@aws-amplify/ui';

import { useAuthenticator } from '..';
import { Button, Flex, Form, View } from '../../..';
import { FederatedSignIn } from '../FederatedSignIn';
import { RemoteErrorMessage } from '../shared';
import { FormFields } from './FormFields';

export function SignUp() {
  const { components, hasValidationErrors, isPending, submitForm, updateForm } =
    useAuthenticator();

  const {
    SignUp: {
      Header = SignUp.Header,
      FormFields = SignUp.FormFields,
      Footer = SignUp.Footer,
    },
  } = components;

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    let { checked, name, type, value } = event.target;
    if (type === 'checkbox' && !checked) value = undefined;

    updateForm({ name, value });
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    submitForm();
  };

  return (
    <View>
      <Header />

      <Form
        data-amplify-authenticator-signup=""
        method="post"
        onChange={handleChange}
        onSubmit={handleSubmit}
      >
        <FederatedSignIn />

        <Flex direction="column">
          <Flex direction="column">
            <FormFields />
            <RemoteErrorMessage />
          </Flex>

          <Button
            borderRadius={0}
            isDisabled={hasValidationErrors || isPending}
            isFullWidth={true}
            type="submit"
            variation="primary"
            isLoading={isPending}
            loadingText={translate('Creating Account')}
            fontWeight="normal"
          >
            {translate('Create Account')}
          </Button>
        </Flex>
      </Form>

      <Footer />
    </View>
  );
}

SignUp.Header = (): JSX.Element => null;
SignUp.FormFields = FormFields;
SignUp.Footer = (): JSX.Element => null;

// packages/svelte/src/lib/components/SignUp.svelte
<script lang="ts">
  import {
    updateForm,
    submitForm,
    error,
    isPending,
    hasValidationErrors,
  } from '$lib/components/authStore';
  import AmplifyError from './primitives/AmplifyError.svelte';
  import AmplifyButton from './primitives/AmplifyButton.svelte';
  import AmplifySignUpFormFields from './AmplifySignUpFormFields.svelte';

  import { translate } from '@aws-amplify/ui';

  const createAccountText = translate('Create Account');

  function onInput(event: Event) {
    let { checked, name, type, value } = <HTMLInputElement>event.target;

    if (type === 'checkbox' && !checked) value = undefined;
    updateForm({ name, value });
  }

  function onSubmit(event: Event): void {
    submitForm();
  }
</script>

<form data-amplify-form on:submit|preventDefault={onSubmit} on:input={onInput}>
  <div class="amplify-flex" style="flex-direction: column">
    <div class="amplify-flex" style="flex-direction: column">
      <AmplifySignUpFormFields />
      {#if $error}
        <AmplifyError>
          {$error}
        </AmplifyError>
      {/if}
    </div>

    <AmplifyButton
      disabled={$isPending || $hasValidationErrors}
      amplify-button
      variation="primary"
      fullWidth="true"
      type="submit"
    >
      {createAccountText}
    </AmplifyButton>
  </div>
</form>
