// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.ts
import { Component, HostBinding, ViewEncapsulation } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import {
  translate,
  getFormDataFromEvent,
  FormFieldsArray,
} from '@aws-amplify/ui';

@Component({
  selector: 'amplify-sign-in',
  templateUrl: './sign-in.component.html',
  encapsulation: ViewEncapsulation.None,
})
export class SignInComponent {
  @HostBinding('attr.data-amplify-authenticator-signin') dataAttr = '';

  // translated phrases
  // Support backwards compatibility for legacy key with trailing space
  public forgotPasswordText = translate('Forgot your password?');
  public signInButtonText = translate('Sign in');
  public sortedFormFields: FormFieldsArray;

  constructor(public authenticator: AuthenticatorService) {}

  public get context() {
    return this.authenticator.slotContext;
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<div data-amplify-container>
  <amplify-slot name="sign-in-header" [context]="context"></amplify-slot>

  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <amplify-federated-sign-in></amplify-federated-sign-in>
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="authenticator.isPending"
    >
      <amplify-user-name-alias
        [labelHidden]="labelHidden('username')"
        [placeholder]="userOverrides?.placeholder"
        [required]="required('username')"
        [label]="userOverrides?.label"
        [dialCode]="userOverrides?.dialCode"
        [dialCodeList]="userOverrides?.dialCodeList"
      ></amplify-user-name-alias>
      <amplify-form-field
        [labelHidden]="labelHidden('password')"
        [placeholder]="passwordOR?.placeholder"
        [required]="required('password')"
        [label]="passwordOR?.label"
        data-amplify-password
        name="password"
        type="password"
        autocomplete="current-password"
      ></amplify-form-field>
      <button amplify-button variation="primary" fullWidth="true" type="submit">
        {{ signInButtonText }}
      </button>

      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </fieldset>
  </form>

  <amplify-slot name="sign-in-footer" [context]="context">
    <div data-amplify-footer>
      <button
        amplify-button
        fontWeight="normal"
        size="small"
        variation="link"
        fullWidth="true"
        (click)="authenticator.toResetPassword()"
      >
        {{ forgotPasswordText }}
      </button>
    </div>
  </amplify-slot>
</div>

// packages/svelte/src/lib/components/SignIn.svelte
<script lang="ts">
	import AmplifyFormField from './primitives/AmplifyFormField.svelte';
	import AmplifyError from './primitives/AmplifyError.svelte';
	import UserNameAlias from './UserNameAlias.svelte';
	import AmplifyButton from './primitives/AmplifyButton.svelte';
	import { translate } from '@aws-amplify/ui';
	import { updateForm, submitForm, isPending, error, toResetPassword } from '$lib/components/store';

	const forgotPasswordText = translate('Forgot your password? ');
	const signInButtonText = translate('Sign in');
	const signIngButtonText = translate('Signing in');

	function onInput(event: Event) {
		event.preventDefault();
		const { name, value } = <HTMLInputElement>event.target;
		updateForm({ name, value });
	}

	function onSubmit(event: Event): void {
		event.preventDefault();
		submitForm();
	}
</script>

<div data-amplify-container>
	<form data-amplify-form on:submit|preventDefault={onSubmit} on:input={onInput}>
		<fieldset
			class="amplify-flex"
			style="flex-direction: column"
			data-amplify-fieldset
			disabled={$isPending}
		>
			<UserNameAlias />
			<AmplifyFormField
				data-amplify-password
				name="password"
				type="password"
				autocomplete="current-password"
			/>
			<AmplifyButton disabled={$isPending} variation="primary" fullWidth="true" type="submit">
				{$isPending ? signIngButtonText : signInButtonText}
			</AmplifyButton>

			{#if $error}
				<AmplifyError>
					{$error}
				</AmplifyError>
			{/if}
		</fieldset>
	</form>

	<div data-amplify-footer>
		<AmplifyButton
			amplify-button
			fontWeight="normal"
			data-size="small"
			variation="link"
			fullWidth="true"
			on:click={toResetPassword}
		>
			{forgotPasswordText}
		</AmplifyButton>
	</div>
</div>
