// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/user-name-alias/user-name-alias.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { getAliasInfoFromContext } from '@aws-amplify/ui';

@Component({
  selector: 'amplify-user-name-alias',
  templateUrl: './user-name-alias.component.html',
})
export class AmplifyUserNameAliasComponent implements OnInit {
  @Input() name: string = 'username';
  @Input() disabled: boolean = false;
  @Input() initialValue: string = '';
  @Input() required: boolean = true;
  public label: string;
  public type: string;
  public error: string;
  public placeholder: string;

  constructor(private authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    const context = this.authenticator.context;
    const { label, type } = getAliasInfoFromContext(context);

    this.label = label;
    this.type = type;
    this.placeholder = label;
  }
}

<amplify-form-field
  data-amplify-usernamealias
  [name]="name"
  [label]="label"
  [type]="type"
  [placeholder]="placeholder"
  [initialValue]="initialValue"
  [disabled]="disabled"
  [required]="required"
  [defaultCountryCode]="isPhoneField() ? defaultCountryCode : null"
  autocomplete="username"
  (input)="isPhoneField() ? handlePhoneNumberChange($event) : null"
>
</amplify-form-field>

// packages/svelte/src/lib/components/UserNameAlias.svelte
<script lang="ts">
  import AmplifyFormField from './primitives/AmplifyFormField.svelte';
  import { onMount } from 'svelte';
  import { authState } from '$lib/components/authStore';
  import { getAliasInfoFromContext } from '@aws-amplify/ui';
  export let name: string = 'username';
  export let disabled: boolean = false;
  export let initialValue: string = '';
  export let required: boolean = true;
  let label: string;
  let type: string;
  let error: string;
  let placeholder: string;

  onMount(() => {
    const { label, type } = getAliasInfoFromContext($authState.context);

    placeholder = label;
  });
</script>

<AmplifyFormField
  data-amplify-usernamealias
  {name}
  {label}
  {type}
  {placeholder}
  {initialValue}
  {disabled}
  {required}
  autocomplete="username"
/>
