// examples/angular/src/pages/ui/components/authenticator/sign-in-totp-mfa/sign-in-totp-mfa.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';

import awsExports from './aws-exports';

@Component({
  selector: 'sign-in-totp-mfa',
  templateUrl: 'sign-in-totp-mfa.component.html',
})
export class SignInTOTPMFAComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
  public formFields = {
    setupTotp: { QR: { totpIssuer: 'My Web App' } },
  };
}

<amplify-authenticator>
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <span>{{ authenticator.user?.username }}</span>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>

// examples/next/pages/ui/components/authenticator/sign-in-totp-mfa/index.tsx
import { Amplify } from 'aws-amplify';

import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default function SignInTotpMfa() {
  const formFields = {
    setupTotp: { QR: { totpIssuer: 'My Web App' } },
  };

  return (
    <>
      <Authenticator formFields={formFields}>
        {({ signOut, user }) => (
          <>
            <span>{user.username}</span>
            <button onClick={signOut}>Sign out</button>
          </>
        )}
      </Authenticator>
    </>
  );
}
