// examples/vue/src/pages/ui/components/authenticator/sign-up-with-attributes/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import {
  Authenticator,
  AuthenticatorForceNewPasswordFormFields,
  AmplifyTextField,
} from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import { importHelper } from '../utils';

const amplifyOutputs = await importHelper('auth-with-all-attributes');

Amplify.configure(amplifyOutputs);
</script>

<template>
  <authenticator initial-state="signUp">
    <template v-slot:force-new-password-form-fields>
      <authenticator-force-new-password-form-fields />
      <amplify-text-field
        label="Zone Info"
        id="12233"
        autocomplete="false"
        placeholder="Zone Info"
        name="zoneinfo"
        :hideLabel="false"
      />
    </template>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/sign-up-with-attributes/sign-up-with-attributes.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';

const amplifyOutputs = (
  await import(
    `@environments/auth/auth-with-all-attributes/${process.env.PATH}`
  )
).default;

@Component({
  selector: 'sign-up-with-attributes',
  templateUrl: 'sign-up-with-attributes.component.html',
})
export class SignUpWithAttributesComponent {
  constructor() {
    Amplify.configure(amplifyOutputs);
  }
}

<amplify-authenticator initialState="signUp">
  <ng-template amplifySlot="sign-up-form-fields">
    <amplify-sign-up-form-fields></amplify-sign-up-form-fields>
    <amplify-text-field
      label="Zone Info"
      placeholder="Zone Info"
      name="zoneinfo"
    ></amplify-text-field>
    <amplify-text-field label="Gender" name="gender"></amplify-text-field>
    <amplify-text-field
      label="Updated At"
      placeholder="1699880541"
      name="updated_at"
    ></amplify-text-field>
    <amplify-text-field label="Address" name="address"></amplify-text-field>
    <amplify-text-field label="Locale" name="locale"></amplify-text-field>
    <amplify-text-field label="Picture" name="picture"></amplify-text-field>
  </ng-template>
  <ng-template amplifySlot="force-new-form-fields">
    <amplify-force-new-password-form-fields></amplify-force-new-password-form-fields>
  </ng-template>
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>
