// examples/vue/src/pages/ui/components/authenticator/auth-with-multi-alias/index.vue
<script setup lang="ts">
import { Amplify } from '@aws-amplify/core';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from '@environments/auth-with-multi-alias/src/aws-exports';

Amplify.configure(aws_exports);
</script>

<template>
  <authenticator :login-mechanisms="['username', 'email', 'phone_number']">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/auth-with-multi-alias/auth-with-multi-alias.component.ts
import { Component } from '@angular/core';
import Amplify from 'aws-amplify';
import awsExports from '@environments/auth-with-multi-alias/src/aws-exports';

@Component({
  selector: 'auth-with-multi-alias',
  templateUrl: 'auth-with-multi-alias.component.html',
})
export class AuthWithMultiAliasComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator
  [loginMechanisms]="['username', 'email', 'phone_number']"
>
  <ng-template
    amplifyOverride="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>
