// examples/vue/src/pages/ui/components/authenticator/useAuthenticator/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { Amplify } from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

const { route } = toRefs(useAuthenticator());
const props = useAuthenticator();
</script>

<template>
  <authenticator>
    <template v-slot>
      <router-link to="useAuthenticator/home">
        <button>Navigate to Home</button>
      </router-link>
    </template>
  </authenticator>
</template>

// examples/svelte/src/routes/ui/components/authenticator/useAuthenticator/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { Authenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
</script>

<Authenticator>
  <a href="./useAuthenticator/home">Navigate to Home</a>
</Authenticator>
