// examples/next/pages/ui/components/authenticator/useAuthenticator/index.tsx
import router from 'next/router';

import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
import { Authenticator } from '@aws-amplify/ui-react';

Amplify.configure(awsExports);

export default function App() {
  const navigateHome = () => router.push('useAuthenticator/home');

  return (
    <Authenticator>
      <button onClick={navigateHome}>Navigate to Home</button>
    </Authenticator>
  );
}

// examples/svelte/src/routes/ui/components/authenticator/useAuthenticator/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { Amplify } from 'aws-amplify';
  import { Authenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
  const handleClick = () => goto('useAuthenticator/home')
</script>

<Authenticator>
  <button onclick={handleClick}>Navigate to Home</button>
</Authenticator>
