// packages/vue/src/components/confirm-reset-password.vue
<script setup lang="ts">
import { defineEmits, computed, toRefs, useAttrs } from 'vue';

import {
  authenticatorTextUtil,
  getFormDataFromEvent,
  translate,
} from '@aws-amplify/ui';

import { useAuthenticator } from '../composables/useAuth';
import { UseAuthenticator } from '../types';
import BaseFormFields from './primitives/base-form-fields.vue';

// `facade` is manually typed to `UseAuthenticator` for temporary type safety.
const facade: UseAuthenticator = useAuthenticator();
const { resendCode, submitForm, updateBlur, updateForm } = facade;
const { error, isPending } = toRefs(facade);

/** @deprecated Component events are deprecated and not maintained. */
const emit = defineEmits(['confirmResetPasswordSubmit', 'backToSignInClicked']);
const attrs = useAttrs();

// Text Util
const { getResendCodeText, getResetYourPasswordText, getSubmitText } =
  authenticatorTextUtil;

// Computed Properties
const resendCodeText = computed(() => getResendCodeText());
const confirmResetPasswordHeading = computed(() => getResetYourPasswordText());
const confirmResetPasswordText = computed(() => getSubmitText());

// Methods
const onConfirmResetPasswordSubmit = (e: Event): void => {
  // TODO(BREAKING): remove unused emit
  // istanbul ignore next
  if (attrs?.onConfirmResetPasswordSubmit) {
    emit('confirmResetPasswordSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  submitForm(getFormDataFromEvent(e));
};

const onLostYourCodeClicked = (): void => {
  resendCode();
};

const onInput = (e: Event) => {
  const { name, value } = e.target as HTMLInputElement;
  updateForm({ name, value });
};

function onBlur(e: Event) {
  const { name } = e.target as HTMLInputElement;
  updateBlur({ name });
}
</script>

<template>
  <slot v-bind="$attrs" name="confirmResetPasswordSlotI">
    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-confirmResetpassword
        @input="onInput"
        @blur.capture="onBlur"
        @submit.prevent="onConfirmResetPasswordSubmit"
      >
        <base-field-set
          class="amplify-flex amplify-authenticator__column"
          :disabled="isPending"
        >
          <slot name="header">
            <base-heading class="amplify-heading" :level="3">
              {{ confirmResetPasswordHeading }}
            </base-heading>
          </slot>

          <base-wrapper class="amplify-flex amplify-authenticator__column">
            <base-form-fields route="confirmResetPassword"></base-form-fields>
          </base-wrapper>
          <base-footer class="amplify-flex amplify-authenticator__column">
            <base-alert v-if="error">
              {{ translate(error) }}
            </base-alert>
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              :variation="'primary'"
              :fullwidth="false"
              type="submit"
              :disabled="isPending"
            >
              {{ confirmResetPasswordText }}
            </amplify-button>
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              :variation="'link'"
              :fullwidth="false"
              :size="'small'"
              type="button"
              @click.prevent="onLostYourCodeClicked"
            >
              {{ resendCodeText }}
            </amplify-button>
            <slot
              name="footer"
              :onConfirmResetPasswordSubmit="onConfirmResetPasswordSubmit"
              :onLostYourCodeClicked="onLostYourCodeClicked"
            >
            </slot>
          </base-footer>
        </base-field-set>
      </base-form>
    </base-wrapper>
  </slot>
</template>

// packages/svelte/src/lib/components/Authenticator/ConfirmResetPassword.svelte
<script lang="ts">
  import {
    authenticatorTextUtil,
    getFormDataFromEvent,
    translate,
  } from '@aws-amplify/ui';

  import { useAuthenticator } from '../../stores/authenticator.svelte';
  import { type Components } from '../../types';

  import Wrapper from '../primitives/Wrapper.svelte';
  import Form from '../primitives/Form.svelte';
  import Button from '../controls/Button.svelte';
  import FieldSet from '../primitives/FieldSet.svelte';
  import FormFields from '../primitives/FormFields.svelte';
  import Heading from '../primitives/Heading.svelte';
  import Footer from '../primitives/Footer.svelte';
  import Alert from '../primitives/Alert.svelte';

  interface Props {
    components?: Components;
  }

  const { components }: Props = $props();

  const { authenticator } = $derived(useAuthenticator());

  // Text Util
  const { getResendCodeText, getResetYourPasswordText, getSubmitText } =
    authenticatorTextUtil;

  // Computed Properties
  const resendCodeText = $derived.by(() => getResendCodeText());
  const confirmResetPasswordHeading = $derived.by(() =>
    getResetYourPasswordText()
  );
  const confirmResetPasswordText = $derived.by(() => getSubmitText());

  // Methods
  const onConfirmResetPasswordSubmit = (e: Event): void => {
    e.preventDefault();
    submit(e);
  };

  const submit = (e: Event): void => {
    authenticator.submitForm(getFormDataFromEvent(e));
  };

  const onLostYourCodeClicked = (e: Event): void => {
    e.preventDefault();
    authenticator.resendCode();
  };

  const onInput = (e: Event) => {
    const { name, value } = e.target as HTMLInputElement;
    authenticator.updateForm({ name, value });
  };

  function onBlur(e: Event) {
    const { name } = e.target as HTMLInputElement;
    authenticator.updateBlur({ name });
  }
</script>

<Wrapper>
  <Form
    data-amplify-authenticator-confirmResetpassword
    oninput={onInput}
    onblurcapture={onBlur}
    onsubmit={onConfirmResetPasswordSubmit}
  >
    <FieldSet
      class="amplify-flex amplify-authenticator__column"
      disabled={authenticator.isPending}
    >
      {#if components?.Header}
        {@render components?.Header()}
      {:else}
        <Heading class="amplify-heading" level="h3">
          {confirmResetPasswordHeading}
        </Heading>
      {/if}
      <Wrapper class="amplify-flex amplify-authenticator__column">
        {#if components?.FormFields}
          {@render components?.FormFields()}
        {:else}
          <FormFields route="confirmResetPassword" />
        {/if}
      </Wrapper>
      <Footer class="amplify-flex amplify-authenticator__column">
        {#if authenticator.error}
          <Alert>
            {translate(authenticator.error)}
          </Alert>
        {/if}
        <Button
          class="amplify-field-group__control amplify-authenticator__font"
          variation="primary"
          fullWidth={false}
          type="submit"
          disabled={authenticator.isPending}
        >
          {confirmResetPasswordText}
        </Button>
        <Button
          class="amplify-field-group__control amplify-authenticator__font"
          variation="link"
          fullWidth={false}
          size="small"
          type="button"
          onclick={onLostYourCodeClicked}
        >
          {resendCodeText}
        </Button>
        {@render components?.Footer?.()}
      </Footer>
    </FieldSet>
  </Form>
</Wrapper>
