// packages/vue/src/components/confirm-sign-up.vue
<script setup lang="ts">
import { computed, useAttrs, toRefs, onBeforeMount } from 'vue';
import { getFormDataFromEvent, translate } from '@aws-amplify/ui';

import { useAuthenticator, useAuth } from '../composables/useAuth';
import { createSharedComposable } from '@vueuse/core';
import BaseFormFields from './primitives/base-form-fields.vue';

const attrs = useAttrs();
const emit = defineEmits(['confirmSignUpSubmit', 'lostCodeClicked']);

const useAuthShared = createSharedComposable(useAuthenticator);
const { isPending, error, codeDeliveryDetails } = toRefs(useAuthShared());
const { submitForm, updateForm, resendCode } = useAuthShared();
const { state } = useAuth();

// Only two types of delivery methods is EMAIL or SMS
const confirmSignUpHeading = computed(() => {
  return codeDeliveryDetails.value?.DeliveryMedium === 'EMAIL'
    ? translate('We Emailed You')
    : codeDeliveryDetails.value?.DeliveryMedium === 'SMS'
    ? translate('We Texted You')
    : translate('We Sent A Code');
});

const resendCodeText = computed(() => translate('Resend Code'));
const confirmText = computed(() => translate('Confirm'));
const emailMessage = translate(
  'Your code is on the way. To log in, enter the code we emailed to'
);
const textedMessage = translate(
  'Your code is on the way. To log in, enter the code we texted to'
);
const defaultMessage = translate(
  'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.'
);
const minutesMessage = translate('It may take a minute to arrive.');
const subtitleText = computed(() => {
  return codeDeliveryDetails.value?.DeliveryMedium === 'EMAIL'
    ? `${emailMessage} ${codeDeliveryDetails.value?.Destination}. ${minutesMessage}`
    : codeDeliveryDetails.value?.DeliveryMedium === 'SMS'
    ? `${textedMessage} ${codeDeliveryDetails.value?.Destination}. ${minutesMessage}`
    : translate(`${defaultMessage}`);
});

// Methods
const onInput = (e: Event): void => {
  const { name, value } = <HTMLInputElement>e.target;
  updateForm({ name, value });
};

const onConfirmSignUpSubmit = (e: Event): void => {
  if (attrs?.onConfirmSignUpSubmit) {
    emit('confirmSignUpSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  submitForm(getFormDataFromEvent(e));
};

const onLostCodeClicked = (): void => {
  if (attrs?.onLostCodeClicked) {
    emit('lostCodeClicked');
  } else {
    resendCode();
  }
};
</script>

<template>
  <slot v-bind="$attrs" name="confirmSignUpSlotI">
    <base-wrapper v-bind="$attrs">
      <base-form @input="onInput" @submit.prevent="onConfirmSignUpSubmit">
        <base-wrapper class="amplify-flex amplify-authenticator__column">
          <slot name="header">
            <base-heading
              class="amplify-heading amplify-authenticator__heading"
              :level="3"
            >
              {{ confirmSignUpHeading }}
            </base-heading>
          </slot>
          <base-text class="amplify-authenticator__subtitle">
            {{ subtitleText }}
          </base-text>
          <base-field-set
            class="amplify-flex amplify-authenticator__column"
            :disabled="isPending"
          >
            <base-form-fields route="confirmSignUp"></base-form-fields>
          </base-field-set>

          <base-footer
            class="
              amplify-flex
              amplify-authenticator__column amplify-authenticator__footer
            "
          >
            <base-alert v-if="error">
              {{ translate(error) }}
            </base-alert>
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              data-fullwidth="false"
              data-loading="false"
              data-variation="primary"
              type="submit"
              :disabled="isPending"
            >
              {{ confirmText }}
            </amplify-button>
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              data-fullwidth="false"
              data-variation="default"
              type="button"
              @click.prevent="onLostCodeClicked"
            >
              {{ resendCodeText }}
            </amplify-button>
            <slot
              name="footer"
              :onConfirmSignUpSubmit="onConfirmSignUpSubmit"
              :onLostCodeClicked="onLostCodeClicked"
            >
            </slot>
          </base-footer>
        </base-wrapper>
      </base-form>
    </base-wrapper>
  </slot>
</template>

// packages/svelte/src/lib/components/Authenticator/ConfirmSignUp.svelte
<script lang="ts">
  import {
    authenticatorTextUtil,
    getFormDataFromEvent,
    translate,
  } from '@aws-amplify/ui';

  import { useAuthenticator } from '../../stores/authenticator.svelte';
  import { type Components } from '../../types';

  import Wrapper from '../primitives/Wrapper.svelte';
  import Form from '../primitives/Form.svelte';
  import Heading from '../primitives/Heading.svelte';
  import Text from '../primitives/Text.svelte';
  import FieldSet from '../primitives/FieldSet.svelte';
  import FormFields from '../primitives/FormFields.svelte';
  import Footer from '../primitives/Footer.svelte';
  import Alert from '../primitives/Alert.svelte';
  import Button from '../controls/Button.svelte';

  interface Props {
    components?: Components;
  }

  const { components }: Props = $props();

  const { authenticator } = $derived(useAuthenticator());

  // Text Util
  const {
    getDeliveryMethodText,
    getDeliveryMessageText,
    getResendCodeText,
    getConfirmText,
  } = authenticatorTextUtil;

  // Only two types of delivery methods is EMAIL or SMS
  const confirmSignUpHeading = $derived.by(() =>
    getDeliveryMethodText(authenticator.codeDeliveryDetails)
  );

  // Computed Properties
  const resendCodeText = $derived.by(() => getResendCodeText());
  const confirmText = $derived.by(() => getConfirmText());
  const subtitleText = $derived.by(() =>
    getDeliveryMessageText(authenticator.codeDeliveryDetails)
  );

  // Methods
  const onInput = (e: Event): void => {
    const { name, value } = e.target as HTMLInputElement;
    authenticator.updateForm({ name, value });
  };

  const onConfirmSignUpSubmit = (e: Event): void => {
    e.preventDefault();
    submit(e);
  };

  const submit = (e: Event): void => {
    authenticator.submitForm(getFormDataFromEvent(e));
  };

  const onLostCodeClicked = (e: Event): void => {
    e.preventDefault();
    authenticator.resendCode();
  };
</script>

<Wrapper>
  <Form oninput={onInput} onsubmit={onConfirmSignUpSubmit}>
    <Wrapper class="amplify-flex amplify-authenticator__column">
      {#if components?.Header}
        {@render components?.Header()}
      {:else}
        <Heading
          class="amplify-heading amplify-authenticator__heading"
          level="h3"
        >
          {confirmSignUpHeading}
        </Heading>
      {/if}
      <Text class="amplify-authenticator__subtitle">
        {subtitleText}
      </Text>
      <FieldSet
        class="amplify-flex amplify-authenticator__column"
        disabled={authenticator.isPending}
      >
        {#if components?.FormFields}
          {@render components?.FormFields()}
        {:else}
          <FormFields route="confirmSignUp" />
        {/if}
      </FieldSet>

      <Footer class="amplify-flex amplify-authenticator__column">
        {#if authenticator.error}
          <Alert>
            {translate(authenticator.error)}
          </Alert>
        {/if}
        <Button
          class="amplify-field-group__control amplify-authenticator__font"
          fullWidth={false}
          loading={false}
          variation="primary"
          type="submit"
          disabled={authenticator.isPending}
        >
          {confirmText}
        </Button>
        <Button
          class="amplify-field-group__control amplify-authenticator__font"
          fullWidth={false}
          variation="default"
          style="font-weight: normal"
          type="button"
          onclick={onLostCodeClicked}
        >
          {resendCodeText}
        </Button>
        {@render components?.Footer?.()}
      </Footer>
    </Wrapper>
  </Form>
</Wrapper>
