// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/forgot-password/forgot-password.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import {
  FormFieldsArray,
  getFormDataFromEvent,
  authenticatorTextUtil,
} from '@aws-amplify/ui';

const { getResetYourPasswordText, getSendCodeText, getBackToSignInText } =
  authenticatorTextUtil;

@Component({
  selector: 'amplify-forgot-password',
  templateUrl: './forgot-password.component.html',
})
export class ForgotPasswordComponent {
  @HostBinding('attr.data-amplify-authenticator-forgotPassword') dataAttr = '';
  @Input() public headerText = getResetYourPasswordText();

  // translated texts
  public sendCodeText = getSendCodeText();
  public backToSignInText = getBackToSignInText();
  public sortedFormFields: FormFieldsArray;

  constructor(public authenticator: AuthenticatorService) {}

  public get context(): AuthenticatorService['slotContext'] {
    return this.authenticator.slotContext;
  }

  onInput(event: Event): void {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
  <fieldset
    class="amplify-flex amplify-authenticator__column"
    data-amplify-fieldset
    [disabled]="authenticator.isPending"
  >
    <amplify-slot
      class="amplify-flex"
      name="forgot-password-header"
      [context]="context"
    >
      <h3 class="amplify-heading amplify-heading--3">{{ this.headerText }}</h3>
    </amplify-slot>

    <amplify-base-form-fields route="forgotPassword"></amplify-base-form-fields>
    <button
      amplify-button
      variation="primary"
      fullWidth="true"
      type="submit"
      [isDisabled]="authenticator.isPending"
    >
      {{ sendCodeText }}
    </button>
    <button
      amplify-button
      size="small"
      variation="link"
      fontWeight="normal"
      fullWidth="true"
      (click)="authenticator.toSignIn()"
    >
      {{ backToSignInText }}
    </button>
    <amplify-error *ngIf="authenticator.error">
      {{ authenticator.error }}
    </amplify-error>
  </fieldset>

  <amplify-slot name="forgot-password-footer" [context]="context">
  </amplify-slot>
</form>

// packages/svelte/src/lib/components/Authenticator/ForgotPassword.svelte
<script lang="ts">
	import { authenticatorTextUtil, getFormDataFromEvent, translate } from '@aws-amplify/ui';

	import { useAuthenticator } from '../../stores/authenticator.svelte';
	import { type Components } from '../../types';

	import Form from '../primitives/Form.svelte';
	import Wrapper from '../primitives/Wrapper.svelte';
	import Heading from '../primitives/Heading.svelte';
	import FieldSet from '../primitives/FieldSet.svelte';
	import FormFields from '../primitives/FormFields.svelte';
	import Footer from '../primitives/Footer.svelte';
	import Alert from '../primitives/Alert.svelte';
	import Button from '../controls/Button.svelte';

	interface Props {
		components?: Components;
	}

	const { components }: Props = $props();

	const { submitForm, toSignIn, updateForm, error, isPending } = $derived(useAuthenticator());

	// Text Util
	const { getBackToSignInText, getResetYourPasswordText, getSendCodeText } = authenticatorTextUtil;

	// Computed Properties
	const backSignInText = $derived.by(() => getBackToSignInText());
	const resetPasswordHeading = $derived.by(() => getResetYourPasswordText());
	const sendCodeText = $derived.by(() => getSendCodeText());

	// Methods
	const onResetPasswordSubmit = (e: Event): void => {
		e.preventDefault();
		submitForm(getFormDataFromEvent(e));
	};

	const onInput = (e: Event): void => {
		const { name, value } = e.target as HTMLInputElement;
		updateForm({ name, value });
	};

	const onBackToSignInClicked = (e: Event): void => {
		e.preventDefault();
		toSignIn();
	};
</script>

<Form data-amplify-authenticator-forgotpassword oninput={onInput} onsubmit={onResetPasswordSubmit}>
	<Wrapper class="amplify-flex amplify-authenticator__column">
		{#if components?.Header}
			{@render components?.Header()}
		{:else}
			<Heading class="amplify-heading" level="h3">
				{resetPasswordHeading}
			</Heading>
		{/if}
		<FieldSet class="amplify-flex amplify-authenticator__column" disabled={isPending}>
			{#if components?.FormFields}
				{@render components?.FormFields()}
			{:else}
				<FormFields route="forgotPassword" />
			{/if}
		</FieldSet>

		<Footer class="amplify-flex amplify-authenticator__column">
			{#if error}
				<Alert>
					{translate(error)}
				</Alert>
			{/if}
			<Button
				class="amplify-field-group__control amplify-authenticator__font"
				fullWidth={false}
				variation="primary"
				type="submit"
				disabled={isPending}
			>
				{sendCodeText}
			</Button>
			<Button
				class="amplify-field-group__control amplify-authenticator__font"
				fullWidth={false}
				size="small"
				variation="link"
				fontWeight="normal"
				type="button"
				onclick={onBackToSignInClicked}
			>
				{backSignInText}
			</Button>
			{@render components?.Footer?.()}
		</Footer>
	</Wrapper>
</Form>
