// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-email/setup-email.component.ts
import { Component } from '@angular/core';
import {
  authenticatorTextUtil,
  classNames,
  ComponentClassName,
  getFormDataFromEvent,
} from '@aws-amplify/ui';

import { AuthenticatorService } from '../../../../services/authenticator.service';

const { getConfirmText, getBackToSignInText, getSetupEmailText } =
  authenticatorTextUtil;

@Component({
  selector: 'amplify-setup-email',
  templateUrl: './setup-email.component.html',
})
export class SetupEmailComponent {
  public headerText = getSetupEmailText();
  public confirmText = getConfirmText();
  public backToSignInText = getBackToSignInText();

  public classNames = classNames;
  public ComponentClassName = ComponentClassName;

  constructor(public authenticator: AuthenticatorService) {}

  public get context(): AuthenticatorService['slotContext'] {
    return this.authenticator.slotContext;
  }

  onInput(event: Event): void {
    event.preventDefault();

    const { name, value } = event.target as HTMLInputElement;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<form
    data-amplify-form
    data-amplify-authenticator-setup-email
    (submit)="onSubmit($event)"
    (input)="onInput($event)"
>
    <fieldset
        [class]="classNames(ComponentClassName.Flex, 'amplify-authenticator__column')"
        data-amplify-fieldset
        [disabled]="authenticator.isPending"
    >
        <amplify-slot
            name="select-mfa-type-header"
            [context]="context"
        >
            <h3 [class]="classNames(ComponentClassName.Heading, 'amplify-heading--3')">{{ headerText }}</h3>
        </amplify-slot>
        <amplify-base-form-fields route="setupEmail"></amplify-base-form-fields>

        <button
            amplify-button
            variation="primary"
            fullWidth="true"
            type="submit"
            [isDisabled]="authenticator.isPending"
        >
            {{ confirmText }}
        </button>
        <button
            amplify-button
            size="small"
            variation="link"
            fontWeight="normal"
            fullWidth="true"
            (click)="authenticator.toSignIn()"
        >
            {{ backToSignInText }}
        </button>
        <amplify-error *ngIf="authenticator.error">
            {{ authenticator.error }}
        </amplify-error>
    </fieldset>
    <amplify-slot
        name="select-mfa-type-footer"
        [context]="context"
    ></amplify-slot>
</form>

// packages/svelte/src/lib/components/Authenticator/SetupEmail.svelte
<script lang="ts">
	import { authenticatorTextUtil, getFormDataFromEvent, translate } from '@aws-amplify/ui';
	import { useAuthenticator } from '../../stores/authenticator.svelte';
	import { type Components } from '../../types';

	import Wrapper from '../primitives/Wrapper.svelte';
	import Form from '../primitives/Form.svelte';
	import Button from '../controls/Button.svelte';
	import FieldSet from '../primitives/FieldSet.svelte';
	import FormFields from '../primitives/FormFields.svelte';
	import Heading from '../primitives/Heading.svelte';
	import Footer from '../primitives/Footer.svelte';
	import Alert from '../primitives/Alert.svelte';

	interface Props {
		components?: Components;
	}

	const { components }: Props = $props();

	const { error, isPending, submitForm, toSignIn, updateForm } = $derived(useAuthenticator());
	const { getBackToSignInText, getConfirmText, getSetupEmailText } = authenticatorTextUtil;
	const setupEmailHeading = $derived.by(() => getSetupEmailText());
	const backSignInText = $derived.by(() => getBackToSignInText());
	const confirmText = $derived.by(() => getConfirmText());

	const onInput = (e: Event) => {
		const { name, value } = e.target as HTMLInputElement;
		updateForm({ name, value });
	};

	const onSetupEmailSubmit = (e: Event) => {
		e.preventDefault();
		submitForm(getFormDataFromEvent(e));
	};

	const onBackToSignInClicked = (e: Event) => {
		e.preventDefault();
		toSignIn();
	};
</script>

<Wrapper>
	<Form data-amplify-authenticator-setupemail oninput={onInput} onsubmit={onSetupEmailSubmit}>
		<FieldSet class="amplify-flex amplify-authenticator__column" disabled={isPending}>
			{#if components?.Header}
				{@render components?.Header()}
			{:else}
				<Heading level="h3" class="amplify-heading">
					{setupEmailHeading}
				</Heading>
			{/if}
			<Wrapper class="amplify-flex amplify-authenticator__column">
				{#if components?.FormFields}
					{@render components?.FormFields()}
				{:else}
					<FormFields route="setupEmail" />
				{/if}
			</Wrapper>
			<Footer class="amplify-flex amplify-authenticator__column">
				{#if error}
					<Alert>
						{translate(error)}
					</Alert>
				{/if}
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					loading={false}
					variation="primary"
					fontWeight="normal"
					disabled={isPending}
				>
					{confirmText}
				</Button>
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					size="small"
					variation="link"
					fontWeight="normal"
					type="button"
					onclick={onBackToSignInClicked}
				>
					{backSignInText}
				</Button>
				{@render components?.Footer?.()}
			</Footer>
		</FieldSet>
	</Form>
</Wrapper>
