// examples/vue/src/pages/ui/components/authenticator/sign-up/index.vue
<template>
  <Authenticator>
    <template v-slot="{ user }">
      <h1 class="text-6xl mb-10">Hello {{ user.username }}!</h1>
      <button
        className="px-2 bg-white rounded shadow"
        @click="send('SIGN_OUT')"
      >
        Sign Out
      </button>
    </template>
  </Authenticator>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import aws_exports from '@environments/auth-with-username-no-attributes/src/aws-exports';

import Amplify from 'aws-amplify';
import '@aws-amplify/ui-vue/styles.css';

import { Authenticator, useAuth } from '@aws-amplify/ui-vue';

Amplify.configure({
  ...aws_exports,
  auth: {
    login_mechanisms: ['username'],
  },
});

export default defineComponent({
  name: 'App',
  components: { Authenticator },
  setup() {
    const { send } = useAuth();
    return { send };
  },
});
</script>

// examples/angular/src/pages/ui/components/authenticator/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { Amplify } from 'aws-amplify';

import awsExports from '@environments/auth-with-username-no-attributes/src/aws-exports';

@Component({
  selector: 'sign-up',
  templateUrl: 'sign-up.component.html',
})
export class SignUpComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator>
  <ng-template
    amplifyOverride="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut($event)">Sign Out</button>
  </ng-template>
</amplify-authenticator>
