// examples/next/pages/ui/components/authenticator/sign-up/index.tsx
import { Authenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';

import awsExports from 'environments/auth-with-username-no-attributes/src/aws-exports';

Amplify.configure(awsExports);

export default function AuthenticatorWithUsername() {
  return <Authenticator />;
}

// examples/angular/src/pages/ui/components/authenticator/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { Amplify } from 'aws-amplify';

import awsExports from '@environments/auth-with-username-no-attributes/src/aws-exports';

@Component({
  selector: 'sign-up',
  templateUrl: 'sign-up.component.html',
})
export class SignUpComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator>
  <ng-template
    amplifyOverride="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut($event)">Sign Out</button>
  </ng-template>
</amplify-authenticator>
