// packages/svelte/src/lib/components/primitives/AmplifyButton.svelte
<script lang="ts">
	export let type: 'submit' | 'button' = 'button';
	export let fullWidth: boolean | string = false;
	export let size: 'small' | 'medium' | 'large' = 'medium';
	export let variation: 'primary' | 'default' | 'link' = 'default';
	export let fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();
</script>

<button
	{...$$restProps}
	on:click={() => dispatch('click')}
	class={`amplify-button ${$$props.class}`}
	{type}
	style="font-weight: {fontWeight} "
	data-fullwidth={fullWidth}
	data-size={size}
	data-fontWeight={fontWeight}
	data-variation={variation}
	data-amplify-button=""
>
	<slot />
</button>

// packages/angular/projects/ui-angular/src/lib/primitives/amplify-button/amplify-button.component.ts
import { Component, HostBinding, Input, OnInit } from '@angular/core';

@Component({
  selector: 'button[amplify-button]',
  templateUrl: './amplify-button.component.html',
})
export class AmplifyButtonComponent implements OnInit {
  @Input() type: 'submit' | 'button' = 'button';
  @Input() fullWidth: boolean | string = false;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() variation: 'primary' | 'default' | 'link' = 'default';
  @Input() fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

  @HostBinding('type') typeAttr: string;
  @HostBinding('attr.data-fullwidth') fullWidthAttr: boolean | string;
  @HostBinding('attr.data-size') sizeAttr: string;
  @HostBinding('attr.data-variation') variationAttr: string;
  @HostBinding('class.amplify-button') defaultClass = true;
  @HostBinding('style.font-weight') fontWeightAttr: string;

  ngOnInit() {
    this.typeAttr = this.type;
    this.fullWidthAttr = this.fullWidth;
    this.sizeAttr = this.size;
    this.variationAttr = this.variation;
    this.fontWeightAttr = this.fontWeight;
  }
}
