// examples/vue/src/pages/ui/components/authenticator/sign-up-with-attributes/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import {
  Authenticator,
  AuthenticatorForceNewPasswordFormFields,
  AmplifyTextField,
} from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';
Amplify.configure(aws_exports);
</script>

<template>
  <authenticator initial-state="signUp">
    <template v-slot:force-new-password-form-fields>
      <authenticator-force-new-password-form-fields />
      <amplify-text-field
        label="Zone Info"
        id="12233"
        autocomplete="false"
        placeholder="Zone Info"
        name="zoneinfo"
        :hideLabel="false"
      />
    </template>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/svelte/src/routes/ui/components/authenticator/sign-up-with-attributes/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import {
    Authenticator,
    ForceNewPasswordFormFields,
    TextField,
  } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
</script>

{#snippet forceNewPasswordFormFields()}
  <ForceNewPasswordFormFields />
  <TextField
    label="Zone Info"
    id="12233"
    autocomplete="false"
    placeholder="Zone Info"
    name="zoneinfo"
    hideLabel={false}
  />
{/snippet}
<Authenticator
  initialState="signUp"
  components={{
    ForceNewPassword: {
      FormFields: forceNewPasswordFormFields,
    },
  }}
>
  {#snippet children({ user, signOut })}
    <h1>Hello {user.username}!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>
