// examples/angular/src/pages/ui/components/authenticator/gen2/auth-status/auth-status.component.ts
import { Component } from '@angular/core';
import { AuthenticatorService } from '@aws-amplify/ui-angular';
import { Amplify } from 'aws-amplify';

import { signIn, signOut } from 'aws-amplify/auth';

import amplifyOutputs from './amplify_outputs';

@Component({
  selector: 'auth-status',
  templateUrl: 'auth-status.component.html',
})
export class AuthStatusComponent {
  constructor(public authenticator: AuthenticatorService) {
    Amplify.configure(amplifyOutputs);
  }

  get isAuthenticated(): boolean {
    return this.authenticator.authStatus === 'authenticated';
  }

  signOut() {
    signOut();
  }

  handleSubmit(event: Event) {
    event.preventDefault();

    const formData = new FormData(event.target as HTMLFormElement);
    signIn({
      username: formData.get('email') as string,
      password: formData.get('password') as string,
    });
  }
}

<form (submit)="handleSubmit($event)">
  <div>{{ authenticator.authStatus }}</div>

  <div
    *ngIf="!isAuthenticated"
    [style.display]="'flex'"
    [style.flex-direction]="'column'"
    [style.gap]="'1rem'"
  >
    <label for="email">Email</label>
    <input id="email" name="email" />
    <label for="password">Password</label>
    <input id="password" name="password" type="password" />
    <button type="submit">Sign In</button>
  </div>

  <div *ngIf="isAuthenticated">
    <button type="button" (click)="signOut()">Sign Out</button>
  </div>
</form>

// examples/vue/src/pages/ui/components/authenticator/gen2/auth-status/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import { signIn, signOut } from 'aws-amplify/auth';
import { computed, toRefs } from 'vue';

import { useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';

import amplifyOutputs from './amplify_outputs';

Amplify.configure(amplifyOutputs);

const { authStatus } = toRefs(useAuthenticator());
const isAuthenticated = computed(() => authStatus.value === 'authenticated');

const handleSignOut = () => signOut();

const onSubmit = (event: any) => {
  signIn({
    username: event.target.email.value,
    password: event.target.password.value,
  });
};
</script>

<template>
  <form @submit.prevent="onSubmit">
    <div>{{ authStatus }}</div>

    <div
      v-if="!isAuthenticated"
      :style="{ display: 'flex', 'flex-direction': 'column', gap: '1rem' }"
    >
      <label for="email">Email</label>
      <input id="email" name="email" />
      <label for="password">Password</label>
      <input id="password" name="password" type="password" />
      <button type="submit">Sign In</button>
    </div>

    <div v-if="isAuthenticated">
      <button type="button" @click="handleSignOut">Sign Out</button>
    </div>
  </form>
</template>
