// examples/vue/src/pages/ui/components/authenticator/sign-in-totp-mfa/index.vue
<script setup lang="ts">
import Amplify from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

const auth = useAuthenticator();
</script>

<template>
  <authenticator>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <span>{{ auth.user?.email }}</span>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/svelte/src/routes/ui/components/authenticator/sign-in-totp-mfa/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { Authenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
  const formFields = {
    setupTotp: { QR: { totpIssuer: 'My Web App' } },
  };
</script>

<Authenticator formFields={formFields}>
  {#snippet children({user, signOut})}
    <h1>Hello { user.username }!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>
