// examples/vue/src/pages/ui/components/authenticator/useAuthenticator/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import Amplify from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);

const { route, user, signOut } = toRefs(useAuthenticator());
const props = useAuthenticator();
</script>

<template>
  <authenticator> </authenticator>
  <template v-if="route === 'authenticated'">
    <h1>Hello {{ user?.username }}!</h1>
    <button @click="signOut">Sign out</button>
  </template>
</template>

// examples/angular/src/pages/ui/components/authenticator/useAuthenticator/useAuthenticator.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';
import { AuthenticatorService } from '@aws-amplify/ui-angular';

import awsExports from './aws-exports';

@Component({
  selector: 'use-authenticator',
  templateUrl: 'useAuthenticator.component.html',
})
export class UseAuthenticatorComponent {
  constructor(public authenticator: AuthenticatorService) {
    Amplify.configure(awsExports);
  }
}

<ng-container *ngIf="authenticator.route === 'authenticated'">
  <h2>Welcome, {{ authenticator.user.username }}!</h2>
  <button (click)="authenticator.signOut()">Sign Out</button>
</ng-container>

<ng-container *ngIf="authenticator.route !== 'authenticated'">
  <amplify-authenticator></amplify-authenticator>
</ng-container>
