// examples/vue-gen2/src/pages/ui/components/authenticator/override-function-calls/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';
import { signUp, SignUpInput } from 'aws-amplify/auth';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from './amplify_outputs';

Amplify.configure(amplifyOutputs);

const services = {
  async handleSignUp(input: SignUpInput) {
    // custom username and email
    const { username, options } = input;
    const customUsername = username.toLowerCase();
    const customEmail = options?.userAttributes?.email?.toLowerCase();
    return signUp({
      ...input,
      username: customUsername,
      options: {
        ...options,
        userAttributes: {
          ...options?.userAttributes,
          email: customEmail,
        },
      },
    });
  },
};
</script>

<template>
  <authenticator :services="services" initial-state="signUp">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/gen2/override-function-calls/override-function-calls.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';
import { signUp, SignUpInput } from 'aws-amplify/auth';
import amplifyOutputs from './amplify_outputs';

@Component({
  selector: 'override-function-calls',
  templateUrl: 'override-function-calls.component.html',
})
export class OverrideFunctionCallsComponent {
  constructor() {
    Amplify.configure(amplifyOutputs);
  }
  services = {
    async handleSignUp(input: SignUpInput) {
      let { username, password, options } = input;
      // custom username and email
      username = username.toLowerCase();
      const customEmail = options?.userAttributes?.email?.toLowerCase();
      return signUp({
        username,
        password,
        options: {
          ...options,
          userAttributes: {
            ...options?.userAttributes,
            email: customEmail,
          },
        },
      });
    },
  };
}
