// examples/angular/src/pages/ui/components/authenticator/custom-sign-up-fields/custom-sign-up-fields.component.ts
import { Component } from '@angular/core';
import Amplify from 'aws-amplify';
import awsExports from '@environments/auth-with-email/src/aws-exports';

@Component({
  selector: 'custom-sign-up-fields',
  templateUrl: 'custom-sign-up-fields.component.html',
})
export class CustomSignUpFieldsComponent {
  constructor() {
    Amplify.configure(awsExports);
  }

  services = {
    async validateCustomSignUp(formData: Record<string, string>) {
      if (!formData.acknowledgement) {
        return {
          acknowledgement: 'You must agree to the Terms & Conditions',
        };
      }
    },
  };
}

<amplify-authenticator
  [loginMechanisms]="['email']"
  [services]="services"
  initialState="signUp"
>
  <!-- sign-up-field override -->
  <ng-template
    amplifySlot="sign-up-form-fields"
    let-validationErrors="validationErrors"
  >
    <!--  Prepend `preferred_username` custom attribute  -->
    <amplify-text-field
      id="prefered_username"
      label="Preferred Username"
      name="preferred_username"
      placeholder="Preferred Username"
      [required]="true"
    ></amplify-text-field>

    <!-- Re-use default `Authenticator.SignUp.FormFields` -->
    <amplify-sign-up-form-fields></amplify-sign-up-form-fields>

    <!-- Append & require Terms & Conditions field to sign up -->
    <amplify-checkbox
      [errorMessage]="validationErrors.acknowledgement"
      [hasError]="!!validationErrors.acknowledgement"
      name="acknowledgement"
      value="yes"
    >
      I agree with the Terms & Conditions
    </amplify-checkbox>
  </ng-template>

  <!-- signed-in content override -->
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>

// examples/vue/src/pages/ui/components/authenticator/custom-sign-up-fields/index.vue
<script setup lang="ts">
import Amplify from 'aws-amplify';
import { toRefs } from 'vue';
import {
  Authenticator,
  SignUpFormFields,
  // Vue Composable to get access to validation errors
  useAuthenticator,
  // Amplify UI Primitives to simplify the custom fields
  BaseTextField,
  BaseCheckBox,
} from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import awsExports from '@environments/auth-with-email-and-custom-attributes/src/aws-exports';

Amplify.configure(awsExports);

const { validationErrors } = toRefs(useAuthenticator());

const services = {
  async validateCustomSignUp(formData) {
    if (!formData.acknowledgement) {
      return {
        acknowledgement: 'You must agree to the Terms & Conditions',
      };
    }
  },
};
</script>

<template>
  <authenticator
    initial-state="signUp"
    :login-mechanisms="['email']"
    :services="services"
  >
    <template v-slot:sign-up-fields>
      <base-text-field
        id="prefered_username"
        label="Preferred Username"
        name="preferred_username"
        placeholder="Preferred Username"
        type="text"
        :required="false"
      ></base-text-field>
      <sign-up-form-fields />
      <base-check-box :errorMessage="validationErrors.acknowledgement" />
    </template>
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
