// packages/vue/src/components/SignUp.vue
<template>
  <Form @submit.prevent="onSignUpButtonClicked">
    <Heading>
      <template #headingI>
        <slot name="heading"></slot>
      </template>
      Sign Up
    </Heading>
    <FieldSet>
      <Label>
        <Text>Username</Text>
        <Input name="username" required type="text"></Input>
      </Label>
      <Label>
        <Text>Password</Text>
        <Input name="password" required type="password"></Input>
      </Label>
      <Label>
        <Text>Email Address</Text>
        <Input name="email" required type="email"></Input>
      </Label>
      <Label>
        <Text>Phone Number</Text>

        <div class="flex">
          <Select
            v-model:selectValue="phonePreFix"
            name="phone_number"
            :options="options"
            class="border"
          />
          <Input
            v-model:textValue="phoneNumber"
            name="phone_number"
            class="border phone"
            required
            type="tel"
            placeholder="(555) 555-1212"
            maxlength="14"
          ></Input>
        </div>
      </Label>
    </FieldSet>

    <Footer>
      <Text>Have an account?</Text
      ><Button type="button" @click.prevent="onHaveAccountClicked">
        Sign in</Button
      >
      <Spacer />
      <Button>CREATE ACCOUNT</Button>
    </Footer>
  </Form>
</template>

<script lang="ts">
import { defineComponent, inject, Ref, ref, computed } from "vue";

import Form from "./primitives/Form.vue";
import Heading from "./primitives/Heading.vue";
import Text from "./primitives/Text.vue";
import Label from "./primitives/Text.vue";
import Input from "./primitives/Input.vue";
import FieldSet from "./primitives/FieldSet.vue";
import Footer from "./primitives/Footer.vue";
import Spacer from "./primitives/Spacer.vue";
import Button from "./primitives/Button.vue";
import Select from "./primitives/Select.vue";

import { useAuth } from "../composables/useAuth";

export default defineComponent({
  components: {
    Form,
    Heading,
    Text,
    Label,
    Input,
    FieldSet,
    Footer,
    Spacer,
    Button,
    Select
  },
  setup() {
    const { state, send } = useAuth();
    const pageInfo = inject<Ref<string>>("pageInfo");
    const options = [{ value: "+1" }, { value: "+7" }, { value: "+20" }];

    const phonePreFix = ref(options[0].value);
    const phoneNumber = ref("");

    const phone = computed(() => `${phonePreFix.value}${phoneNumber.value}`);

    // Methods
    const onHaveAccountClicked = (): void => {
      pageInfo.value = "SIGNIN";
      send({
        type: "SIGN_IN"
      });
    };

    const onSignUpButtonClicked = (e): void => {
      const phoneS = phone.value.replace(/[^A-Z0-9\+]/gi, "");
      console.log("full", phoneS);

      const formData = new FormData(e.target);

      send({
        type: "SUBMIT",
        //@ts-ignore Property 'fromEntries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2019' or later.ts(2550)
        data: { ...Object.fromEntries(formData), phone_number: phoneS }
      });
    };

    return {
      options,
      onHaveAccountClicked,
      onSignUpButtonClicked,
      state,
      phonePreFix,
      phoneNumber
    };
  }
});
</script>

<style scoped>
.phone {
  margin-top: 0;
  border-radius: 0;
}
</style>

// packages/amplify-ui-react/src/components/Authenticator/SignUp/SignUp.tsx
import { includes } from 'lodash';

import { useAmplify, useAuth } from '../../../hooks';

import {
  authInputAttributes,
  socialProviderLoginMechanisms,
} from '@aws-amplify/ui-core';
import { FederatedSignIn } from '../FederatedSignIn';

export function SignUp() {
  const {
    components: {
      Button,
      Fieldset,
      Footer,
      Form,
      Heading,
      Spacer,
      Text,
      ErrorText,
    },
  } = useAmplify('Authenticator.SignUp');

  const [state, send] = useAuth();
  const isPending = state.matches('signUp.pending');
  const { remoteError } = state.context;

  const [primaryAlias, ...secondaryAliases] = state.context.config
    ?.login_mechanisms ?? ['username', 'email', 'phone_number'];

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    send({
      type: 'CHANGE',
      data: { name, value },
    });
  };

  return (
    <Form
      data-amplify-authenticator-signup=""
      method="post"
      onSubmit={(event) => {
        event.preventDefault();

        const formData = new FormData(event.target);

        send({
          type: 'SUBMIT',
          // @ts-ignore Property 'fromEntries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2019' or later.ts(2550)
          data: Object.fromEntries(formData),
        });
      }}
      onChange={handleChange}
    >
      <Heading>Create a new account</Heading>

      <FederatedSignIn />

      <Fieldset>
        <SignUp.AliasControl
          label={authInputAttributes[primaryAlias].label}
          name={primaryAlias}
        />
        <SignUp.PasswordControl />
        <SignUp.ConfirmPasswordControl />
        {secondaryAliases
          .filter((alias) => !includes(socialProviderLoginMechanisms, alias))
          .map((alias) => (
            <SignUp.AliasControl
              key={alias}
              label={authInputAttributes[alias].label}
              name={alias}
            />
          ))}
      </Fieldset>

      <ErrorText>{remoteError}</ErrorText>

      <Footer>
        <Text>Have an account?</Text>{' '}
        <Button onClick={() => send({ type: 'SIGN_IN' })} type="button">
          Sign in
        </Button>
        <Spacer />
        <Button isDisabled={isPending} type="submit">
          {isPending ? <>Creating Account&hellip;</> : <>Create Account</>}
        </Button>
      </Footer>
    </Form>
  );
}

SignUp.AliasControl = ({
  label = 'Username',
  name = 'username',
  placeholder = label,
}) => {
  const {
    components: { Input, Label, Text, ErrorText },
  } = useAmplify('Authenticator.SignUp.Password');
  const [{ context }] = useAuth();
  const error = context.validationError[name];

  return (
    <>
      <Label>
        <Text>{label}</Text>
        <Input
          name={name}
          placeholder={placeholder}
          required
          type={authInputAttributes[name].type}
        />
      </Label>
      <ErrorText>{error}</ErrorText>
    </>
  );
};

SignUp.PasswordControl = ({
  label = 'Password',
  name = 'password',
  placeholder = label,
}) => {
  const {
    components: { Input, Label, Text, ErrorText },
  } = useAmplify('Authenticator.SignUp.Password');
  const [{ context }] = useAuth();
  const error = context.validationError[name];

  return (
    <>
      <Label>
        <Text>{label}</Text>
        <Input name={name} placeholder={placeholder} required type="password" />
      </Label>
      <ErrorText>{error}</ErrorText>
    </>
  );
};

SignUp.ConfirmPasswordControl = ({
  label = 'Confirm Password',
  name = 'confirm_password',
}) => {
  const {
    components: { Input, Label, Text, ErrorText },
  } = useAmplify('Authenticator.SignUp.Password');
  const [{ context }] = useAuth();
  const error = context.validationError[name];

  return (
    <>
      <Label>
        <Text>{label}</Text>
        <Input name={name} placeholder={label} required type="password" />
      </Label>
      <ErrorText>{error}</ErrorText>
    </>
  );
};
