// examples/vue/src/pages/ui/components/authenticator/auth-with-translations/index.vue
<script setup lang="ts">
import { DefaultTexts } from '@aws-amplify/ui';
import Amplify, { I18n } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from '@environments/auth-with-email/src/aws-exports';

I18n.setLanguage('ja');
I18n.putVocabulariesForLanguage('ja', {
  [DefaultTexts.CONFIRM_PASSWORD_LABEL]: 'パスワードの確認',
  [DefaultTexts.CONFIRM_SMS_LABEL]: 'SMSコードを確認する',
  [DefaultTexts.CONFIRM_TOTP_LABEL]: 'TOTPコードを確認する',
});

Amplify.configure(aws_exports);
</script>

<template>
  <authenticator :login-mechanisms="['email']">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/auth-with-translations/auth-with-translations.component.ts
import { Component, OnInit } from '@angular/core';
import { DefaultTexts } from '@aws-amplify/ui';
import awsExports from '@environments/auth-with-email/src/aws-exports';
import Amplify, { I18n } from 'aws-amplify';
@Component({
  selector: 'auth-with-translations',
  templateUrl: 'auth-with-translations.component.html',
})
export class AuthWithTranslationsComponent implements OnInit {
  constructor() {
    Amplify.configure(awsExports);
  }

  ngOnInit() {
    I18n.setLanguage('ja');

    // Provide missing translations
    I18n.putVocabulariesForLanguage('ja', {
      [DefaultTexts.CONFIRM_PASSWORD_LABEL]: 'パスワードの確認',
      [DefaultTexts.CONFIRM_SMS_LABEL]: 'SMSコードを確認する',
      [DefaultTexts.CONFIRM_TOTP_LABEL]: 'TOTPコードを確認する',
    });

    // Or customers can use helper to get autocompletition
    // import { putTranslationsForLang } from '@aws-amplify/ui'

    // putTranslationsForLang('ja', {
    //   'Confirm Password': 'パスワードの確認',
    //   'Confirm SMS Code': 'SMSコードを確認する',
    //   'Confirm TOTP Code': 'TOTPコードを確認する',
    // });
  }

  ngOnDestroy() {
    I18n.setLanguage('en'); // reset the languages back
  }
}

<amplify-authenticator></amplify-authenticator>
