// packages/svelte/src/lib/components/UserNameAlias.svelte
<script lang="ts">
  import AmplifyFormField from './primitives/AmplifyFormField.svelte';
  import { onMount } from 'svelte';
  import { authState } from '$lib/components/authStore';
  import { getAliasInfoFromContext } from '@aws-amplify/ui';
  export let name: string = 'username';
  export let disabled: boolean = false;
  export let initialValue: string = '';
  export let required: boolean = true;
  let label: string;
  let type: string;
  let error: string;
  let placeholder: string;

  onMount(() => {
    const { label, type } = getAliasInfoFromContext($authState.context);

    placeholder = label;
  });
</script>

<AmplifyFormField
  data-amplify-usernamealias
  {name}
  {label}
  {type}
  {placeholder}
  {initialValue}
  {disabled}
  {required}
  autocomplete="username"
/>

// packages/amplify-ui-react/src/components/Authenticator/shared/UserNameAlias.tsx
import { useAuth } from '../../../hooks';

import { Label, Text, Input, ErrorText } from '../../../primitives';
import { getAliasInfoFromContext } from '@aws-amplify/ui-core';

export interface UserNameAliasProps {
  handleInputChange?(event): void;
  [key: string]: any;
}

export function UserNameAlias(props: UserNameAliasProps) {
  const { handleInputChange, ...attrs } = props;
  const [{ context }] = useAuth();

  const { label, type, error } = getAliasInfoFromContext(context);

  return (
    <Label {...attrs}>
      <Text>{label}</Text>
      <Input
        onChange={handleInputChange}
        name="username"
        required
        type={type}
      />
      <ErrorText>{error}</ErrorText>
    </Label>
  );
}
