// examples/vue/src/pages/ui/components/authenticator/sign-in-federated/index.vue
<template>
  <Authenticator>
    <template v-slot="{ user, send }">
      <h1 class="text-6xl mb-10">Hello {{ user.username }}!</h1>
      <button
        className="px-2 bg-white rounded shadow"
        @click="send('SIGN_OUT')"
      >
        Sign Out
      </button>
    </template>
  </Authenticator>
</template>

<script setup lang="ts">
import aws_exports from '@environments/auth-with-federated/src/aws-exports';

import Amplify from 'aws-amplify';
import '@aws-amplify/ui-vue/styles.css';

import { Authenticator } from '@aws-amplify/ui-vue';

Amplify.configure({
  ...aws_exports,
  auth: {
    login_mechanisms: ['email', 'facebook', 'amazon', 'google'],
  },
});
</script>

// examples/next/pages/ui/components/authenticator/sign-in-federated/index.tsx
import { Authenticator } from '@aws-amplify/ui-react';
import { Amplify } from 'aws-amplify';

import awsExports from 'environments/auth-with-federated/src/aws-exports';

Amplify.configure({
  ...awsExports,
  auth: {
    login_mechanisms: ['email', 'facebook', 'google', 'amazon'],
  },
});

export default function AuthenticatorWithFacebook() {
  return (
    <Authenticator>
      {({ send }) => {
        return (
          <>
            <button onClick={() => send('SIGN_OUT')}>Sign out</button>
          </>
        );
      }}
    </Authenticator>
  );
}
