// packages/angular/projects/ui-angular/src/lib/primitives/amplify-text-field/amplify-text-field.component.ts
import { Component, Input } from '@angular/core';
import { nanoid } from 'nanoid';

@Component({
  selector: 'amplify-text-field',
  templateUrl: './amplify-text-field.component.html',
})
export class AmplifyTextFieldComponent {
  @Input() autocomplete = 'new-password';
  @Input() disabled = false;
  @Input() fieldId: string = `amplify-field-${nanoid(12)}`;
  @Input() initialValue = '';
  @Input() label = '';
  @Input() name: string;
  @Input() placeholder = '';
  @Input() required = true;
  @Input() type: string;
}

<label class="amplify-label" [class.sr-only]="labelHidden" [for]="fieldId">
  {{ label }}
</label>
<input
  class="amplify-input"
  [id]="fieldId"
  [type]="type"
  [name]="name"
  [placeholder]="placeholder"
  [required]="required"
  [value]="initialValue"
  [attr.disabled]="disabled ? '' : null"
  [autocomplete]="autocomplete"
/>

// packages/svelte/src/lib/components/primitives/AmplifyTextField.svelte
<script lang="ts">
	import { nanoid } from 'nanoid';
	export let autocomplete = 'new-password';
	export let disabled = false;
	export let fieldId: string = `amplify-field-${nanoid(12)}`;
	export let initialValue = '';
	export let label = '';
	export let name: string;
	export let placeholder = '';
	export let required = true;
	export let type: string;
	export let labelHidden = false;
</script>

<label class="amplify-label {labelHidden ? 'sr-only' : ''}" for={fieldId}>
	{label}
</label>
<input
	{...$$restProps}
	class={`amplify-input ${$$props.class}`}
	id={fieldId}
	{type}
	{name}
	{placeholder}
	{required}
	value={initialValue}
	disabled={disabled ? true : false}
	{autocomplete}
/>
