// packages/angular/projects/ui-angular/src/lib/primitives/amplify-form-field/amplify-form-field.component.ts
import { Component, Input, OnInit } from '@angular/core';
import {
  ActorContextWithForms,
  AuthInputAttributes,
  getActorContext,
  translate,
  countryDialCodes,
} from '@aws-amplify/ui';
import { getAttributeMap } from '../../common';
import { AuthenticatorService } from '../../services/authenticator.service';

/**
 * Input interface opinionated for authenticator usage.
 *
 * TODO: Separate this component out to two parts -- 1) amplify-auth-input that
 * contains authenticator opinionated logic and 2) amplify-text-field primitive
 * that does not make any auth-related inference.
 */
@Component({
  selector: 'amplify-form-field',
  templateUrl: './amplify-form-field.component.html',
})
export class AmplifyFormFieldComponent implements OnInit {
  @Input() name: string;
  // TODO: Separate entry for id
  @Input() type: string;
  @Input() required = true;
  @Input() placeholder = '';
  @Input() label = '';
  @Input() initialValue = '';
  @Input() disabled = false;
  @Input() autocomplete = '';
  public defaultCountryCode: string;
  public countryDialCodes = countryDialCodes;
  public textFieldId: string;
  public selectFieldId: string;

  constructor(private authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    // TODO: consider better default handling mechanisms across frameworks
    if (this.isPhoneField()) {
      const state = this.authenticator.authState;
      const { country_code }: ActorContextWithForms = getActorContext(state);
      this.defaultCountryCode = country_code;

      // TODO: remove this side-effect
      this.authenticator.updateForm({
        name: 'country_code',
        value: country_code,
      });
    }
  }

  get attributeMap(): AuthInputAttributes {
    return getAttributeMap();
  }

  get error(): string {
    const formContext: ActorContextWithForms = getActorContext(
      this.authenticator.authState
    );
    const { validationError } = formContext;
    return validationError[this.name];
  }

  inferLabel(): string {
    const label = this.label || this.attributeMap[this.name]?.label;
    return translate<string>(label);
  }

  inferPlaceholder(): string {
    const placeholder =
      this.placeholder ||
      this.attributeMap[this.name]?.placeholder ||
      this.inferLabel();
    return translate<string>(placeholder);
  }

  // infers what the `type` of underlying input element should be.
  inferType(): string {
    return this.type ?? this.attributeMap[this.name]?.type ?? 'text';
  }

  // TODO(enhancement): use enum to differentiate special field types
  isPasswordField(): boolean {
    return this.inferType() === 'password';
  }

  isPhoneField(): boolean {
    return this.inferType() === 'tel';
  }
}

<div class="amplify-flex" style="flex-direction: column; gap: 0">
  <!-- Country code field -->
  <amplify-phone-number-field
    *ngIf="isPhoneField()"
    [selectFieldId]="selectFieldId"
    [defaultCountryCode]="defaultCountryCode"
    [textFieldId]="textFieldId"
    [type]="inferType()"
    [name]="name"
    [label]="inferLabel()"
    [placeholder]="inferPlaceholder()"
    [required]="required"
    [initialValue]="initialValue"
    [disabled]="disabled"
    [autocomplete]="autocomplete"
  ></amplify-phone-number-field>

  <amplify-password-field
    *ngIf="isPasswordField()"
    [id]="textFieldId"
    [name]="name"
    [label]="inferLabel()"
    [placeholder]="inferPlaceholder()"
    [required]="required"
    [initialValue]="initialValue"
    [disabled]="disabled"
    [autocomplete]="autocomplete"
  ></amplify-password-field>

  <amplify-text-field
    *ngIf="!isPasswordField() && !isPhoneField()"
    [id]="textFieldId"
    [type]="inferType()"
    [name]="name"
    [label]="inferLabel()"
    [placeholder]="inferPlaceholder()"
    [required]="required"
    [initialValue]="initialValue"
    [disabled]="disabled"
    [autocomplete]="autocomplete"
  ></amplify-text-field>

  <amplify-error *ngIf="error">
    {{ error }}
  </amplify-error>
</div>

// packages/svelte/src/lib/components/primitives/AmplifyFormField.svelte
<script lang="ts">
	import AmplifyPhoneNumberField from './AmplifyPhoneNumberField.svelte';
	import AmplifyPasswordField from './AmplifyPasswordField.svelte';
	import AmplifyTextField from './AmplifyTextField.svelte';
	import AmplifyError from './AmplifyError.svelte';

	import { authState, updateForm, updateBlur } from '$lib/components/store';
	import {
		ActorContextWithForms,
		authInputAttributes,
		AuthInputAttributes,
		getActorContext,
		translate
	} from '@aws-amplify/ui';

	import { onMount } from 'svelte';

	export let name: string;
	export let type: string;
	export let required = true;
	export let placeholder = '';
	export let label = '';
	export let initialValue = '';
	export let disabled = false;
	export let autocomplete = '';
	export let labelHidden = true;

	const getAttributeMap: AttributeInfoProvider = () => authInputAttributes;
	type AttributeInfoProvider = () => AuthInputAttributes;

	let defaultCountryCode: string;
	onMount(() => {
		if (isPhoneField()) {
			const state = $authState;
			const { country_code }: ActorContextWithForms = getActorContext(state);
			defaultCountryCode = country_code;

			// TODO: remove this side-effect
			updateForm()({
				name: 'country_code',
				value: country_code
			});
		}
	});

	// function attributeMap(): AuthInputAttributes {
	// 	return getAttributeMap();
	// }

	const attributeMap = getAttributeMap();

	function error(): string {
		const formContext: ActorContextWithForms = getActorContext($authState);
		const { validationError } = formContext;
		return translate(validationError[name]);
	}

	function onBlur($event: Event) {
		let { name } = <HTMLInputElement>$event.target;

		updateBlur()({ name });
	}

	function inferLabel(): string {
		const myLabel = label || attributeMap[name]?.label;
		return translate<string>(myLabel);
	}

	// function inferPlaceholder(): string {
	let inferPlaceholder;
	$: {
		const myPlaceholder = placeholder || attributeMap[name]?.placeholder || inferLabel();
		inferPlaceholder = translate<string>(myPlaceholder);
	}
	// }

	// infers what the `type` of underlying input element should be.
	function inferType(): string {
		return type ?? attributeMap[name]?.type ?? 'text';
	}

	function inferAutocomplete(): string {
		return autocomplete || attributeMap[name]?.autocomplete;
	}

	// TODO(enhancement): use enum to differentiate special field types
	function isPasswordField(): boolean {
		return inferType() === 'password';
	}

	function isPhoneField(): boolean {
		return inferType() === 'tel';
	}
</script>

<div class="amplify-flex amplify-field" style="flex-direction: column">
	<!-- Country code field -->
	{#if isPhoneField()}
		<AmplifyPhoneNumberField
			{defaultCountryCode}
			type={inferType()}
			{name}
			label={inferLabel()}
			placeholder={inferPlaceholder}
			{required}
			{initialValue}
			{disabled}
			{labelHidden}
			autocomplete={inferAutocomplete()}
		/>
	{/if}

	{#if isPasswordField()}
		<AmplifyPasswordField
			{...$$restProps}
			{name}
			label={inferLabel()}
			placeholder={inferPlaceholder}
			{required}
			{initialValue}
			{disabled}
			{labelHidden}
			autocomplete={inferAutocomplete()}
		/>
	{/if}

	{#if !isPasswordField() && !isPhoneField()}
		<AmplifyTextField
			type={inferType()}
			{name}
			label={inferLabel()}
			placeholder={inferPlaceholder}
			{required}
			{initialValue}
			{disabled}
			{labelHidden}
			autocomplete={inferAutocomplete()}
		/>
	{/if}

	{#if error()}
		<AmplifyError>
			{error()}
		</AmplifyError>
	{/if}
</div>
