// packages/angular/projects/ui-angular/src/lib/primitives-poc/amplify-button/amplify-button-component/amplify-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
  OnInit,
  ViewEncapsulation,
} from '@angular/core';

@Component({
  selector: 'button[amplify-button-poc]',
  templateUrl: './amplify-button.component.html',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AmplifyButtonComponent implements OnInit {
  @Input() type: 'submit' | 'button' = 'button';
  @Input() fullWidth: boolean | string = false;
  @Input() isDisabled: boolean | string = false;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() variation: 'primary' | 'default' | 'link' = 'default';
  @Input() fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

  @HostBinding('type') typeAttr: string;
  @HostBinding('attr.data-fullwidth') fullWidthAttr: boolean | string;
  @HostBinding('attr.data-size') sizeAttr: string;
  @HostBinding('attr.data-variation') variationAttr: string;
  @HostBinding('style.font-weight') fontWeightAttr: string;

  @HostBinding('class') get classNames() {
    let className = 'amplify-button';
    const result = {
      ...(this.variation && {
        data: (className += ` amplify-button--${this.variation}`),
      }),
      ...(this.size && {
        data: (className += ` amplify-button--${this.size}`),
      }),
      ...(this.fullWidth && {
        data: (className += ` amplify-button--fullwidth`),
      }),
      ...(this.isDisabled && {
        data: (className += ` amplify-button--disabled amplify-button--loading`),
      }),
    };
    return result.data;
  }

  // constructor(private shared: AmplifyPrimitiveSharedService) {}

  ngOnInit() {
    this.typeAttr = this.type;
    this.fullWidthAttr = this.fullWidth;
    this.sizeAttr = this.size;
    this.variationAttr = this.variation;
    this.fontWeightAttr = this.fontWeight;
  }
}

// packages/svelte/src/lib/components/primitives/AmplifyButton.svelte
<script lang="ts">
	export let type: 'submit' | 'button' = 'button';
	export let fullWidth: boolean | string = false;
	export let size: 'small' | 'medium' | 'large' = 'medium';
	export let variation: 'primary' | 'default' | 'link' = 'default';
	export let fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();
</script>

<button
	{...$$restProps}
	on:click={() => dispatch('click')}
	class={`amplify-button ${$$props.class}`}
	{type}
	style="font-weight: {fontWeight} "
	data-fullwidth={fullWidth}
	data-size={size}
	data-fontWeight={fontWeight}
	data-variation={variation}
	data-amplify-button=""
>
	<slot />
</button>
