// packages/vue/src/components/primitives/amplify-button.vue
<script setup lang="ts">
interface PropsInterface {
  type?: 'submit' | 'button';
  fullWidth?: boolean | string;
  size?: 'small' | 'medium' | 'large';
  variation?: 'primary' | 'default' | 'link';
  fontWeight?: 'normal' | 'bold' | 'lighter';
}
const { type, fullWidth, size, variation, fontWeight } = withDefaults(
  defineProps<PropsInterface>(),
  {}
);
</script>
<template>
  <slot v-bind="$attrs" name="buttont">
    <button
      :type="type"
      :style="{ fontWeight: fontWeight }"
      :data-fullwidth="fullWidth"
      :data-size="size"
      :data-fontWeight="fontWeight"
      :data-variation="variation"
      v-bind="$attrs"
      data-amplify-button=""
    >
      <slot></slot>
    </button>
  </slot>
</template>

// packages/svelte/src/lib/components/primitives/AmplifyButton.svelte
<script lang="ts">
	export let type: 'submit' | 'button' = 'button';
	export let fullWidth: boolean | string = false;
	export let size: 'small' | 'medium' | 'large' = 'medium';
	export let variation: 'primary' | 'default' | 'link' = 'default';
	export let fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();
</script>

<button
	{...$$restProps}
	on:click={() => dispatch('click')}
	class={`amplify-button ${$$props.class}`}
	{type}
	style="font-weight: {fontWeight} "
	data-fullwidth={fullWidth}
	data-size={size}
	data-fontWeight={fontWeight}
	data-variation={variation}
	data-amplify-button=""
>
	<slot />
</button>
