// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/form-field/form-field.component.ts
import { Component, Input } from '@angular/core';
import {
  translate,
  countryDialCodes,
  FormFieldOptions,
  getErrors,
} from '@aws-amplify/ui';
import { nanoid } from 'nanoid';
import { AuthenticatorService } from '../../../../services/authenticator.service';

@Component({
  selector: 'amplify-form-field',
  templateUrl: './form-field.component.html',
})
export class FormFieldComponent {
  @Input() name: string; // name of the input field
  @Input() formField: FormFieldOptions; // form field options for this field

  public defaultCountryCodeValue: string;
  public countryDialCodesValue = countryDialCodes;
  public errorId = nanoid(12);

  constructor(private authenticator: AuthenticatorService) {}

  get errors(): string[] {
    const { validationErrors } = this.authenticator;
    return getErrors(validationErrors[this.name]);
  }

  public onBlur($event: Event) {
    let { name } = <HTMLInputElement>$event.target;

    this.authenticator.updateBlur({ name });
  }

  isPasswordField(): boolean {
    return this.formField.type === 'password';
  }

  isPhoneField(): boolean {
    return this.formField.type === 'tel';
  }

  hasError(): boolean {
    return this.errors?.length > 0;
  }

  get ariaDescribedBy() {
    return this.hasError() ? this.errorId : undefined;
  }

  translate(phrase: string): string {
    return translate<string>(phrase);
  }
}

<div class="amplify-flex amplify-field amplify-authenticator__column">
  <!-- Country code field -->
  <amplify-phone-number-field
    *ngIf="isPhoneField()"
    [name]="name"
    [label]="formField.label"
    [defaultCountryCode]="formField.dialCode"
    [dialCodeList]="formField.dialCodeList"
    [placeholder]="formField.placeholder"
    [required]="formField.isRequired"
    [labelHidden]="formField.labelHidden"
    [autocomplete]="formField.autocomplete"
    [hasError]="hasError"
    [describedBy]="ariaDescribedBy"
    type="tel"
  ></amplify-phone-number-field>

  <amplify-password-field
    *ngIf="isPasswordField()"
    [name]="name"
    [label]="formField.label"
    [placeholder]="formField.placeholder"
    [required]="formField.isRequired"
    [labelHidden]="formField.labelHidden"
    [autocomplete]="formField.autocomplete"
    [hasError]="hasError"
    [describedBy]="ariaDescribedBy"
    (setBlur)="onBlur($event)"
  ></amplify-password-field>

  <amplify-text-field
    *ngIf="!isPasswordField() && !isPhoneField()"
    [name]="name"
    [label]="formField.label"
    [placeholder]="formField.placeholder"
    [required]="formField.isRequired"
    [labelHidden]="formField.labelHidden"
    [autocomplete]="formField.autocomplete"
    [type]="formField.type"
    [hasError]="hasError"
    [describedBy]="ariaDescribedBy"
  ></amplify-text-field>

  <div
    data-amplify-sign-up-errors
    *ngIf="hasError()"
    [id]="errorId"
  >
    <div
      class="amplify-text amplify-text--error"
      data-variation="error"
      *ngFor="let error of errors"
    >
      {{ translate(error) }}
    </div>
  </div>
</div>

// packages/svelte/src/lib/components/primitives/FormField.svelte
<script lang="ts">
  import { nanoid } from 'nanoid';
  import { type FullAutoFill } from 'svelte/elements';

  import { type FormFieldOptions, getErrors, translate } from '@aws-amplify/ui';
  import { useAuthenticator } from '../../stores/authenticator.svelte';
  import PasswordField from '../controls/PasswordField.svelte';
  import AliasField from '../controls/AliasField.svelte';

  interface BaseFormField {
    name?: string;
    formField?: FormFieldOptions;
  }

  const { name = '', formField = {} }: BaseFormField = $props();

  const { validationErrors } = $derived(useAuthenticator());

  const { type } = formField;

  const isPasswordField = $derived(type === 'password');

  const errorId = nanoid(12);

  const errors = $derived(getErrors(validationErrors[name]));
  const hasError = $derived(errors?.length > 0);
  const ariaDescribedBy = $derived(hasError ? errorId : undefined);
  const autocomplete = $derived(formField.autocomplete ?? '') as unknown as FullAutoFill;
</script>

{#if isPasswordField}
  <PasswordField
    {name}
    {hasError}
    {autocomplete}
    label={formField.label ?? ''}
    placeholder={formField.placeholder}
    required={formField.isRequired}
    labelHidden={formField.labelHidden}
    describedBy={ariaDescribedBy}
  />
{:else}
  <AliasField
    {name}
    {hasError}
    {autocomplete}
    label={formField.label ?? ''}
    placeholder={formField.placeholder}
    required={formField.isRequired}
    labelHidden={formField.labelHidden}
    dialCode={formField.dialCode}
    dialCodeList={formField.dialCodeList}
    type={formField.type}
    describedBy={ariaDescribedBy}
  />
{/if}

{#if hasError}
  <div id={ariaDescribedBy}>
    {#each errors as error, idx (idx)}
      <p role="alert" data-variation="error" class="amplify-text amplify-text--error">
        {translate(error)}
      </p>
    {/each}
  </div>
{/if}
