// packages/react-storage/src/components/StorageBrowser/subcomponents/SelectItemControl/Input.tsx
import * as React from 'react';
import { InputElementProps } from '@aws-amplify/ui-react/internal';
import { useElement } from '../../context/elements';

export const Input = <T extends InputElementProps>({
  id,
  type = 'text',
  className,
  value,
  ...rest
}: T): JSX.Element => {
  const Input = useElement('Input');
  const [checked, setChecked] = React.useState(false);

  return (
    <Input
      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
        setChecked(e.target.checked)
      }
      value={value}
      checked={checked}
      className={className}
      type={type}
      id={id}
      {...rest}
    />
  );
};

// packages/svelte/src/lib/components/primitives/Input.svelte
<script lang="ts">
	import { type HTMLInputAttributes } from 'svelte/elements';

	interface Props extends HTMLInputAttributes {
		onInput?: (value: string) => void;
	}
	let { onInput, value = $bindable(), ...rest }: Props = $props();

	const handleInput = (e: Event): void => {
		onInput?.((e.target as HTMLInputElement).value);
	};
</script>

<input {...rest} bind:value onchange={(event) => handleInput(event)} data-amplify-input />
