// packages/svelte/src/lib/components/SignUp.svelte
<script lang="ts">
  import {
    updateForm,
    submitForm,
    error,
    isPending,
    hasValidationErrors,
  } from '$lib/components/authStore';
  import AmplifyError from './primitives/AmplifyError.svelte';
  import AmplifyButton from './primitives/AmplifyButton.svelte';
  import AmplifySignUpFormFields from './AmplifySignUpFormFields.svelte';

  import { translate } from '@aws-amplify/ui';

  const createAccountText = translate('Create Account');

  function onInput(event: Event) {
    let { checked, name, type, value } = <HTMLInputElement>event.target;

    if (type === 'checkbox' && !checked) value = undefined;
    updateForm({ name, value });
  }

  function onSubmit(event: Event): void {
    submitForm();
  }
</script>

<!-- <button on:click={toSignIn}>To Sign In</button> -->

<form data-amplify-form on:submit|preventDefault={onSubmit} on:input={onInput}>
  <div class="amplify-flex" style="flex-direction: column">
    <div class="amplify-flex" style="flex-direction: column">
      <AmplifySignUpFormFields />
      {#if $error}
        <AmplifyError>
          {$error}
        </AmplifyError>
      {/if}
    </div>

    <AmplifyButton
      disabled={$isPending || $hasValidationErrors}
      amplify-button
      variation="primary"
      fullWidth="true"
      type="submit"
    >
      {createAccountText}
    </AmplifyButton>
  </div>
</form>

// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-up/sign-up.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { translate } from '@aws-amplify/ui';

@Component({
  selector: 'amplify-sign-up',
  templateUrl: './sign-up.component.html',
})
export class SignUpComponent {
  @HostBinding('attr.data-amplify-authenticator-signup') dataAttr = '';

  // translated texts
  public createAccountText = translate('Create Account');

  constructor(public authenticator: AuthenticatorService) {}

  public get context() {
    return this.authenticator.slotContext;
  }

  onInput(event: Event) {
    let { checked, name, type, value } = <HTMLInputElement>event.target;

    if (type === 'checkbox' && !checked) value = undefined;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm();
  }
}

<amplify-slot name="sign-up-header" [context]="context"></amplify-slot>

<form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
  <amplify-federated-sign-in></amplify-federated-sign-in>
  <div class="amplify-flex" style="flex-direction: column">
    <div class="amplify-flex" style="flex-direction: column">
      <amplify-slot name="sign-up-form-fields" [context]="context">
        <amplify-sign-up-form-fields></amplify-sign-up-form-fields>
      </amplify-slot>

      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </div>

    <amplify-slot name="sign-up-button" [context]="context">
      <button
        [disabled]="
          authenticator.isPending || authenticator.hasValidationErrors
        "
        amplify-button
        variation="primary"
        fullWidth="true"
        type="submit"
      >
        {{ createAccountText }}
      </button>
    </amplify-slot>
  </div>
</form>

<amplify-slot name="sign-up-footer" [context]="context"> </amplify-slot>
