// examples/next/pages/ui/components/authenticator/auth-status/index.tsx
import { Amplify } from 'aws-amplify';
import { signIn, signOut } from 'aws-amplify/auth';

import {
  Authenticator,
  Button,
  Flex,
  Text,
  TextField,
  PasswordField,
  useAuthenticator,
} from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
import React from 'react';
Amplify.configure(awsExports);

function App() {
  const { authStatus } = useAuthenticator();

  const isAuthenticated = authStatus === 'authenticated';

  return (
    <Flex
      as="form"
      direction="column"
      onSubmit={(e: any) => {
        e.preventDefault();

        signIn(Object.fromEntries(new FormData(e.target)) as any);
      }}
    >
      <Text>{authStatus}</Text>
      {isAuthenticated ? null : (
        <>
          <TextField label="Username" id="username" name="username" />
          <PasswordField label="Password" id="password" name="password" />
        </>
      )}
      <Button
        onClick={() => {
          if (isAuthenticated) {
            signOut();
          }
        }}
        type={isAuthenticated ? 'button' : 'submit'}
      >
        {isAuthenticated ? 'Sign Out' : 'Sign In'}
      </Button>
    </Flex>
  );
}

export default function ProviderWrappedApp() {
  return (
    <Authenticator.Provider>
      <App />
    </Authenticator.Provider>
  );
}

// examples/svelte/src/routes/ui/components/authenticator/auth-status/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { signIn } from 'aws-amplify/auth';
  import { useAuthenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);

  const { authenticator } = $derived(useAuthenticator());
  const isAuthenticated = $derived(authenticator.authStatus === 'authenticated');

  const handleSignOut = () => authenticator.signOut();

  const onSubmit = (event: Event) => {
    event.preventDefault();
    signIn(
      Object.fromEntries(new FormData(event.target as HTMLFormElement)) as any
    );
  };
</script>

<form onsubmit={onSubmit}>
  <div>{ authenticator.authStatus }</div>
  {#if !isAuthenticated}
    <div style="display:flex;flex-direction:column;gap:1rem">
      <label for="username">Username</label>
      <input id="username" name="username" />
      <label for="password">Password</label>
      <input id="password" name="password" type="password" />
      <button type="submit">Sign In</button>
    </div>
  {/if}
  {#if isAuthenticated}
    <button type="button" onclick={handleSignOut}>Sign out</button>
  {/if}
</form>
