// examples/svelte/src/routes/ui/components/authenticator/sign-in-with-username/index.svelte
<script lang="ts">
	import { Amplify } from 'aws-amplify';
	import aws_exports from './aws-exports';
	Amplify.configure({ ...aws_exports, ssr: true });
	import { Authenticator, store } from '@aws-amplify/ui-svelte';
	import '@aws-amplify/ui-svelte/styles.css';
	console.log('store', store.signOut);
	const { signOut, user } = store;
</script>

<h1>Welcome to SvelteKit</h1>
<Authenticator>
	<h1>Hello {$user.username}!</h1>
	<button on:click={signOut}>Sign Out</button>
</Authenticator>

// examples/next/pages/ui/components/authenticator/sign-in-with-username/index.tsx
import React from 'react';
import { Amplify } from 'aws-amplify';

import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import awsExports from './aws-exports';
Amplify.configure(awsExports);

export default function App() {
  return (
    <Authenticator>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
    </Authenticator>
  );
}
