// examples/vue/src/pages/ui/components/authenticator/gen2/useAuthenticator/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { Amplify } from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from './amplify_outputs';

Amplify.configure(amplifyOutputs);

const { route } = toRefs(useAuthenticator());
const props = useAuthenticator();
</script>

<template>
  <authenticator>
    <template v-slot>
      <router-link to="useAuthenticator/home">
        <button>Navigate to Home</button>
      </router-link>
    </template>
  </authenticator>
</template>

// examples/angular-gen2/src/pages/ui/components/authenticator/useAuthenticator/useAuthenticator.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';
import { AuthenticatorService } from '@aws-amplify/ui-angular';

import amplifyOutputs from './amplify_outputs';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'use-authenticator',
  templateUrl: 'useAuthenticator.component.html',
})
export class UseAuthenticatorComponent {
  constructor(
    public authenticator: AuthenticatorService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    Amplify.configure(amplifyOutputs);
  }

  public navigateHome(event: Event) {
    event.preventDefault();
    this.router.navigate(['home'], { relativeTo: this.route });
  }
}
