// packages/react/src/components/Authenticator/shared/UserNameAlias.tsx
import {
  ActorContextWithForms,
  getActorContext,
  getAliasInfoFromContext,
  LoginMechanism,
  translate,
} from '@aws-amplify/ui';
import React, { useState } from 'react';

import { useAuthenticator } from '..';
import { PhoneNumberField, TextField } from '../../..';

export interface UserNameAliasProps {
  alias?: LoginMechanism;
  [key: string]: any;
}

export function UserNameAlias(props: UserNameAliasProps) {
  const { alias, ...attrs } = props;
  const { _state, updateForm } = useAuthenticator();

  const { country_code: defaultCountryCode }: ActorContextWithForms =
    getActorContext(_state);
  const { label, type, error } = getAliasInfoFromContext(_state.context, alias);
  const i18nLabel = translate<string>(label);

  const isPhoneAlias = type === 'tel';
  const inputFieldName = alias ?? 'username';
  const countryCodeName = 'country_code';

  const [fullPhoneNumber, setFullPhoneNumber] = useState({
    [countryCodeName]: defaultCountryCode,
  });

  /**
   * When the field being rendered is for a phone number, this handler is used to prevent change event propagation in
   * order to manually update the state machine with a country code + phone number.
   */
  const handlePhoneNumberChange = (
    event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    event.stopPropagation();

    const newState = {
      ...fullPhoneNumber,
      [event.target.name]: event.target.value,
    };

    updateForm({
      name: inputFieldName,
      value: newState[countryCodeName] + newState[inputFieldName],
    });

    setFullPhoneNumber(newState);
  };

  return isPhoneAlias ? (
    <PhoneNumberField
      autoComplete="username"
      countryCodeName={countryCodeName}
      defaultCountryCode={defaultCountryCode}
      errorMessage={error}
      label={i18nLabel}
      labelHidden={true}
      name={inputFieldName}
      onCountryCodeChange={handlePhoneNumberChange}
      onChange={handlePhoneNumberChange}
      placeholder={i18nLabel}
      isRequired
      {...attrs}
    />
  ) : (
    <TextField
      autoComplete="username"
      errorMessage={error}
      label={i18nLabel}
      labelHidden={true}
      name={inputFieldName}
      required
      placeholder={i18nLabel}
      isRequired
      type={type}
      {...attrs}
    />
  );
}

// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/user-name-alias/user-name-alias.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import {
  ActorContextWithForms,
  getActorContext,
  getAliasInfoFromContext,
} from '@aws-amplify/ui';

@Component({
  selector: 'amplify-user-name-alias',
  templateUrl: './user-name-alias.component.html',
})
export class UserNameAliasComponent implements OnInit {
  @Input() name: string = 'username';
  @Input() disabled: boolean = false;
  @Input() initialValue: string = '';
  @Input() required: boolean = true;
  public label: string;
  public type: string;
  public error: string;
  public placeholder: string;
  public defaultCountryCode?: string;

  private fullPhoneNumber: {
    country_code: string;
    phone_number?: string;
    username?: string;
  };

  constructor(private authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    const context = this.authenticator.context;
    const { label, type } = getAliasInfoFromContext(context);

    this.label = label;
    this.type = type;
    this.placeholder = label;

    if (this.isPhoneField()) {
      const state = this.authenticator.authState;
      const { country_code }: ActorContextWithForms = getActorContext(state);
      this.defaultCountryCode = country_code;
      this.fullPhoneNumber = { country_code };
    }
  }

  isPhoneField(): boolean {
    return this.type === 'tel';
  }

  /**
   * When the field being rendered is for a phone number, this handler is used to prevent change event propagation in
   * order to manually update the state machine with a country code + phone number.
   */
  handlePhoneNumberChange(event: InputEvent) {
    event.stopPropagation();

    const { name, value } = <HTMLInputElement>event.target;
    this.fullPhoneNumber[name] = value;

    this.authenticator.updateForm({
      name: this.name,
      value: this.fullPhoneNumber.country_code + this.fullPhoneNumber[name],
    });
  }
}

<amplify-form-field
  data-amplify-usernamealias
  [name]="name"
  [label]="label"
  [type]="type"
  [placeholder]="placeholder"
  [initialValue]="initialValue"
  [disabled]="disabled"
  [required]="required"
  [defaultCountryCode]="isPhoneField() ? defaultCountryCode : null"
  autocomplete="username"
  (input)="isPhoneField() ? handlePhoneNumberChange($event) : null"
>
</amplify-form-field>
