// examples/svelte/src/routes/ui/components/authenticator/sign-in-with-email/+page.svelte
<script lang="ts">
  import '@aws-amplify/ui-svelte/styles.css';
  import { Amplify } from 'aws-amplify';
  import { Authenticator, Heading, Text } from '@aws-amplify/ui-svelte';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);

  const formFields = {
    signIn: {
      username: {
        placeholder: 'Enter your cool email'
      }
    },
    confirmVerifyUser: {
      confirmation_code: {
        label: 'New Label',
        placeholder: 'Enter your Confirmation Code:',
        isRequired: false
      }
    }
  };

  const components = {
    VerifyUser: {
      Header: verifyUserHeader,
      Footer: verifyUserFooter,
    },
    ConfirmVerifyUser: {
      Header: confirmVerifyUserHeader,
      Footer: confirmVerifyUserFooter,
    },
  };

</script>
{#snippet verifyUserHeader()}
  <Heading level='h3'>
    Enter Information:
  </Heading>
{/snippet}
{#snippet verifyUserFooter()}
  <Text>Footer Information</Text>
{/snippet}
{#snippet confirmVerifyUserHeader()}
  <Heading level='h3'>
    Enter Information:
  </Heading>
{/snippet}
{#snippet confirmVerifyUserFooter()}
  <Text>Footer Information</Text>
{/snippet}

<Authenticator formFields={formFields} components={components} hideSignUp>
  {#snippet children ({ user, signOut })}
    <h1>Hello { user.username }!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>

// examples/next/pages/ui/components/authenticator/sign-in-with-email/index.tsx
import { Amplify } from 'aws-amplify';

import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

import { Heading, Text, useTheme } from '@aws-amplify/ui-react';

import awsExports from './aws-exports';
Amplify.configure(awsExports);

const formFields = {
  signIn: {
    username: {
      placeholder: 'Enter your cool email',
    },
  },
  confirmVerifyUser: {
    confirmation_code: {
      label: 'New Label',
      placeholder: 'Enter your Confirmation Code:',
      isRequired: false,
    },
  },
};

const components = {
  VerifyUser: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    Footer() {
      return <Text>Footer Information</Text>;
    },
  },

  ConfirmVerifyUser: {
    Header() {
      const { tokens } = useTheme();
      return (
        <Heading
          padding={`${tokens.space.xl} 0 0 ${tokens.space.xl}`}
          level={3}
        >
          Enter Information:
        </Heading>
      );
    },
    Footer() {
      return <Text>Footer Information</Text>;
    },
  },
};

export default function App() {
  return (
    <Authenticator
      formFields={formFields}
      components={components}
      hideSignUp={true}
    >
      {({ signOut, user }) => {
        return (
          <main>
            <h1>Hello {user.username}</h1>
            <button onClick={signOut}>Sign out</button>
          </main>
        );
      }}
    </Authenticator>
  );
}
