// packages/react/src/components/Authenticator/ForceNewPassword/ForceNewPassword.tsx
import { getActorContext, SignInContext, translate } from '@aws-amplify/ui';

import { useAuthenticator } from '..';
import { Button, Flex, Heading, PasswordField, Text } from '../../..';
import { isInputOrSelectElement, isInputElement } from '../../../helpers/utils';

export const ForceNewPassword = (): JSX.Element => {
  const { _state, error, isPending, toSignIn, submitForm, updateForm } =
    useAuthenticator();
  const { validationError } = getActorContext(_state) as SignInContext;

  const handleChange = (event: React.FormEvent<HTMLFormElement>) => {
    if (isInputOrSelectElement(event.target)) {
      let { name, type, value } = event.target;
      if (
        isInputElement(event.target) &&
        type === 'checkbox' &&
        !event.target.checked
      ) {
        value = undefined;
      }

      updateForm({ name, value });
    }
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    submitForm();
  };

  return (
    <form
      data-amplify-form=""
      data-amplify-authenticator-forcenewpassword=""
      method="post"
      onChange={handleChange}
      onSubmit={handleSubmit}
    >
      <Flex direction="column">
        <Heading level={3}>{translate('Change Password')}</Heading>

        <Flex direction="column">
          <PasswordField
            data-amplify-password
            placeholder={translate('Password')}
            required
            name="password"
            label={translate('Password')}
            labelHidden={true}
            hasError={!!validationError['confirm_password']}
          />
          <PasswordField
            data-amplify-confirmpassword
            placeholder={translate('Confirm Password')}
            required
            name="confirm_password"
            label={translate('Confirm Password')}
            labelHidden={true}
            hasError={!!validationError['confirm_password']}
          />

          {!!validationError['confirm_password'] && (
            <Text role="alert" variation="error">
              {validationError['confirm_password']}
            </Text>
          )}
        </Flex>

        {error && (
          <Text className="forceNewPasswordErrorText" variation="error">
            {error}
          </Text>
        )}

        <Button
          isDisabled={isPending}
          type="submit"
          variation="primary"
          isLoading={isPending}
          loadingText={translate('Changing')}
          fontWeight="normal"
        >
          {translate('Change Password')}
        </Button>
        <Button
          onClick={toSignIn}
          type="button"
          fontWeight="normal"
          variation="link"
          size="small"
        >
          {translate('Back to Sign In')}
        </Button>
      </Flex>
    </form>
  );
};

// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/force-new-password/force-new-password.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { getFormDataFromEvent, translate } from '@aws-amplify/ui';

@Component({
  selector: 'amplify-force-new-password',
  templateUrl: './force-new-password.component.html',
})
export class ForceNewPasswordComponent {
  @HostBinding('attr.data-amplify-authenticator-forcenewpassword')
  dataAttr = '';
  @Input() public headerText = translate('Change Password');

  // translated texts
  public changePasswordText = translate('Change Password');
  public backToSignInText = translate('Back to Sign In');

  constructor(public authenticator: AuthenticatorService) {}

  public get context() {
    return this.authenticator.slotContext;
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<div data-amplify-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="authenticator.isPending"
    >
      <amplify-slot name="force-new-password-header" [context]="context">
        <h3 class="amplify-heading">{{ this.headerText }}</h3>
      </amplify-slot>
      <amplify-form-field
        [labelHidden]="grabField('password', 'labelHidden', true)"
        [placeholder]="grabField('password', 'placeholder', null)"
        [required]="grabField('password', 'required', true)"
        [label]="grabField('password', 'label', null)"
        name="password"
        type="password"
        autocomplete="new-password"
      ></amplify-form-field>

      <amplify-form-field
        name="confirm_password"
        type="password"
        autocomplete="new-password"
        [labelHidden]="grabField('confirm_password', 'labelHidden', true)"
        [placeholder]="grabField('confirm_password', 'placeholder', null)"
        [required]="grabField('confirm_password', 'required', true)"
        [label]="grabField('confirm_password', 'label', 'Confirm Password')"
      ></amplify-form-field>
      <amplify-slot name="force-new-form-fields" [context]="context">
        <amplify-force-new-password-form-fields></amplify-force-new-password-form-fields>
      </amplify-slot>

      <button amplify-button variation="primary" fullWidth="true" type="submit">
        {{ changePasswordText }}
      </button>

      <button
        amplify-button
        size="small"
        variation="link"
        fontWeight="normal"
        fullWidth="true"
        (click)="authenticator.toSignIn()"
      >
        {{ backToSignInText }}
      </button>
      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </fieldset>
    <amplify-slot name="force-new-password-footer" [context]="context">
    </amplify-slot>
  </form>
</div>
