// packages/angular/projects/ui-angular/src/lib/primitives-poc/button/button-component/button.component.ts
import { Component, HostBinding, Input, OnInit } from '@angular/core';
import { AmplifyBasePrimitiveComponent } from '../../base-primitive/base-primitive.component';

@Component({
  selector: 'button[amplify-button-poc]',
  template: '<ng-content></ng-content>',
})
export class AmplifyButtonComponent
  extends AmplifyBasePrimitiveComponent
  implements OnInit
{
  @Input() type: 'submit' | 'button' = 'button';
  @Input() fullWidth: boolean = false;
  @Input() isDisabled: boolean = false;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Input() variation: 'primary' | 'default' | 'link' = 'default';
  @Input() fontWeight: 'normal' | 'bold' | 'lighter' = 'normal';

  @HostBinding('type') typeAttr: string;
  @HostBinding('attr.data-fullwidth') fullWidthAttr: boolean | string;
  @HostBinding('attr.data-size') sizeAttr: string;
  @HostBinding('attr.data-variation') variationAttr: string;
  @HostBinding('style.font-weight') fontWeightAttr: string;

  @HostBinding('class') get classNamesProp() {
    const classNames = require('classnames');
    return classNames(
      { [`amplify-button amplify-button--${this.variation}`]: this.variation },
      { [`amplify-button amplify-button--${this.size}`]: this.size },
      { [`amplify-button amplify-button--fullwidth`]: this.fullWidth },
      {
        [`amplify-button amplify-button--disabled amplify-button--loading`]:
          this.isDisabled,
      }
    );
  }

  ngOnInit() {
    this.typeAttr = this.type;
    this.fullWidthAttr = this.fullWidth;
    this.sizeAttr = this.size;
    this.variationAttr = this.variation;
    this.fontWeightAttr = this.fontWeight;
  }
}

// packages/svelte/src/lib/components/controls/Button.svelte
<script lang="ts">
	import { type HTMLButtonAttributes } from 'svelte/elements';

	interface PropsInterface extends HTMLButtonAttributes {
		type?: 'submit' | 'button';
		fullWidth?: boolean | string;
		size?: 'small' | 'medium' | 'large';
		variation?: 'primary' | 'default' | 'link';
		fontWeight?: 'normal' | 'bold' | 'lighter';
		loading?: boolean | string;
		disabled?: boolean;
	}

	const {
		type,
		fullWidth,
		size,
		variation,
		fontWeight,
		loading,
		disabled,
		children,
		style,
		...rest
	}: PropsInterface = $props();
</script>

<button
	{...rest}
	class={{
		'amplify-button': true,
		'amplify-field-group__control': true,
		[`amplify-button--${variation}`]: variation,
		[`amplify-button--${size}`]: size,
		'amplify-button--fullwidth': fullWidth,
		'amplify-button--loading': loading,
		'amplify-button--disabled': disabled
	}}
	{type}
	style={`fontWeight: ${fontWeight || 'normal'} ${style}`}
	data-fullwidth={fullWidth}
	data-size={size}
	data-fontWeight={fontWeight}
	data-variation={variation}
	data-loading={loading}
	data-disabled={disabled}
	{disabled}
	data-amplify-button=""
>
	{@render children?.()}
</button>
