// packages/angular/projects/ui-angular/src/lib/primitives/text-field/text-field.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { nanoid } from 'nanoid';

@Component({
  selector: 'amplify-text-field',
  templateUrl: './text-field.component.html',
})
export class TextFieldComponent {
  @Input() autocomplete = 'new-password';
  @Input() disabled = false;
  @Input() fieldId: string = `amplify-field-${nanoid(12)}`;
  @Input() initialValue = '';
  @Input() label = '';
  @Input() name: string;
  @Input() placeholder = '';
  @Input() required = true;
  @Input() type: string;
  @Input() labelHidden = false;

  @HostBinding('style.display') display = 'contents';
}

<label
  class="amplify-label"
  [class.amplify-visually-hidden]="labelHidden"
  [for]="fieldId"
>
  {{ label }}
</label>
<input
  class="amplify-input"
  [id]="fieldId"
  [type]="type"
  [name]="name"
  [placeholder]="placeholder"
  [required]="required"
  [value]="initialValue"
  [autocomplete]="autocomplete"
  [attr.autocapitalize]="autocapitalize"
  [attr.disabled]="disabled ? '' : null"
  [attr.aria-invalid]="hasError ? 'true' : 'false'"
  [attr.aria-describedby]="describedBy"
/>

// packages/svelte/src/lib/components/controls/TextField.svelte
<script lang="ts">
  import { Input, Label, Wrapper } from '../primitives';
  import { type FullAutoFill } from 'svelte/elements';

  interface TextFields {
    label?: string;
    id?: string;
    autocomplete?: FullAutoFill;
    placeholder?: string;
    required?: boolean;
    disabled?: boolean;
    name?: string;
    type?: string;
    hideLabel?: boolean;
  }

  const {
    label = '',
    id = '',
    autocomplete = '',
    placeholder = '',
    required = true,
    disabled = false,
    name = '',
    type = 'text',
    hideLabel = true
  }: TextFields = $props();
</script>

<Label class={['amplify-label', hideLabel && 'amplify-visually-hidden']} for={id}>{label}</Label>
<Wrapper class="amplify-field-group__field-wrapper">
  <Input
    class="amplify-input amplify-field-group__control"
    {id}
    aria-invalid="false"
    {autocomplete}
    {placeholder}
    {required}
    {name}
    {disabled}
    {type}
  />
</Wrapper>
