// examples/next/pages/components/authenticator/sign-up-with-phone/index.tsx
import { Authenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import awsExports from "@environments/auth-with-phone-number/src/aws-exports";

Amplify.configure({
  ...awsExports,
  auth: {
    login_mechanisms: ["phone_number"],
  },
});

export default function AuthenticatorWithPhone() {
  return (
    <>
      <Authenticator>
        {({ send }) => {
          return (
            <>
              <h1>Hello</h1>
              <button onClick={() => send("SIGN_OUT")}>Sign out</button>
            </>
          );
        }}
      </Authenticator>
    </>
  );
}

// examples/vue/src/pages/ui/components/authenticator/sign-up-with-phone/index.vue
<template>
  <Authenticator>
    <template v-slot="{ signOut, user }">
      <h1 class="text-6xl mb-10">Hello {{ user.username }}!</h1>
      <button className="px-2 bg-white rounded shadow" @click="signOut()">
        Sign Out
      </button>
    </template>
  </Authenticator>
</template>

<script setup lang="ts">
import aws_exports from '@environments/auth-with-phone-number/src/aws-exports';

import Amplify from 'aws-amplify';
import '@aws-amplify/ui-vue/styles.css';

import { Authenticator } from '@aws-amplify/ui-vue';

Amplify.configure({
  ...aws_exports,
  auth: {
    login_mechanisms: ['phone_number'],
  },
});
</script>
