// examples/angular/src/pages/ui/components/authenticator/reset-password/reset-password.component.ts
import { Component } from '@angular/core';
import { Amplify } from '@aws-amplify/core';

import awsExports from '@environments/auth-with-username-no-attributes/src/aws-exports';

@Component({
  selector: 'reset-password',
  templateUrl: 'reset-password.component.html',
})
export class ResetPasswordComponent {
  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator initialState="resetPassword">
  <ng-template
    amplifySlot="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
    <h2>Welcome, {{ user.username }}!</h2>
    <button (click)="signOut()">Sign Out</button>
  </ng-template>
</amplify-authenticator>

// examples/vue/src/pages/ui/components/authenticator/reset-password/index.vue
<script setup lang="ts">
import { Amplify } from '@aws-amplify/core';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from '@environments/auth-with-username-no-attributes/src/aws-exports';

Amplify.configure(aws_exports);
</script>

<template>
  <authenticator initial-state="resetPassword">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
