// examples/svelte/src/routes/ui/components/authenticator/sign-in-with-username/+page.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { Authenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';

  Amplify.configure(aws_exports);
  const formFields = {
    signUp: {
      phone_number: {
        dialCode: '+227',
        dialCodeList: ['+1', '+82', '+227', '+100'],
      },
    },
  };
</script>

<Authenticator formFields={formFields} signUpAttributes={['phone_number']} >
  {#snippet children({user, signOut})}
    <h1>Hello { user.username }!</h1>
    <button onclick={signOut}>Sign Out</button>
  {/snippet}
</Authenticator>

// examples/vue/src/pages/ui/components/authenticator/sign-in-with-username/index.vue
<script setup lang="ts">
import Amplify from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
const formFields = {
  signUp: {
    phone_number: {
      dialCode: '+227',
      dialCodeList: ['+1', '+82', '+227', '+100', '+227'],
    },
  },
};
</script>

<template>
  <authenticator
    :form-fields="formFields"
    :sign-up-attributes="['phone_number']"
  >
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>
