// examples/vue-gen2/src/pages/ui/components/authenticator/useAuthenticator/home/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { useRouter } from 'vue-router';

import { Amplify } from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from '../amplify_outputs';

Amplify.configure(amplifyOutputs);

const router = useRouter();
const { user, signOut } = toRefs(useAuthenticator());
const handleClick = (event) => {
  event.preventDefault();
  signOut.value();
  router.push('../useAuthenticator');
};
</script>

<template>
  <!-- TODO: this authenticator shouldn't be needed -->
  <authenticator></authenticator>
  <div>Hello, {{ user?.username }}!</div>
  <button @click="handleClick">Sign Out</button>
</template>

// examples/next/pages/ui/components/authenticator/useAuthenticator/home/index.tsx
import { Amplify } from 'aws-amplify';
import { Authenticator, useAuthenticator } from '@aws-amplify/ui-react';
import * as React from 'react';
import awsExports from '../aws-exports';
import router from 'next/router';

Amplify.configure(awsExports);

function App() {
  const { user, signOut } = useAuthenticator();

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    signOut();
    router.push('../useAuthenticator');
  };

  return (
    <>
      <div>Hello, {user?.username}!</div>
      <button onClick={handleClick}>Sign Out</button>
    </>
  );
}

export default function ProviderWrappedApp() {
  return (
    <Authenticator.Provider>
      <App />
    </Authenticator.Provider>
  );
}
