// examples/vue/src/pages/ui/components/authenticator/useAuthenticator/home/index.vue
<script setup lang="ts">
import { toRefs } from 'vue';
import { useRouter } from 'vue-router';

import { Amplify } from 'aws-amplify';
import { useAuthenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from '../aws-exports';

Amplify.configure(aws_exports);

const router = useRouter();
const { user, signOut } = toRefs(useAuthenticator());
const handleClick = (event: Event) => {
  event.preventDefault();
  signOut();
  router.push('../useAuthenticator');
};
</script>

<template>
  <div>Hello, {{ user?.username }}!</div>
  <button @click="handleClick">Sign Out</button>
</template>

// examples/svelte/src/routes/ui/components/authenticator/useAuthenticator/home/+page.svelte
<script  lang="ts">
  import { goto } from '$app/navigation';

  import { Amplify } from 'aws-amplify';
  import { useAuthenticator } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from '../aws-exports';

  Amplify.configure(aws_exports);

  const { user, signOut } = $derived(useAuthenticator());
  const handleClick = (event) => {
    event.preventDefault();
    // signOut();
    goto('./')
  };
</script>

<div>Hello, { user?.username }!</div>
<button onclick={handleClick}>Sign Out</button>
