// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/authenticator/authenticator.component.ts
import {
  AfterContentInit,
  ChangeDetectorRef,
  Component,
  ContentChildren,
  Input,
  OnDestroy,
  OnInit,
  QueryList,
  TemplateRef,
  ViewEncapsulation,
} from '@angular/core';
import {
  AuthenticatorMachineOptions,
  authenticatorTextUtil,
  setUserAgent,
  SocialProvider,
} from '@aws-amplify/ui';
import { AmplifySlotDirective } from '../../../../utilities/amplify-slot/amplify-slot.directive';
import { CustomComponentsService } from '../../../../services/custom-components.service';
import { AuthenticatorService } from '../../../../services/authenticator.service';

const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

@Component({
  selector: 'amplify-authenticator',
  templateUrl: './authenticator.component.html',
  providers: [CustomComponentsService], // make sure custom components are scoped to this authenticator only
  encapsulation: ViewEncapsulation.None,
})
export class AuthenticatorComponent
  implements OnInit, AfterContentInit, OnDestroy
{
  @Input() formFields: AuthenticatorMachineOptions['formFields'];
  @Input() initialState: AuthenticatorMachineOptions['initialState'];
  @Input() loginMechanisms: AuthenticatorMachineOptions['loginMechanisms'];
  @Input() services: AuthenticatorMachineOptions['services'];
  @Input() signUpAttributes: AuthenticatorMachineOptions['signUpAttributes'];
  @Input() socialProviders: SocialProvider[];
  @Input() variation: 'default' | 'modal';
  @Input() hideSignUp: boolean;

  @ContentChildren(AmplifySlotDirective)
  private customComponentQuery: QueryList<AmplifySlotDirective> = null;

  // translated texts
  public signInTitle = getSignInTabText();
  public signUpTitle = getSignUpTabText();

  private hasInitialized = false;
  private isHandlingHubEvent = false;
  private unsubscribeMachine: () => void;
  private clearUserAgent: () => void;

  constructor(
    private authenticator: AuthenticatorService,
    private contextService: CustomComponentsService,
    private changeDetector: ChangeDetectorRef
  ) {}

  // context passed to "authenticated" slot
  public get context(): AuthenticatorService['slotContext'] {
    return this.authenticator.slotContext;
  }

  public get route(): AuthenticatorService['route'] {
    return this.authenticator.route;
  }

  ngOnInit(): void {
    const {
      initialState,
      loginMechanisms,
      services,
      signUpAttributes,
      socialProviders,
      formFields,
    } = this;

    this.clearUserAgent = setUserAgent({
      componentName: 'Authenticator',
      packageName: 'angular',
      version: VERSION,
    });

    const { initializeMachine } = this.authenticator;

    this.authenticator.hubSubject.subscribe(() => {
      /*
       * Hub events aren't properly caught by Angular, because they are
       * synchronous events. Angular tracks async network events and
       * html events, but not synchronous events like hub.
       *
       * On any notable hub events, we run change detection manually.
       */
      this.changeDetector.detectChanges();

      /*
       * Hub events that we handle can lead to multiple state changes:
       * e.g. `authenticated` -> `signOut` -> initialState.
       *
       * We want to ensure change detection runs all the way, until
       * we reach back to the initial state. Setting the below flag
       * to true to until we reach initial state.
       */
      this.isHandlingHubEvent = true;
    });

    /**
     * Subscribes to state machine changes and sends INIT event
     * once machine reaches 'setup' state.
     */
    this.unsubscribeMachine = this.authenticator.subscribe(() => {
      const { route } = this.authenticator;

      if (this.isHandlingHubEvent) {
        this.changeDetector.detectChanges();

        const initialStateWithDefault = initialState ?? 'signIn';

        // We can stop manual change detection if we're back to the initial state
        if (route === initialStateWithDefault) {
          this.isHandlingHubEvent = false;
        }
      }

      if (!this.hasInitialized && route === 'setup') {
        initializeMachine({
          initialState,
          loginMechanisms,
          services,
          signUpAttributes,
          socialProviders,
          formFields,
        });

        this.hasInitialized = true;
      }
    }).unsubscribe;

    /**
     * handling translations after content init, because authenticator and its
     * translations might be initialized before the main app's `ngOnInit` is run.
     */
    this.signInTitle = getSignInTabText();
    this.signUpTitle = getSignUpTabText();
  }

  /**
   * Lifecycle Methods
   */
  ngAfterContentInit(): void {
    this.contextService.customComponents = this.mapCustomComponents(
      this.customComponentQuery
    );
  }

  ngOnDestroy(): void {
    this.clearUserAgent();
    if (this.unsubscribeMachine) this.unsubscribeMachine();
  }

  /**
   * Class Functions
   */
  public onTabChange(): void {
    const { route } = this.authenticator;
    if (route === 'signIn') {
      this.authenticator.toSignUp();
    } else {
      this.authenticator.toSignIn();
    }
  }

  public hasTabs(): boolean {
    const { route } = this.authenticator;
    return route === 'signIn' || route === 'signUp';
  }

  public hasRouteComponent(): boolean {
    const { route } = this.authenticator;

    switch (route) {
      case 'authenticated':
      case 'idle':
      case 'setup':
      case 'signOut':
      case 'transition':
        return false;
      default:
        return true;
    }
  }

  private mapCustomComponents(
    componentQuery: QueryList<AmplifySlotDirective>
  ): Record<string, TemplateRef<unknown>> {
    if (!componentQuery) return {};
    const customComponents: Record<string, TemplateRef<unknown>> = {};
    componentQuery.forEach((component) => {
      customComponents[component.name] = component.template;
    });

    return customComponents;
  }
}

<div
  data-amplify-authenticator
  [attr.data-variation]="variation"
  *ngIf="route !== 'authenticated'"
>
  <div data-amplify-container>
    <amplify-slot name="header" [context]="context"></amplify-slot>
    <div
      data-amplify-router
      [attr.data-amplify-router-content]="hasTabs() ? undefined : ''"
    >
      <amplify-tabs
        (tabChange)="onTabChange()"
        *ngIf="(route === 'signIn' || route === 'signUp') && !hideSignUp"
      >
        <amplify-tab-item
          [title]="signInTitle"
          [active]="route === 'signIn'"
          data-amplify-router-content
        >
          <!-- signIn component -->
          <amplify-slot
            name="sign-in"
            [context]="context"
            *ngIf="route === 'signIn'"
          >
            <amplify-sign-in></amplify-sign-in>
          </amplify-slot>
        </amplify-tab-item>
        <amplify-tab-item
          [title]="signUpTitle"
          [active]="route === 'signUp'"
          data-amplify-router-content
        >
          <!-- signUp component -->
          <amplify-slot
            name="sign-up"
            [context]="context"
            *ngIf="route === 'signUp'"
          >
            <amplify-sign-up></amplify-sign-up>
          </amplify-slot>
        </amplify-tab-item>
      </amplify-tabs>

      <amplify-slot
        name="sign-in"
        [context]="context"
        *ngIf="route === 'signIn' && hideSignUp"
      >
        <amplify-sign-in></amplify-sign-in>
      </amplify-slot>

      <!-- confirmSignUp content -->
      <amplify-slot
        name="confirm-sign-up"
        [context]="context"
        *ngIf="route === 'confirmSignUp'"
      >
        <amplify-confirm-sign-up></amplify-confirm-sign-up>
      </amplify-slot>

      <!-- confirmSignIn content -->
      <amplify-slot
        name="confirm-sign-in"
        [context]="context"
        *ngIf="route === 'confirmSignIn'"
      >
        <amplify-confirm-sign-in></amplify-confirm-sign-in>
      </amplify-slot>

      <!-- setupTotp content -->
      <amplify-slot
        name="setup-totp"
        [context]="context"
        *ngIf="route === 'setupTOTP'"
      >
        <amplify-setup-totp></amplify-setup-totp>
      </amplify-slot>

      <!-- forceNewPassword content -->
      <amplify-slot
        name="force-new-password"
        [context]="context"
        *ngIf="route === 'forceNewPassword'"
      >
        <amplify-force-new-password></amplify-force-new-password>
      </amplify-slot>

      <!-- resetPassword content -->
      <amplify-slot
        name="reset-password"
        [context]="context"
        *ngIf="route === 'resetPassword'"
      >
        <amplify-reset-password></amplify-reset-password>
      </amplify-slot>

      <!-- confirmResetPassword content -->
      <amplify-slot
        name="confirm-reset-password"
        [context]="context"
        *ngIf="route === 'confirmResetPassword'"
      >
        <amplify-confirm-reset-password></amplify-confirm-reset-password>
      </amplify-slot>

      <!-- verifyUser content -->
      <amplify-slot
        name="verify-user"
        [context]="context"
        *ngIf="route === 'verifyUser'"
      >
        <amplify-verify-user></amplify-verify-user>
      </amplify-slot>

      <!-- confirmVerifyUser content -->
      <amplify-slot
        name="confirm-verify-user"
        [context]="context"
        *ngIf="route === 'confirmVerifyUser'"
      >
        <amplify-confirm-verify-user></amplify-confirm-verify-user>
      </amplify-slot>
    </div>

    <amplify-slot name="footer" [context]="context"></amplify-slot>
  </div>
</div>

<!-- signedIn content is rendered outside authenticator so it's not styled by authenticator -->
<amplify-slot
  name="authenticated"
  [context]="context"
  *ngIf="route === 'authenticated'"
>
  <ng-content></ng-content>
</amplify-slot>

// packages/vue/src/components/authenticator.vue
<script setup lang="ts">
import {
  ref,
  toRefs,
  computed,
  onMounted,
  onUnmounted,
  withDefaults,
} from 'vue';

import {
  AuthFormFields,
  AuthenticatorMachineOptions,
  AuthenticatorRoute,
  SocialProvider,
  authenticatorTextUtil,
  setUserAgent,
} from '@aws-amplify/ui';

import { useAuth, useAuthenticator } from '../composables/useAuth';
import { UseAuthenticator } from '../types';
import { VERSION } from '../version';

import SignIn from './sign-in.vue';
import SignUp from './sign-up.vue';
import ConfirmSignUp from './confirm-sign-up.vue';
import ConfirmSignIn from './confirm-sign-in.vue';
import SetupTotp from './setup-totp.vue';
import ForceNewPassword from './force-new-password.vue';
import ResetPassword from './reset-password.vue';
import ConfirmResetPassword from './confirm-reset-password.vue';
import VerifyUser from './verify-user.vue';
import ConfirmVerifyUser from './confirm-verify-user.vue';

interface AuthenticatorProps {
  hideSignUp?: boolean;
  initialState?: AuthenticatorMachineOptions['initialState'];
  loginMechanisms?: AuthenticatorMachineOptions['loginMechanisms'];
  services?: AuthenticatorMachineOptions['services'];
  signUpAttributes?: AuthenticatorMachineOptions['signUpAttributes'];
  variation?: 'default' | 'modal';
  socialProviders?: SocialProvider[];
  formFields?: AuthFormFields;
}

const props = withDefaults(defineProps<AuthenticatorProps>(), {
  variation: 'default',
});

const {
  initialState,
  loginMechanisms,
  variation,
  services,
  signUpAttributes,
  socialProviders,
  hideSignUp,
  formFields,
} = toRefs(props);

let clearUserAgent: () => void;

const hasInitialized = ref(false);

const { service, send, state } = useAuth();

/**
 * Subscribes to state machine changes and sends INIT event
 * once machine reaches 'setup' state.
 */
const unsubscribeMachine = service.subscribe((newState) => {
  if (newState.matches('setup') && !hasInitialized.value) {
    send({
      type: 'INIT',
      data: {
        /**
         * There's a type inference bug with prop refs that incorrectly assume
         * they can be undefined. Adding `!` until this is resolved from Vue's end.
         *
         * https://github.com/vuejs/core/issues/6420
         */
        initialState: initialState!.value,
        loginMechanisms: loginMechanisms!.value,
        socialProviders: socialProviders!.value,
        signUpAttributes: signUpAttributes!.value,
        services: services!.value,
        formFields: formFields!.value,
      },
    });
    hasInitialized.value = true;
  }
}).unsubscribe;

// `facade` is manually typed to `UseAuthenticator` for temporary type safety.
const facade: UseAuthenticator = useAuthenticator();
const { route, signOut, toSignIn, toSignUp, user } = toRefs(facade);

onMounted(() => {
  clearUserAgent = setUserAgent({
    componentName: 'Authenticator',
    packageName: 'vue',
    version: VERSION,
  });
});

onUnmounted(() => {
  clearUserAgent();
  unsubscribeMachine();
});

const signInComponent = ref();
const signUpComponent = ref();
const confirmSignUpComponent = ref();
const confirmSignInComponent = ref();
const confirmSetupTotpComponent = ref();
const forceNewPasswordComponent = ref();
const resetPasswordComponent = ref();
const confirmResetPasswordComponent = ref();
const verifyUserComponent = ref();
const confirmVerifyUserComponent = ref();

// text util
const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

// computed
const signInLabel = computed(() => getSignInTabText());
const createAccountLabel = computed(() => getSignUpTabText());

// methods
const hasTabs = computed(() => {
  return route.value === 'signIn' || route.value === 'signUp';
});

const hasRouteComponent = computed(() => {
  const routesWithComponent: AuthenticatorRoute[] = [
    'confirmResetPassword',
    'confirmSignIn',
    'confirmSignUp',
    'confirmVerifyUser',
    'forceNewPassword',
    'resetPassword',
    'setupTotp',
    'signIn',
    'signUp',
    'verifyUser',
  ];
  return routesWithComponent.includes(route.value);
});
</script>

<template>
  <div
    v-bind="$attrs"
    data-amplify-authenticator
    :data-variation="variation"
    v-if="hasRouteComponent"
  >
    <div data-amplify-container>
      <slot name="header"> </slot>
      <div
        data-amplify-router
        :data-amplify-router-content="hasTabs ? undefined : ''"
      >
        <base-two-tabs v-if="hasTabs && !hideSignUp">
          <base-two-tab-item
            :active="route === 'signIn'"
            id="signIn"
            :label="signInLabel"
            @click="toSignIn"
          />
          <base-two-tab-item
            :active="route === 'signUp'"
            id="signUp"
            :label="createAccountLabel"
            @click="toSignUp"
          />
        </base-two-tabs>
        <div v-if="hasTabs" data-amplify-router-content>
          <sign-in
            id="signIn-panel"
            role="tabpanel"
            class="amplify-tabs__panel amplify-tabs__panel--active"
            aria-labelledby="signIn-tab"
            v-if="route === 'signIn'"
            ref="signInComponent"
          >
            <template #signInSlotI>
              <slot name="sign-in"></slot>
            </template>

            <template
              #form="{ info, onSignInSubmit, onForgotPasswordClicked, onInput }"
            >
              <slot
                name="sign-in-form"
                :info="info"
                :onInput="onInput"
                :onSignInSubmit="onSignInSubmit"
                :onForgotPasswordClicked="onForgotPasswordClicked"
              ></slot>
            </template>

            <template #header>
              <slot name="sign-in-header"></slot>
            </template>

            <template #footer>
              <slot name="sign-in-footer"> </slot>
            </template>
          </sign-in>
          <sign-up
            id="signUp-panel"
            class="amplify-tabs__panel amplify-tabs__panel--active"
            role="tabpanel"
            aria-labelledby="signUp-tab"
            v-if="route === 'signUp' && !hideSignUp"
            ref="signUpComponent"
          >
            <template #signUpSlotI>
              <slot name="sign-up"></slot>
            </template>
            <template #header>
              <slot name="sign-up-header"></slot>
            </template>
            <template #signup-fields="{ info }">
              <slot name="sign-up-fields" :info="info"></slot>
            </template>

            <template #footer>
              <slot name="sign-up-footer"> </slot>
            </template>
          </sign-up>
        </div>

        <confirm-sign-up
          v-if="route === 'confirmSignUp'"
          ref="confirmSignUpComponent"
        >
          <template #confirmSignUpSlotI>
            <slot name="confirm-sign-up"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-up-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-sign-up-footer"> </slot>
          </template>
        </confirm-sign-up>

        <reset-password
          v-if="route === 'resetPassword'"
          ref="resetPasswordComponent"
        >
          <template #resetPasswordSlotI>
            <slot name="reset-password"></slot>
          </template>
          <template #header>
            <slot name="reset-password-header"></slot>
          </template>
          <template #footer>
            <slot name="reset-password-footer"> </slot>
          </template>
        </reset-password>

        <confirm-reset-password
          v-if="route === 'confirmResetPassword'"
          ref="confirmResetPasswordComponent"
        >
          <template #confirmResetPasswordSlotI>
            <slot name="confirm-reset-password"></slot>
          </template>
          <template #header>
            <slot name="confirm-reset-password-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-reset-password-footer"> </slot>
          </template>
        </confirm-reset-password>

        <confirm-sign-in
          v-if="route === 'confirmSignIn'"
          ref="confirmSignInComponent"
        >
          <template #confirmSignInSlotI>
            <slot name="confirm-sign-in"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-in-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-sign-in-footer"> </slot>
          </template>
        </confirm-sign-in>

        <setup-totp
          v-if="route === 'setupTotp'"
          ref="confirmSetupTotpComponent"
        >
          <template #confirmSetupTotpI>
            <slot name="setup-totp"></slot>
          </template>
          <template #header>
            <slot name="setup-totp-header"></slot>
          </template>
          <template #footer>
            <slot name="setup-totp-footer"> </slot>
          </template>
        </setup-totp>

        <force-new-password
          v-if="route === 'forceNewPassword'"
          ref="forceNewPasswordComponent"
        >
          <template #forceNewPasswordI>
            <slot name="force-new-password"></slot>
          </template>
          <template #header>
            <slot name="force-new-password-header"></slot>
          </template>
          <template #force-new-password-form-fields>
            <slot name="force-new-password-form-fields"></slot>
          </template>
          <template #footer>
            <slot name="force-new-password-footer"> </slot>
          </template>
        </force-new-password>

        <verify-user v-if="route === 'verifyUser'" ref="verifyUserComponent">
          <template #verifyUserSlotI>
            <slot name="verify-user"></slot>
          </template>
          <template #header>
            <slot name="verify-user-header"></slot>
          </template>
          <template #footer>
            <slot name="verify-user-footer"> </slot>
          </template>
        </verify-user>

        <confirm-verify-user
          v-if="route === 'confirmVerifyUser'"
          ref="confirmVerifyUserComponent"
        >
          <template #confirmVerifyUserSlotI>
            <slot name="confirm-verify-user"></slot>
          </template>
          <template #header>
            <slot name="confirm-verify-user-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-verify-user-footer"> </slot>
          </template>
        </confirm-verify-user>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
  <!-- cast slot props back to any for backwards compatibility -->
  <slot
    v-if="route === 'authenticated'"
    :user="user as any"
    :state="state as any"
    :signOut="signOut as any"
    :send="send as any"
  ></slot>
</template>
