// packages/svelte/src/lib/components/Authenticator/Authenticator.svelte
<script lang="ts">
  import { onDestroy, onMount, type Snippet } from 'svelte';
  import {
    type AuthenticatorMachineOptions,
    type AuthenticatorRoute,
    authenticatorTextUtil,
    type AuthFormFields,
    type AuthMachineState,
    setUserAgent,
    type SocialProvider
  } from '@aws-amplify/ui';
  import { type AuthUser } from '@aws-amplify/auth';

  import { useAuth, useAuthenticator } from '../../stores/authenticator.svelte';
  import { VERSION } from '../../version';
  import { type Components } from '../../types';
  import TwoTabs from '../primitives/TwoTabs.svelte';
  import TwoTabItem from '../primitives/TwoTabItem.svelte';
  import SignIn from './SignIn.svelte';
  import SignUp from './SignUp.svelte';
  import ConfirmSignUp from './ConfirmSignUp.svelte';
  import ForgotPassword from './ForgotPassword.svelte';
  import ConfirmResetPassword from './ConfirmResetPassword.svelte';
  import ConfirmSignIn from './ConfirmSignIn.svelte';
  import SetupTotp from './SetupTotp.svelte';
  import ForceNewPassword from './ForceNewPassword.svelte';
  import VerifyUser from './VerifyUser.svelte';
  import ConfirmVerifyUser from './ConfirmVerifyUser.svelte';
  import SelectMfaType from './SelectMfaType.svelte';
  import SetupEmail from './SetupEmail.svelte';

  interface ComponentsProvider extends Components {
    ConfirmSignIn?: Components;
    ConfirmSignUp?: Components;
    ConfirmResetPassword?: Components;
    ConfirmVerifyUser?: Components;
    ForceNewPassword?: Components;
    ForgotPassword?: Components;
    SelectMfaType?: Components;
    SetupEmail?: Components;
    SetupTotp?: Components;
    SignIn?: Components;
    SignUp?: Components;
    VerifyUser?: Components;
  }

  interface AuthenticatorProps {
    components?: ComponentsProvider;
    initialState?: AuthenticatorMachineOptions['initialState'];
    loginMechanisms?: AuthenticatorMachineOptions['loginMechanisms'];
    variation?: 'default' | 'modal';
    services?: AuthenticatorMachineOptions['services'];
    signUpAttributes?: AuthenticatorMachineOptions['signUpAttributes'];
    socialProviders?: SocialProvider[];
    hideSignUp?: boolean;
    formFields?: AuthFormFields;
    children?: Snippet<
      [
        {
          user: AuthUser;
          state: AuthMachineState;
          signOut: () => void;
          send: ReturnType<typeof useAuth>['send'];
        }
      ]
    >;
  }

  const {
    components,
    initialState,
    loginMechanisms,
    variation = 'default',
    services,
    signUpAttributes,
    socialProviders,
    hideSignUp,
    formFields,
    children
  }: AuthenticatorProps = $props();

  let clearUserAgent: () => void;

  let hasInitialized = $state(false);

  const {
    send,
    service,
    state: _state,
    route,
    signOut,
    toSignIn,
    toSignUp,
    user
  } = $derived(useAuthenticator());
  /**
   * Subscribes to state machine changes and sends INIT event
   * once machine reaches 'setup' state.
   */
  const unsubscribeMachine = service.subscribe((newState) => {
    if (newState.matches('setup') && !hasInitialized) {
      send({
        type: 'INIT',
        data: {
          initialState,
          loginMechanisms,
          socialProviders,
          signUpAttributes,
          services,
          formFields
        }
      });
      hasInitialized = true;
    }
  }).unsubscribe;

  onMount(() => {
    clearUserAgent = setUserAgent({
      componentName: 'Authenticator',
      packageName: 'svelte',
      version: VERSION
    });
  });

  onDestroy(() => {
    clearUserAgent?.();
    unsubscribeMachine();
  });

  // text util
  const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

  // computed
  const signInLabel = $derived(getSignInTabText());
  const createAccountLabel = $derived(getSignUpTabText());

  // methods
  const hasTabs = $derived(route === 'signIn' || route === 'signUp');

  const hasRouteComponent = $derived(
    (
      [
        'confirmResetPassword',
        'confirmSignIn',
        'confirmSignUp',
        'confirmVerifyUser',
        'forceNewPassword',
        'forgotPassword',
        'selectMfaType',
        'setupEmail',
        'setupTotp',
        'signIn',
        'signUp',
        'verifyUser'
      ] as AuthenticatorRoute[]
    ).includes(route)
  );
</script>

{#if hasRouteComponent}
  <div data-amplify-authenticator data-variation={variation}>
    <div data-amplify-container>
      {@render components?.Header?.()}
      <div data-amplify-router data-amplify-router-content={hasTabs ? undefined : ''}>
        {#if hasTabs && !hideSignUp}
          <TwoTabs>
            <TwoTabItem
              active={route === 'signIn'}
              id="signIn"
              label={signInLabel}
              onclick={toSignIn}
            />
            <TwoTabItem
              active={route === 'signUp'}
              id="signUp"
              label={createAccountLabel}
              onclick={toSignUp}
            />
          </TwoTabs>
        {/if}
        {#if hasTabs}
          <div data-amplify-router-content>
            {#if route === 'signIn'}
              <SignIn
                id="signIn-panel"
                role="tabpanel"
                class="amplify-tabs__panel amplify-tabs__panel--active"
                aria-labelledby="signIn-tab"
                components={components?.SignIn}
              />
            {/if}
            {#if route === 'signUp' && !hideSignUp}
              <SignUp
                id="signUp-panel"
                class="amplify-tabs__panel amplify-tabs__panel--active"
                role="tabpanel"
                aria-labelledby="signUp-tab"
                components={components?.SignUp}
              />
            {/if}
          </div>
        {/if}
        {#if route === 'confirmSignUp'}
          <ConfirmSignUp components={components?.ConfirmSignUp} />
        {:else if route === 'forgotPassword'}
          <ForgotPassword components={components?.ForgotPassword} />
        {:else if route === 'confirmResetPassword'}
          <ConfirmResetPassword components={components?.ConfirmResetPassword} />
        {:else if route === 'confirmSignIn'}
          <ConfirmSignIn components={components?.ConfirmSignIn} />
        {:else if route === 'setupTotp'}
          <SetupTotp components={components?.SetupTotp} />
        {:else if route === 'forceNewPassword'}
          <ForceNewPassword components={components?.ForceNewPassword} />
        {:else if route === 'verifyUser'}
          <VerifyUser components={components?.VerifyUser} />
        {:else if route === 'confirmVerifyUser'}
          <ConfirmVerifyUser components={components?.ConfirmVerifyUser} />
        {:else if route === 'selectMfaType'}
          <SelectMfaType components={components?.SelectMfaType} />
        {:else if route === 'setupEmail'}
          <SetupEmail components={components?.SetupEmail} />
        {/if}
      </div>
      {@render components?.Footer?.()}
    </div>
  </div>
{/if}
{#if route === 'authenticated'}
  {@render children?.({ user, state: _state, signOut, send })}
{/if}

// packages/vue/src/components/authenticator.vue
<script setup lang="ts">
import {
  ref,
  toRefs,
  computed,
  onMounted,
  onUnmounted,
  withDefaults,
} from 'vue';

import {
  AuthFormFields,
  AuthenticatorMachineOptions,
  AuthenticatorRoute,
  SocialProvider,
  authenticatorTextUtil,
  setUserAgent,
} from '@aws-amplify/ui';

import { useAuth, useAuthenticator } from '../composables/useAuth';
import { UseAuthenticator } from '../types';
import { VERSION } from '../version';

import SignIn from './sign-in.vue';
import SignUp from './sign-up.vue';
import ConfirmSignUp from './confirm-sign-up.vue';
import ConfirmSignIn from './confirm-sign-in.vue';
import SetupTotp from './setup-totp.vue';
import ForceNewPassword from './force-new-password.vue';
import ResetPassword from './reset-password.vue';
import ConfirmResetPassword from './confirm-reset-password.vue';
import VerifyUser from './verify-user.vue';
import ConfirmVerifyUser from './confirm-verify-user.vue';

interface AuthenticatorProps {
  hideSignUp?: boolean;
  initialState?: AuthenticatorMachineOptions['initialState'];
  loginMechanisms?: AuthenticatorMachineOptions['loginMechanisms'];
  services?: AuthenticatorMachineOptions['services'];
  signUpAttributes?: AuthenticatorMachineOptions['signUpAttributes'];
  variation?: 'default' | 'modal';
  socialProviders?: SocialProvider[];
  formFields?: AuthFormFields;
}

const props = withDefaults(defineProps<AuthenticatorProps>(), {
  variation: 'default',
});

const {
  initialState,
  loginMechanisms,
  variation,
  services,
  signUpAttributes,
  socialProviders,
  hideSignUp,
  formFields,
} = toRefs(props);

let clearUserAgent: () => void;

const hasInitialized = ref(false);

const { service, send, state } = useAuth();

/**
 * Subscribes to state machine changes and sends INIT event
 * once machine reaches 'setup' state.
 */
const unsubscribeMachine = service.subscribe((newState) => {
  if (newState.matches('setup') && !hasInitialized.value) {
    send({
      type: 'INIT',
      data: {
        /**
         * There's a type inference bug with prop refs that incorrectly assume
         * they can be undefined. Adding `!` until this is resolved from Vue's end.
         *
         * https://github.com/vuejs/core/issues/6420
         */
        initialState: initialState!.value,
        loginMechanisms: loginMechanisms!.value,
        socialProviders: socialProviders!.value,
        signUpAttributes: signUpAttributes!.value,
        services: services!.value,
        formFields: formFields!.value,
      },
    });
    hasInitialized.value = true;
  }
}).unsubscribe;

// `facade` is manually typed to `UseAuthenticator` for temporary type safety.
const facade: UseAuthenticator = useAuthenticator();
const { route, signOut, toSignIn, toSignUp, user } = toRefs(facade);

onMounted(() => {
  clearUserAgent = setUserAgent({
    componentName: 'Authenticator',
    packageName: 'vue',
    version: VERSION,
  });
});

onUnmounted(() => {
  clearUserAgent();
  unsubscribeMachine();
});

const signInComponent = ref();
const signUpComponent = ref();
const confirmSignUpComponent = ref();
const confirmSignInComponent = ref();
const confirmSetupTotpComponent = ref();
const forceNewPasswordComponent = ref();
const resetPasswordComponent = ref();
const confirmResetPasswordComponent = ref();
const verifyUserComponent = ref();
const confirmVerifyUserComponent = ref();

// text util
const { getSignInTabText, getSignUpTabText } = authenticatorTextUtil;

// computed
const signInLabel = computed(() => getSignInTabText());
const createAccountLabel = computed(() => getSignUpTabText());

// methods
const hasTabs = computed(() => {
  return route.value === 'signIn' || route.value === 'signUp';
});

const hasRouteComponent = computed(() => {
  const routesWithComponent: AuthenticatorRoute[] = [
    'confirmResetPassword',
    'confirmSignIn',
    'confirmSignUp',
    'confirmVerifyUser',
    'forceNewPassword',
    'resetPassword',
    'setupTotp',
    'signIn',
    'signUp',
    'verifyUser',
  ];
  return routesWithComponent.includes(route.value);
});
</script>

<template>
  <div
    v-bind="$attrs"
    data-amplify-authenticator
    :data-variation="variation"
    v-if="hasRouteComponent"
  >
    <div data-amplify-container>
      <slot name="header"> </slot>
      <div
        data-amplify-router
        :data-amplify-router-content="hasTabs ? undefined : ''"
      >
        <base-two-tabs v-if="hasTabs && !hideSignUp">
          <base-two-tab-item
            :active="route === 'signIn'"
            id="signIn"
            :label="signInLabel"
            @click="toSignIn"
          />
          <base-two-tab-item
            :active="route === 'signUp'"
            id="signUp"
            :label="createAccountLabel"
            @click="toSignUp"
          />
        </base-two-tabs>
        <div v-if="hasTabs" data-amplify-router-content>
          <sign-in
            id="signIn-panel"
            role="tabpanel"
            class="amplify-tabs__panel amplify-tabs__panel--active"
            aria-labelledby="signIn-tab"
            v-if="route === 'signIn'"
            ref="signInComponent"
          >
            <template #signInSlotI>
              <slot name="sign-in"></slot>
            </template>

            <template
              #form="{ info, onSignInSubmit, onForgotPasswordClicked, onInput }"
            >
              <slot
                name="sign-in-form"
                :info="info"
                :onInput="onInput"
                :onSignInSubmit="onSignInSubmit"
                :onForgotPasswordClicked="onForgotPasswordClicked"
              ></slot>
            </template>

            <template #header>
              <slot name="sign-in-header"></slot>
            </template>

            <template #footer>
              <slot name="sign-in-footer"> </slot>
            </template>
          </sign-in>
          <sign-up
            id="signUp-panel"
            class="amplify-tabs__panel amplify-tabs__panel--active"
            role="tabpanel"
            aria-labelledby="signUp-tab"
            v-if="route === 'signUp' && !hideSignUp"
            ref="signUpComponent"
          >
            <template #signUpSlotI>
              <slot name="sign-up"></slot>
            </template>
            <template #header>
              <slot name="sign-up-header"></slot>
            </template>
            <template #signup-fields="{ info }">
              <slot name="sign-up-fields" :info="info"></slot>
            </template>

            <template #footer>
              <slot name="sign-up-footer"> </slot>
            </template>
          </sign-up>
        </div>

        <confirm-sign-up
          v-if="route === 'confirmSignUp'"
          ref="confirmSignUpComponent"
        >
          <template #confirmSignUpSlotI>
            <slot name="confirm-sign-up"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-up-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-sign-up-footer"> </slot>
          </template>
        </confirm-sign-up>

        <reset-password
          v-if="route === 'resetPassword'"
          ref="resetPasswordComponent"
        >
          <template #resetPasswordSlotI>
            <slot name="reset-password"></slot>
          </template>
          <template #header>
            <slot name="reset-password-header"></slot>
          </template>
          <template #footer>
            <slot name="reset-password-footer"> </slot>
          </template>
        </reset-password>

        <confirm-reset-password
          v-if="route === 'confirmResetPassword'"
          ref="confirmResetPasswordComponent"
        >
          <template #confirmResetPasswordSlotI>
            <slot name="confirm-reset-password"></slot>
          </template>
          <template #header>
            <slot name="confirm-reset-password-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-reset-password-footer"> </slot>
          </template>
        </confirm-reset-password>

        <confirm-sign-in
          v-if="route === 'confirmSignIn'"
          ref="confirmSignInComponent"
        >
          <template #confirmSignInSlotI>
            <slot name="confirm-sign-in"></slot>
          </template>
          <template #header>
            <slot name="confirm-sign-in-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-sign-in-footer"> </slot>
          </template>
        </confirm-sign-in>

        <setup-totp
          v-if="route === 'setupTotp'"
          ref="confirmSetupTotpComponent"
        >
          <template #confirmSetupTotpI>
            <slot name="setup-totp"></slot>
          </template>
          <template #header>
            <slot name="setup-totp-header"></slot>
          </template>
          <template #footer>
            <slot name="setup-totp-footer"> </slot>
          </template>
        </setup-totp>

        <force-new-password
          v-if="route === 'forceNewPassword'"
          ref="forceNewPasswordComponent"
        >
          <template #forceNewPasswordI>
            <slot name="force-new-password"></slot>
          </template>
          <template #header>
            <slot name="force-new-password-header"></slot>
          </template>
          <template #force-new-password-form-fields>
            <slot name="force-new-password-form-fields"></slot>
          </template>
          <template #footer>
            <slot name="force-new-password-footer"> </slot>
          </template>
        </force-new-password>

        <verify-user v-if="route === 'verifyUser'" ref="verifyUserComponent">
          <template #verifyUserSlotI>
            <slot name="verify-user"></slot>
          </template>
          <template #header>
            <slot name="verify-user-header"></slot>
          </template>
          <template #footer>
            <slot name="verify-user-footer"> </slot>
          </template>
        </verify-user>

        <confirm-verify-user
          v-if="route === 'confirmVerifyUser'"
          ref="confirmVerifyUserComponent"
        >
          <template #confirmVerifyUserSlotI>
            <slot name="confirm-verify-user"></slot>
          </template>
          <template #header>
            <slot name="confirm-verify-user-header"></slot>
          </template>
          <template #footer>
            <slot name="confirm-verify-user-footer"> </slot>
          </template>
        </confirm-verify-user>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
  <!-- cast slot props back to any for backwards compatibility -->
  <slot
    v-if="route === 'authenticated'"
    :user="user as any"
    :state="state as any"
    :signOut="signOut as any"
    :send="send as any"
  ></slot>
</template>
