// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.ts
import { Component, HostBinding, OnInit } from '@angular/core';
import { Logger } from 'aws-amplify';
import {
  AuthChallengeNames,
  FormFields,
  getActorContext,
  getActorState,
  getFormDataFromEvent,
  SignInContext,
} from '@aws-amplify/ui';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { translate } from '@aws-amplify/ui';

const logger = new Logger('ConfirmSignIn');

@Component({
  selector: 'amplify-confirm-sign-in',
  templateUrl: './confirm-sign-in.component.html',
})
export class ConfirmSignInComponent implements OnInit {
  @HostBinding('attr.data-amplify-authenticator-confirmsignin') dataAttr = '';

  // translated texts
  public headerText: string;
  public confirmText = translate('Confirm');
  public backToSignInText = translate('Back to Sign In');
  public formOverrides: FormFields;

  constructor(public authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    this.setHeaderText();
    this.setFormFields();
  }

  public setFormFields() {
    const _state = this.authenticator.authState;
    this.formOverrides =
      getActorState(_state).context?.formFields?.confirmSignIn;
  }

  public grabField(name: string, field: string, defaultV) {
    return this.formOverrides?.[name]?.[field] ?? defaultV;
  }

  public get context() {
    return this.authenticator.slotContext;
  }

  setHeaderText(): void {
    const state = this.authenticator.authState;
    const actorContext = getActorContext(state) as SignInContext;
    const { challengeName } = actorContext;
    switch (challengeName) {
      case AuthChallengeNames.SOFTWARE_TOKEN_MFA:
        this.headerText = translate('Confirm TOTP Code');
        break;
      case AuthChallengeNames.SMS_MFA:
        this.headerText = translate('Confirm SMS Code');
        break;
      default:
        logger.error('Unexpected challengeName', challengeName);
    }
  }

  onInput(event: Event): void {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<div data-amplify-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="authenticator.isPending"
    >
      <amplify-slot name="confirm-sign-in-header" [context]="context">
        <h3 class="amplify-heading">{{ headerText }}</h3>
      </amplify-slot>
      <amplify-form-field
        name="confirmation_code"
        label="Code *"
        type="text"
        autocomplete="one-time-code"
        [labelHidden]="grabField('confirmation_code', 'labelHidden', true)"
        [placeholder]="grabField('confirmation_code', 'placeholder', null)"
        [required]="grabField('confirmation_code', 'required', true)"
        [label]="grabField('confirmation_code', 'label', 'Code *')"
      ></amplify-form-field>

      <button amplify-button variation="primary" fullWidth="true" type="submit">
        {{ confirmText }}
      </button>
      <button
        amplify-button
        size="small"
        variation="link"
        fontWeight="normal"
        fullWidth="true"
        (click)="authenticator.toSignIn()"
      >
        {{ backToSignInText }}
      </button>
      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </fieldset>
    <amplify-slot
      name="confirm-sign-in-footer"
      [context]="context"
    ></amplify-slot>
  </form>
</div>

// packages/vue/src/components/confirm-sign-in.vue
<script setup lang="ts">
import {
  AuthChallengeNames,
  getActorState,
  getFormDataFromEvent,
  SignInState,
  translate,
} from '@aws-amplify/ui';
import { computed, ComputedRef, useAttrs } from 'vue';
import { createSharedComposable } from '@vueuse/core';

import { useAuth, useAuthenticator } from '../composables/useAuth';

const emit = defineEmits(['confirmSignInSubmit', 'backToSignInClicked']);
const attrs = useAttrs();

const { state, send } = useAuth();

const {
  value: { context },
} = state;

const formOverrides = context?.config?.formFields?.confirmSignIn;

const useAuthShared = createSharedComposable(useAuthenticator);
const props = useAuthShared();

const actorState = computed(() =>
  getActorState(state.value)
) as ComputedRef<SignInState>;
const challengeName = actorState.value.context.challengeName;

let mfaType: string = 'SMS';

if (challengeName === AuthChallengeNames.SOFTWARE_TOKEN_MFA) {
  mfaType = 'TOTP';
}
const confirmSignInHeading = `Confirm ${mfaType} Code`;

// Computed Properties
const backSignInText = computed(() => translate('Back to Sign In'));
const confirmText = computed(() => translate('Confirm'));
const codeText = computed(() => translate('Code'));

const label =
  formOverrides?.['confirmation_code']?.label ?? translate('Code *');
const labelHidden = formOverrides?.['confirmation_code']?.labelHidden;

// Methods
const onInput = (e: Event): void => {
  const { name, value } = <HTMLInputElement>e.target;
  send({
    type: 'CHANGE',
    //@ts-ignore
    data: { name, value },
  });
};

const onConfirmSignInSubmit = (e: Event): void => {
  if (attrs?.onConfirmSignInSubmit) {
    emit('confirmSignInSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  props.submitForm(getFormDataFromEvent(e));
};

const onBackToSignInClicked = (): void => {
  if (attrs?.onBackToSignInClicked) {
    emit('backToSignInClicked');
  } else {
    send({
      type: 'SIGN_IN',
    });
  }
};
</script>

<template>
  <slot v-bind="$attrs" name="confirmSignInSlotI">
    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-confirmsignin
        @input="onInput"
        @submit.prevent="onConfirmSignInSubmit"
      >
        <base-field-set
          class="amplify-flex"
          style="flex-direction: column"
          :disabled="actorState.matches('confirmSignIn.pending')"
        >
          <slot name="header">
            <base-heading :level="3" class="amplify-heading">
              {{ confirmSignInHeading }}
            </base-heading>
          </slot>
          <base-wrapper class="amplify-flex" style="flex-direction: column">
            <base-wrapper
              class="amplify-flex amplify-field amplify-textfield"
              style="flex-direction: column"
            >
              <base-label
                class="amplify-label"
                :class="{ 'amplify-visually-hidden': labelHidden ?? true }"
                for="amplify-field-51ee"
              >
                {{ label }}
              </base-label>
              <base-wrapper class="amplify-flex" style="flex-direction: column">
                <base-input
                  :placeholder="
                    formOverrides?.['confirmation_code']?.placeholder ??
                    codeText
                  "
                  :required="
                    formOverrides?.['confirmation_code']?.required ?? true
                  "
                  class="amplify-input amplify-field-group__control"
                  id="amplify-field-51ee"
                  aria-invalid="false"
                  name="confirmation_code"
                  autocomplete="one-time-code"
                  type="text"
                ></base-input>
              </base-wrapper>
            </base-wrapper>
          </base-wrapper>
          <base-footer class="amplify-flex" style="flex-direction: column">
            <base-alert v-if="actorState?.context?.remoteError">
              {{ translate(actorState?.context?.remoteError) }}
            </base-alert>
            <amplify-button
              class="amplify-field-group__control"
              data-fullwidth="false"
              data-loading="false"
              data-variation="primary"
              style="font-weight: normal"
              :disabled="actorState.matches('confirmSignIn.pending')"
              >{{ confirmText }}</amplify-button
            >
            <amplify-button
              class="amplify-field-group__control"
              data-fullwidth="false"
              data-size="small"
              data-variation="link"
              style="font-weight: normal"
              type="button"
              @click.prevent="onBackToSignInClicked"
            >
              {{ backSignInText }}</amplify-button
            >
            <slot
              name="footer"
              :onBackToSignInClicked="onBackToSignInClicked"
              :onConfirmSignInSubmit="onConfirmSignInSubmit"
            >
            </slot>
          </base-footer>
        </base-field-set>
      </base-form>
    </base-wrapper>
  </slot>
</template>
