// packages/react/src/components/Authenticator/FederatedSignIn/index.tsx
import { get, includes } from 'lodash-es';

import { useAmplify, useAuth } from '../../../hooks';
import { FederatedIdentityProviders } from '@aws-amplify/ui-core';

import { FederatedSignInButton } from './FederatedSignInButton';

export const FederatedSignIn = (): JSX.Element => {
  const [{ context }] = useAuth();
  const loginMechanisms = get(context, 'config.login_mechanisms');

  const amplifyNamespace = 'Authenticator.FederatedSignIn';
  const {
    components: { Flex },
  } = useAmplify(amplifyNamespace);

  const facebookButton = includes(loginMechanisms, 'facebook') ? (
    <FederatedSignInButton
      text="Sign in with Facebook"
      provider={FederatedIdentityProviders.Facebook}
    />
  ) : null;
  const googleButton = includes(loginMechanisms, 'google') ? (
    <FederatedSignInButton
      text="Sign in with Google"
      provider={FederatedIdentityProviders.Google}
    />
  ) : null;
  const amazonButton = includes(loginMechanisms, 'amazon') ? (
    <FederatedSignInButton
      text="Sign in with Amazon"
      provider={FederatedIdentityProviders.Amazon}
    />
  ) : null;

  const shouldShowFederatedSignIn =
    facebookButton || googleButton || amazonButton;

  const component = shouldShowFederatedSignIn ? (
    <Flex direction="column">
      {googleButton}
      {facebookButton}
      {amazonButton}
    </Flex>
  ) : null;

  return component;
};

// packages/vue/src/components/federated-sign-in.vue
<template>
  <base-wrapper
    data-amplify-wrapper
    data-amplify-federated
    v-if="shouldShowFederatedSignIn"
  >
    <federated-sign-in-button
      v-if="includeFacebook"
      text="Sign in with Facebook"
      :provider="fp.Facebook"
    >
    </federated-sign-in-button>
    <federated-sign-in-button
      v-if="includeGoogle"
      text="Sign in with Google"
      :provider="fp.Google"
    >
    </federated-sign-in-button>
    <federated-sign-in-button
      v-if="includeAmazon"
      text="Sign in with Amazon"
      :provider="fp.Amazon"
    >
    </federated-sign-in-button>
  </base-wrapper>
  <base-box data-amplify-strike v-if="shouldShowFederatedSignIn">
    <base-spacer>or</base-spacer>
  </base-box>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { FederatedIdentityProviders } from '@aws-amplify/ui';
import { useAuth } from '../composables/useAuth';
import FederatedSignInButton from './federated-sign-in-button.vue';

const { state } = useAuth();
const {
  value: { context },
} = state;

const loginMechanisms = context?.config?.login_mechanisms;

const includeFacebook = loginMechanisms?.includes('facebook');
const includeGoogle = loginMechanisms?.includes('google');
const includeAmazon = loginMechanisms?.includes('amazon');

const shouldShowFederatedSignIn =
  includeFacebook || includeGoogle || includeAmazon;

// computed properties

const fp = computed(() => FederatedIdentityProviders);
</script>
