// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/federated-sign-in-button/federated-sign-in-button.component.ts
import { Component, Input } from '@angular/core';
import { FederatedIdentityProviders } from '@aws-amplify/ui';
import { AuthenticatorService } from '../../../../services/authenticator.service';

@Component({
  selector: 'amplify-federated-sign-in-button',
  templateUrl: './federated-sign-in-button.component.html',
})
export class AmplifyFederatedSignInButtonComponent {
  @Input() provider: FederatedIdentityProviders;
  @Input() text: string;

  constructor(private authenticator: AuthenticatorService) {}

  onClick = (): void => {
    this.authenticator.send({
      type: 'FEDERATED_SIGN_IN',
      data: { provider: this.provider },
    });
  };
}

<button
  amplify-button
  class="amplify-field-group__control federated-sign-in-button"
  fullWidth="true"
  fontWeight="normal"
  style="display: block"
  (click)="onClick()"
>
  <div
    class="amplify-flex federated-sign-in-button-row"
    style="flex-direction: row; justify-content: center; align-items: center"
  >
    <ng-content></ng-content>
  </div>
</button>

// packages/vue/src/components/federated-sign-in-button.vue
<template>
  <amplify-button
    class="amplify-field-group__control federated-sign-in-button"
    data-fullwidth="false"
    style="font-weight: normal"
    type="button"
    @click="onClick"
  >
    <base-wrapper
      class="amplify-flex federated-sign-in-button-row"
      style="flex-direction: row; justify-content: center; align-items: center"
    >
      <slot></slot>
    </base-wrapper>
  </amplify-button>
</template>

<script setup lang="ts">
// @xstate
import { FederatedIdentityProviders } from '@aws-amplify/ui';
import { useAuth } from '../composables/useAuth';
const { provider } = defineProps({
  provider: String,
});

const { send } = useAuth();

// Methods
const onClick = (e: Event): void => {
  if (provider)
    send({
      type: 'FEDERATED_SIGN_IN',
      data: { provider: provider as FederatedIdentityProviders },
    });
};
</script>
