// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/select-mfa-type/select-mfa-type.component.ts
import { Component, OnInit } from '@angular/core';
import {
  getActorContext,
  getFormDataFromEvent,
  SignInContext,
  authenticatorTextUtil,
  ComponentClassName,
  classNames,
} from '@aws-amplify/ui';

import { AuthenticatorService } from '../../../../services/authenticator.service';

const { getConfirmText, getBackToSignInText, getSelectMfaTypeByChallengeName } =
  authenticatorTextUtil;

@Component({
  selector: 'amplify-select-mfa-type',
  templateUrl: './select-mfa-type.component.html',
})
export class SelectMfaTypeComponent implements OnInit {
  public headerText: string;
  public confirmText = getConfirmText();
  public backToSignInText = getBackToSignInText();

  public classNames = classNames;
  public ComponentClassName = ComponentClassName;

  constructor(public authenticator: AuthenticatorService) {}

  public get context(): AuthenticatorService['slotContext'] {
    return this.authenticator.slotContext;
  }

  ngOnInit(): void {
    this.setHeaderText();
  }

  setHeaderText(): void {
    const state = this.authenticator.authState;
    const actorContext = getActorContext(state) as SignInContext;
    this.headerText = getSelectMfaTypeByChallengeName(
      actorContext.challengeName
    );
  }

  onInput(event: Event): void {
    event.preventDefault();

    const { name, value } = event.target as HTMLInputElement;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<form
    data-amplify-form
    (submit)="onSubmit($event)"
    (input)="onInput($event)"
>
    <fieldset
        [class]="classNames(ComponentClassName.Flex, 'amplify-authenticator__column')"
        data-amplify-fieldset
        [disabled]="authenticator.isPending"
    >
        <amplify-slot
            name="select-mfa-type-header"
            [context]="context"
        >
            <h3 [class]="classNames(ComponentClassName.Heading, 'amplify-heading--3')">{{ headerText }}</h3>
        </amplify-slot>
        <amplify-base-form-fields route="selectMfaType"></amplify-base-form-fields>

        <button
            amplify-button
            variation="primary"
            fullWidth="true"
            type="submit"
            [isDisabled]="authenticator.isPending"
        >
            {{ confirmText }}
        </button>
        <button
            amplify-button
            size="small"
            variation="link"
            fontWeight="normal"
            fullWidth="true"
            (click)="authenticator.toSignIn()"
        >
            {{ backToSignInText }}
        </button>
        <amplify-error *ngIf="authenticator.error">
            {{ authenticator.error }}
        </amplify-error>
    </fieldset>
    <amplify-slot
        name="select-mfa-type-footer"
        [context]="context"
    ></amplify-slot>
</form>

// packages/vue/src/components/select-mfa-type.vue
<script setup lang="ts">
import { computed, toRefs } from 'vue';

import {
    authenticatorTextUtil,
    getFormDataFromEvent,
    translate,
} from '@aws-amplify/ui';

import { useAuthenticator } from '../composables/useAuth';
import { UseAuthenticator } from '../types';
import BaseFormFields from './primitives/base-form-fields.vue';


const facade: UseAuthenticator = useAuthenticator();
const { submitForm, toSignIn, updateForm } = facade;
const { error, isPending, challengeName: challengeNameRef } = toRefs(facade);

const challengeName = computed(() => challengeNameRef.value);

const { getBackToSignInText, getConfirmText, getSelectMfaTypeByChallengeName } =
    authenticatorTextUtil;

const selectMfaTypeHeading = computed(() =>
    getSelectMfaTypeByChallengeName(challengeName.value)
);
const backSignInText = computed(() => getBackToSignInText());
const confirmText = computed(() => getConfirmText());

const onInput = (e: Event) => {
    const { name, value } = e.target as HTMLInputElement;
    updateForm({ name, value });
};

const onSelectMfaTypeSubmit = (e: Event) => {
    submitForm(getFormDataFromEvent(e));
};

const onBackToSignInClicked = () => {
    toSignIn();
};
</script>

<template>
    <slot
        v-bind="$attrs"
        name="selectMfaTypeSlotI"
    >
        <base-wrapper v-bind="$attrs">
            <base-form
                data-amplify-authenticator-selectmfatype
                @input="onInput"
                @submit.prevent="onSelectMfaTypeSubmit"
            >
                <base-field-set
                    class="amplify-flex amplify-authenticator__column"
                    :disabled="isPending"
                >
                    <slot name="header">
                        <base-heading
                            :level="3"
                            class="amplify-heading"
                        >
                            {{ selectMfaTypeHeading }}
                        </base-heading>
                    </slot>
                    <base-wrapper class="amplify-flex amplify-authenticator__column">
                        <base-form-fields route="selectMfaType"></base-form-fields>
                    </base-wrapper>
                    <base-footer class="amplify-flex amplify-authenticator__column">
                        <base-alert v-if="error">
                            {{ translate(error) }}
                        </base-alert>
                        <amplify-button
                            class="amplify-field-group__control amplify-authenticator__font"
                            :fullwidth="false"
                            :loading="false"
                            :variation="'primary'"
                            style="font-weight: normal"
                            :disabled="isPending"
                        >
                            {{ confirmText }}
                        </amplify-button>
                        <amplify-button
                            class="amplify-field-group__control amplify-authenticator__font"
                            :fullwidth="false"
                            :size="'small'"
                            :variation="'link'"
                            style="font-weight: normal"
                            type="button"
                            @click.prevent="onBackToSignInClicked"
                        >
                            {{ backSignInText }}
                        </amplify-button>
                        <slot name="footer"> </slot>
                    </base-footer>
                </base-field-set>
            </base-form>
        </base-wrapper>
    </slot>
</template>
