// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/setup-totp/setup-totp.component.ts
import { Component, HostBinding, OnInit } from '@angular/core';
import QRCode from 'qrcode';
import { Auth, Logger } from 'aws-amplify';
import { getActorContext, SignInContext } from '@aws-amplify/ui';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { translate } from '@aws-amplify/ui';

const logger = new Logger('SetupTotp');

@Component({
  selector: 'amplify-setup-totp',
  templateUrl: './setup-totp.component.html',
})
export class SetupTotpComponent implements OnInit {
  @HostBinding('attr.data-amplify-authenticator-setup-totp') dataAttr = '';
  public headerText = translate('Setup TOTP');
  public qrCodeSource = '';
  public secretKey = '';
  public copyTextLabel = translate('COPY');

  // translated texts
  public backToSignInText = translate('Back to Sign In');
  public confirmText = translate('Confirm');

  constructor(public authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    this.generateQRCode();
  }

  public get context() {
    return this.authenticator.slotContext;
  }

  async generateQRCode() {
    // TODO: This should be handled in core.
    const state = this.authenticator.authState;
    const actorContext = getActorContext(state) as SignInContext;
    const { user } = actorContext;
    try {
      this.secretKey = await Auth.setupTOTP(user);
      const issuer = 'AWSCognito';
      const totpCode = `otpauth://totp/${issuer}:${user.username}?secret=${this.secretKey}&issuer=${issuer}`;

      logger.info('totp code was generated:', totpCode);
      this.qrCodeSource = await QRCode.toDataURL(totpCode);
    } catch (err) {
      logger.error(err);
    }
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm();
  }

  copyText(): void {
    navigator.clipboard.writeText(this.secretKey);
    this.copyTextLabel = translate('COPIED');
  }
}

<div data-amplify-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="authenticator.isPending"
    >
      <amplify-slot name="setup-totp-header" [context]="context">
        <h3 class="amplify-heading">{{ this.headerText }}</h3>
      </amplify-slot>
      <p *ngIf="!qrCodeSource">Loading...</p>
      <img
        *ngIf="qrCodeSource"
        [src]="qrCodeSource"
        alt="qr code"
        data-amplify-qrcode
        width="228"
        height="228"
      />
      <div class="amplify-flex" data-amplify-copy>
        <div>{{ secretKey }}</div>
        <div data-amplify-copy-svg (click)="copyText()">
          <div data-amplify-copy-tooltip>{{ copyTextLabel }}</div>
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M16 1H4C2.9 1 2 1.9 2 3V17H4V3H16V1ZM15 5H8C6.9 5 6.01 5.9 6.01 7L6 21C6 22.1 6.89 23 7.99 23H19C20.1 23 21 22.1 21 21V11L15 5ZM8 21V7H14V12H19V21H8Z"
              fill="black"
            />
          </svg>
        </div>
      </div>

      <amplify-form-field
        name="confirmation_code"
        type="text"
        autocomplete="one-time-code"
        [labelHidden]="grabField('confirmation_code', 'labelHidden', true)"
        [placeholder]="grabField('confirmation_code', 'placeholder', null)"
        [required]="grabField('confirmation_code', 'required', true)"
        [label]="grabField('confirmation_code', 'label', 'Code *')"
      ></amplify-form-field>
      <button amplify-button variation="primary" fullWidth="true" type="submit">
        {{ confirmText }}
      </button>
      <button
        amplify-button
        size="small"
        variation="link"
        fontWeight="normal"
        fullWidth="true"
        (click)="authenticator.toSignIn()"
      >
        {{ backToSignInText }}
      </button>
      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </fieldset>
    <amplify-slot name="setup-totp-footer" [context]="context"> </amplify-slot>
  </form>
</div>

// packages/vue/src/components/setup-totp.vue
<script setup lang="ts">
import { onMounted, reactive, computed, ComputedRef, useAttrs, ref } from 'vue';
import { createSharedComposable } from '@vueuse/core';
import QRCode from 'qrcode';

import { Auth, Logger } from 'aws-amplify';
import {
  getActorState,
  getFormDataFromEvent,
  SignInState,
  translate,
} from '@aws-amplify/ui';

import { useAuth, useAuthenticator } from '../composables/useAuth';

const useAuthShared = createSharedComposable(useAuthenticator);
const props = useAuthShared();

const attrs = useAttrs();
const emit = defineEmits(['confirmSetupTOTPSubmit', 'backToSignInClicked']);

const { state, send } = useAuth();
const actorState = computed(() =>
  getActorState(state.value)
) as ComputedRef<SignInState>;

let qrCode = reactive({
  qrCodeImageSource: '',
  isLoading: true,
});
let secretKey = ref('');
let copyTextLabel = ref(translate('COPY'));

function copyText() {
  navigator.clipboard.writeText(secretKey.value);
  copyTextLabel.value = translate('COPIED');
}

// lifecycle hooks

onMounted(async () => {
  const logger = new Logger('SetupTOTP-logger');
  const { user } = actorState.value.context;
  if (!user) {
    return;
  }
  try {
    secretKey.value = await Auth.setupTOTP(user);
    const issuer = 'AWSCognito';
    const totpCode = `otpauth://totp/${issuer}:${user.username}?secret=${secretKey.value}&issuer=${issuer}`;
    qrCode.qrCodeImageSource = await QRCode.toDataURL(totpCode);
  } catch (error) {
    logger.error(error);
  } finally {
    qrCode.isLoading = false;
  }
});

// Computed Properties
const backSignInText = computed(() => translate('Back to Sign In'));
const confirmText = computed(() => translate('Confirm'));
const codeText = computed(() => translate('Code'));

// Methods
const onInput = (e: Event): void => {
  const { name, value } = <HTMLInputElement>e.target;
  send({
    type: 'CHANGE',
    //@ts-ignore
    data: { name, value },
  });
};

const onSetupTOTPSubmit = (e: Event): void => {
  if (attrs?.onConfirmSetupTOTPSubmit) {
    emit('confirmSetupTOTPSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  e.preventDefault();
  props.submitForm(getFormDataFromEvent(e));
};

const onBackToSignInClicked = (): void => {
  if (attrs?.onBackToSignInClicked) {
    emit('backToSignInClicked');
  } else {
    send({
      type: 'SIGN_IN',
    });
  }
};
</script>

<template>
  <slot v-bind="$attrs" name="confirmSetupTOTPI">
    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-setup-totp
        @input="onInput"
        @submit.prevent="onSetupTOTPSubmit"
      >
        <base-field-set
          class="amplify-flex"
          style="flex-direction: column"
          :disabled="actorState.matches('confirmSignIn.pending')"
        >
          <template v-if="qrCode.isLoading">
            <p>Loading...</p>
          </template>
          <template v-else>
            <base-wrapper class="amplify-flex" style="flex-direction: column">
              <slot name="header">
                <base-heading class="amplify-heading" :level="3">
                  Setup TOTP
                </base-heading>
              </slot>

              <base-wrapper class="amplify-flex" style="flex-direction: column">
                <img
                  class="amplify-image"
                  data-amplify-qrcode
                  :src="qrCode.qrCodeImageSource"
                  alt="qr code"
                  width="228"
                  height="228"
                />
                <base-wrapper class="amplify-flex" data-amplify-copy>
                  <div>{{ secretKey }}</div>
                  <base-wrapper data-amplify-copy-svg @click="copyText">
                    <div data-amplify-copy-tooltip>{{ copyTextLabel }}</div>
                    <svg
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M16 1H4C2.9 1 2 1.9 2 3V17H4V3H16V1ZM15 5H8C6.9 5 6.01 5.9 6.01 7L6 21C6 22.1 6.89 23 7.99 23H19C20.1 23 21 22.1 21 21V11L15 5ZM8 21V7H14V12H19V21H8Z"
                        fill="black"
                      />
                    </svg>
                  </base-wrapper>
                </base-wrapper>
                <base-wrapper
                  class="amplify-flex amplify-field amplify-textfield"
                  style="flex-direction: column"
                >
                  <base-label
                    class="amplify-visually-hidden amplify-label"
                    for="amplify-field-45d1"
                    >Code *</base-label
                  >
                  <base-wrapper class="amplify-flex">
                    <base-input
                      class="amplify-input amplify-field-group__control"
                      id="amplify-field-45d1"
                      aria-invalid="false"
                      name="confirmation_code"
                      :placeholder="codeText"
                      autocomplete="one-time-code"
                      required
                      type="text"
                    ></base-input>
                  </base-wrapper>
                </base-wrapper>
              </base-wrapper>
              <base-footer class="amplify-flex" style="flex-direction: column">
                <base-alert v-if="actorState.context?.remoteError">
                  {{ translate(actorState.context.remoteError) }}
                </base-alert>
                <amplify-button
                  class="amplify-field-group__control"
                  data-fullwidth="false"
                  data-loading="false"
                  data-variation="primary"
                  type="submit"
                  style="font-weight: normal"
                  :disabled="actorState.matches('confirmSignIn.pending')"
                >
                  {{ confirmText }}
                </amplify-button>
                <amplify-button
                  class="amplify-field-group__control"
                  data-fullwidth="false"
                  data-size="small"
                  data-variation="link"
                  style="font-weight: normal"
                  type="button"
                  @click.prevent="onBackToSignInClicked"
                >
                  {{ backSignInText }}</amplify-button
                >
                <slot
                  name="footer"
                  :onBackToSignInClicked="onBackToSignInClicked"
                  :onSetupTOTPSubmit="onSetupTOTPSubmit"
                >
                </slot>
              </base-footer>
            </base-wrapper>
          </template>
        </base-field-set>
      </base-form>
    </base-wrapper>
  </slot>
</template>
