// packages/svelte/src/lib/components/Authenticator/SetupEmail.svelte
<script lang="ts">
	import { authenticatorTextUtil, getFormDataFromEvent, translate } from '@aws-amplify/ui';
	import { useAuthenticator } from '../../stores/authenticator.svelte';
	import { type Components } from '../../types';

	import Wrapper from '../primitives/Wrapper.svelte';
	import Form from '../primitives/Form.svelte';
	import Button from '../controls/Button.svelte';
	import FieldSet from '../primitives/FieldSet.svelte';
	import FormFields from '../primitives/FormFields.svelte';
	import Heading from '../primitives/Heading.svelte';
	import Footer from '../primitives/Footer.svelte';
	import Alert from '../primitives/Alert.svelte';

	interface Props {
		components?: Components;
	}

	const { components }: Props = $props();

	const { error, isPending, submitForm, toSignIn, updateForm } = $derived(useAuthenticator());
	const { getBackToSignInText, getConfirmText, getSetupEmailText } = authenticatorTextUtil;
	const setupEmailHeading = $derived.by(() => getSetupEmailText());
	const backSignInText = $derived.by(() => getBackToSignInText());
	const confirmText = $derived.by(() => getConfirmText());

	const onInput = (e: Event) => {
		const { name, value } = e.target as HTMLInputElement;
		updateForm({ name, value });
	};

	const onSetupEmailSubmit = (e: Event) => {
		e.preventDefault();
		submitForm(getFormDataFromEvent(e));
	};

	const onBackToSignInClicked = (e: Event) => {
		e.preventDefault();
		toSignIn();
	};
</script>

<Wrapper>
	<Form data-amplify-authenticator-setupemail oninput={onInput} onsubmit={onSetupEmailSubmit}>
		<FieldSet class="amplify-flex amplify-authenticator__column" disabled={isPending}>
			{#if components?.Header}
				{@render components?.Header()}
			{:else}
				<Heading level="h3" class="amplify-heading">
					{setupEmailHeading}
				</Heading>
			{/if}
			<Wrapper class="amplify-flex amplify-authenticator__column">
				{#if components?.FormFields}
					{@render components?.FormFields()}
				{:else}
					<FormFields route="setupEmail" />
				{/if}
			</Wrapper>
			<Footer class="amplify-flex amplify-authenticator__column">
				{#if error}
					<Alert>
						{translate(error)}
					</Alert>
				{/if}
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					loading={false}
					variation="primary"
					fontWeight="normal"
					disabled={isPending}
				>
					{confirmText}
				</Button>
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					size="small"
					variation="link"
					fontWeight="normal"
					type="button"
					onclick={onBackToSignInClicked}
				>
					{backSignInText}
				</Button>
				{@render components?.Footer?.()}
			</Footer>
		</FieldSet>
	</Form>
</Wrapper>

// packages/vue/src/components/setup-email.vue
<script setup lang="ts">
import { computed, toRefs } from 'vue';

import {
    authenticatorTextUtil,
    getFormDataFromEvent,
    translate,
} from '@aws-amplify/ui';

import { useAuthenticator } from '../composables/useAuth';
import type { UseAuthenticator } from '../types';
import BaseFormFields from './primitives/base-form-fields.vue';

const facade: UseAuthenticator = useAuthenticator();
const { submitForm, toSignIn, updateForm } = facade;
const { error, isPending, } = toRefs(facade);

const { getBackToSignInText, getConfirmText, getSetupEmailText } =
    authenticatorTextUtil;

const setupEmailHeading = computed(() =>
    getSetupEmailText()
);
const backSignInText = computed(() => getBackToSignInText());
const confirmText = computed(() => getConfirmText());

const onInput = (e: Event) => {
    const { name, value } = e.target as HTMLInputElement;
    updateForm({ name, value });
};

const onSetupEmailSubmit = (e: Event) => {
    submitForm(getFormDataFromEvent(e));
};

const onBackToSignInClicked = () => {
    toSignIn();
};
</script>

<template>
    <slot
        v-bind="$attrs"
        name="setupEmailSlotI"
    >
        <base-wrapper v-bind="$attrs">
            <base-form
                data-amplify-authenticator-setupemail
                @input="onInput"
                @submit.prevent="onSetupEmailSubmit"
            >
                <base-field-set
                    class="amplify-flex amplify-authenticator__column"
                    :disabled="isPending"
                >
                    <slot name="header">
                        <base-heading
                            :level="3"
                            class="amplify-heading"
                        >
                            {{ setupEmailHeading }}
                        </base-heading>
                    </slot>
                    <base-wrapper class="amplify-flex amplify-authenticator__column">
                        <base-form-fields route="setupEmail"></base-form-fields>
                    </base-wrapper>
                    <base-footer class="amplify-flex amplify-authenticator__column">
                        <base-alert v-if="error">
                            {{ translate(error) }}
                        </base-alert>
                        <amplify-button
                            class="amplify-field-group__control amplify-authenticator__font"
                            :fullwidth="false"
                            :loading="false"
                            :variation="'primary'"
                            style="font-weight: normal"
                            :disabled="isPending"
                        >
                            {{ confirmText }}
                        </amplify-button>
                        <amplify-button
                            class="amplify-field-group__control amplify-authenticator__font"
                            :fullwidth="false"
                            :size="'small'"
                            :variation="'link'"
                            style="font-weight: normal"
                            type="button"
                            @click.prevent="onBackToSignInClicked"
                        >
                            {{ backSignInText }}
                        </amplify-button>
                        <slot name="footer"> </slot>
                    </base-footer>
                </base-field-set>
            </base-form>
        </base-wrapper>
    </slot>
</template>
