// packages/svelte/src/lib/components/Authenticator/SignIn.svelte
<script lang="ts">
  import { authenticatorTextUtil, getFormDataFromEvent, translate } from '@aws-amplify/ui';

  import { useAuthenticator } from '../../stores/authenticator.svelte';
  import { type Components } from '../../types';

  import FormFields from '../primitives/FormFields.svelte';
  import FieldSet from '../primitives/FieldSet.svelte';
  import Form from '../primitives/Form.svelte';
  import Alert from '../primitives/Alert.svelte';
  import Footer from '../primitives/Footer.svelte';
  import Wrapper from '../primitives/Wrapper.svelte';
  import Button from '../controls/Button.svelte';
  import FederatedSignIn from '../controls/FederatedSignIn.svelte';
  import { type HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    components?: Components;
  }

  const { components, ...rest }: Props = $props();

  const { authenticator } = $derived(useAuthenticator());

  // Text Util
  const { getForgotPasswordText, getSignInText, getSigningInText } = authenticatorTextUtil;

  // Computed Properties
  const forgotYourPasswordLink = $derived.by(() => getForgotPasswordText());
  const signInButtonText = $derived.by(() => getSignInText());
  const signingInButtonText = $derived.by(() => getSigningInText());

  // Methods
  const onInput = (e: Event): void => {
    const { name, value } = e.target as HTMLInputElement;
    authenticator.updateForm({ name, value });
  };

  const onSignInSubmit = (e: Event): void => {
    e.preventDefault();
    authenticator.submitForm(getFormDataFromEvent(e));
  };

  const onForgotPasswordClicked = (): void => {
    authenticator.toForgotPassword();
  };
</script>

<div {...rest}>
  {@render components?.Header?.()}
  <Wrapper>
    <Form
      data-amplify-authenticator-signin
      oninput={onInput}
      onsubmit={onSignInSubmit}
      method="post"
    >
      <FederatedSignIn />
      <Wrapper class="amplify-flex amplify-authenticator__column">
        <FieldSet
          disabled={authenticator.isPending}
          class="amplify-flex amplify-authenticator__column"
        >
          <legend class="amplify-visually-hidden">Sign in</legend>
          {#if components?.FormFields}
            {@render components?.FormFields()}
          {:else}
            <FormFields route="signIn" />
          {/if}
        </FieldSet>
        {#if authenticator.error}
          <Alert>{translate(authenticator.error)}</Alert>
        {/if}

        <Button
          disabled={authenticator.isPending}
          class="amplify-field-group__control amplify-authenticator__font"
          fullWidth={true}
          loading={false}
          variation="primary"
        >
          {authenticator.isPending ? signingInButtonText : signInButtonText}
        </Button>
      </Wrapper>
    </Form>
  </Wrapper>

  <Footer>
    {#if components?.Footer}
      {@render components?.Footer()}
    {:else}
      <div data-amplify-footer>
        <Button
          onclick={onForgotPasswordClicked}
          class="amplify-field-group__control amplify-authenticator__font"
          variation="link"
          fullWidth={true}
          size="small"
          fontWeight="normal"
          type="button"
        >
          {forgotYourPasswordLink}
        </Button>
      </div>
    {/if}
  </Footer>
</div>

// packages/vue/src/components/sign-in.vue
<script setup lang="ts">
import { computed, toRefs, useAttrs } from 'vue';

import {
  authenticatorTextUtil,
  getFormDataFromEvent,
  translate,
} from '@aws-amplify/ui';

import { useAuthenticator } from '../composables/useAuth';
import { UseAuthenticator } from '../types';
import BaseFormFields from './primitives/base-form-fields.vue';
import FederatedSignIn from './federated-sign-in.vue';

// `facade` is manually typed to `UseAuthenticator` for temporary type safety.
const facade: UseAuthenticator = useAuthenticator();
const { submitForm, updateForm, toResetPassword } = facade;
const { error, isPending } = toRefs(facade);

const attrs = useAttrs();

/** @deprecated Component events are deprecated and not maintained. */
const emit = defineEmits([
  'signInSubmit',
  'forgotPasswordClicked',
  'createAccountClicked',
]);

// Text Util
const { getForgotPasswordText, getSignInText, getSigningInText } =
  authenticatorTextUtil;

// Computed Properties
const forgotYourPasswordLink = computed(() => getForgotPasswordText());
const signInButtonText = computed(() => getSignInText());
const signingInButtonText = computed(() => getSigningInText());

// Methods
const onInput = (e: Event): void => {
  const { name, value } = e.target as HTMLInputElement;
  updateForm({ name, value });
};

const onSignInSubmit = (e: Event): void => {
  // TODO(BREAKING): remove unused emit
  // istanbul ignore next
  if (attrs?.onSignInSubmit) {
    emit('signInSubmit', e);
  } else {
    submitForm(getFormDataFromEvent(e));
  }
};

const onForgotPasswordClicked = (): void => {
  // TODO(BREAKING): remove unused emit
  // istanbul ignore next
  if (attrs?.onForgotPasswordClicked) {
    emit('forgotPasswordClicked');
  } else {
    toResetPassword();
  }
};
</script>

<template>
  <slot v-bind="$attrs" name="signInSlotI">
    <slot name="header"></slot>

    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-signin
        @input="onInput"
        @submit.prevent="onSignInSubmit"
        method="post"
      >
        <template #formt="{ slotData }">
          <slot
            name="form"
            :info="slotData"
            :onSignInSubmit="onSignInSubmit"
            :onInput="onInput"
            :onForgotPasswordClicked="onForgotPasswordClicked"
          >
          </slot>
        </template>
        <federated-sign-in></federated-sign-in>
        <base-wrapper class="amplify-flex amplify-authenticator__column">
          <base-field-set
            :disabled="isPending"
            class="amplify-flex amplify-authenticator__column"
          >
            <template #fieldSetI="{ slotData }">
              <slot name="signin-fields" :info="slotData"> </slot>
            </template>
            <legend class="amplify-visually-hidden">Sign in</legend>
            <base-form-fields route="signIn"></base-form-fields>
          </base-field-set>
          <base-alert v-if="error">
            {{ translate(error) }}
          </base-alert>

          <amplify-button
            :disabled="isPending"
            class="amplify-field-group__control amplify-authenticator__font"
            :fullwidth="true"
            :loading="false"
            :variation="'primary'"
          >
            {{ isPending ? signingInButtonText : signInButtonText }}
          </amplify-button>
        </base-wrapper>
      </base-form>
    </base-wrapper>

    <base-footer>
      <slot name="footer">
        <div data-amplify-footer>
          <amplify-button
            @click="onForgotPasswordClicked"
            class="amplify-field-group__control amplify-authenticator__font"
            :variation="'link'"
            :fullwidth="true"
            :size="'small'"
            style="font-weight: normal"
            type="button"
          >
            {{ forgotYourPasswordLink }}
          </amplify-button>
        </div>
      </slot>
    </base-footer>
  </slot>
</template>
