// packages/react/src/components/Authenticator/shared/UserNameAlias.tsx
import {
  ActorContextWithForms,
  getActorContext,
  getAliasInfoFromContext,
  LoginMechanism,
  translate,
} from '@aws-amplify/ui';
import React, { useState } from 'react';

import { useAuthenticator } from '..';
import { PhoneNumberField, TextField } from '../../..';

export interface UserNameAliasProps {
  alias?: LoginMechanism;
  [key: string]: any;
}

export function UserNameAlias(props: UserNameAliasProps) {
  const { alias, ...attrs } = props;
  const { _state, updateForm } = useAuthenticator();

  const { country_code: defaultCountryCode }: ActorContextWithForms =
    getActorContext(_state);
  const { label, type, error } = getAliasInfoFromContext(_state.context, alias);
  const i18nLabel = translate<string>(label);

  const isPhoneAlias = type === 'tel';
  const inputFieldName = alias ?? 'username';
  const countryCodeName = 'country_code';

  const [fullPhoneNumber, setFullPhoneNumber] = useState({
    [countryCodeName]: defaultCountryCode,
  });

  /**
   * When the field being rendered is for a phone number, this handler is used to prevent change event propagation in
   * order to manually update the state machine with a country code + phone number.
   */
  const handlePhoneNumberChange = (
    event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    event.stopPropagation();

    const newState = {
      ...fullPhoneNumber,
      [event.target.name]: event.target.value,
    };

    updateForm({
      name: inputFieldName,
      value: newState[countryCodeName] + newState[inputFieldName],
    });

    setFullPhoneNumber(newState);
  };

  return isPhoneAlias ? (
    <PhoneNumberField
      autoComplete="username"
      countryCodeName={countryCodeName}
      defaultCountryCode={defaultCountryCode}
      errorMessage={error}
      label={i18nLabel}
      labelHidden={true}
      name={inputFieldName}
      onCountryCodeChange={handlePhoneNumberChange}
      onChange={handlePhoneNumberChange}
      placeholder={i18nLabel}
      isRequired
      {...attrs}
    />
  ) : (
    <TextField
      autoComplete="username"
      errorMessage={error}
      label={i18nLabel}
      labelHidden={true}
      name={inputFieldName}
      required
      placeholder={i18nLabel}
      isRequired
      type={type}
      {...attrs}
    />
  );
}

// packages/vue/src/components/user-name-alias.vue
<template>
  <base-wrapper
    class="
      amplify-flex amplify-field amplify-textfield amplify-phonenumberfield
    "
    style="flex-direction: column"
    @input.prevent="handlePhoneNumberChange"
  >
    <base-label
      class="amplify-label sr-only"
      for="amplify-field-601d"
      v-bind="$attrs"
    >
      {{ label }}
    </base-label>
    <base-wrapper class="amplify-flex amplify-field-group">
      <base-wrapper class="amplify-field-group__outer-start">
        <!--Drop Down-->
        <template v-if="type === 'tel'">
          <base-wrapper
            class="
              amplify-flex
              amplify-field
              amplify-selectfield
              amplify-countrycodeselect
            "
            style="flex-direction: column"
          >
            <base-label class="amplify-label sr-only" for="amplify-field-1177">
              {{ 'Country Code' }}
            </base-label>
            <base-wrapper class="amplify-select__wrapper">
              <base-select
                class="amplify-select amplify-field-group__control"
                id="amplify-field-1177"
                aria-label="country code"
                name="country_code"
                :options="dialCodes"
                :selectValue="defaultDialCode"
              >
              </base-select>
              <base-wrapper
                class="amplify-flex amplify-select__icon-wrapper"
                style="align-items: center; justify-content: center"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="amplify-icon"
                  viewBox="0 0 24 24"
                  data-size="large"
                  fill="currentColor"
                >
                  <path d="M16.59 8.59L12 13.17 7.41 8.59 6 10l6 6 6-6z"></path>
                </svg>
              </base-wrapper>
            </base-wrapper>
          </base-wrapper>
        </template>
      </base-wrapper>

      <base-wrapper class="amplify-field-group__field-wrapper">
        <!--input field-->
        <base-input
          class="amplify-input amplify-field-group__control"
          id="amplify-field-601d"
          aria-invalid="false"
          :textValue="uName"
          autocomplete="username"
          :placeholder="label"
          required
          :name="name"
          :disabled="disabled"
          :type="type"
        ></base-input>
      </base-wrapper>
    </base-wrapper>
  </base-wrapper>
</template>

<script setup lang="ts">
import { ref, computed, ComputedRef, onMounted } from 'vue';
import {
  authInputAttributes,
  getActorContext,
  getAliasInfoFromContext,
  ActorContextWithForms,
  countryDialCodes,
  translate,
  LoginMechanism,
} from '@aws-amplify/ui';

import { useAuth, useAuthenticator } from '../composables/useAuth';
import { useAliases } from '../composables/useUtils';

interface PropsInterface {
  userNameAlias?: boolean;
  userName?: string;
  disabled?: boolean;
}

const { userNameAlias, userName, disabled } = withDefaults(
  defineProps<PropsInterface>(),
  {
    userNameAlias: false,
    userName: '',
    disable: false,
  }
);

const { state, send } = useAuth();
const { updateForm } = useAuthenticator();

const {
  value: { context },
} = state;

const actorContext: ComputedRef<ActorContextWithForms> = computed(() =>
  getActorContext(state.value)
);

const defaultDialCode = actorContext.value.country_code;

let uName = ref('');

if (userName) {
  uName = computed(() => userName);
}

const dialCodes = computed(() => countryDialCodes);

const [primaryAlias] = useAliases(
  context?.config?.loginMechanisms as LoginMechanism[]
);

let name = primaryAlias;
let label =
  authInputAttributes[primaryAlias as LoginMechanism]?.label ??
  authInputAttributes['username'].label;
let type =
  authInputAttributes[name as LoginMechanism]?.type ??
  authInputAttributes['username'].label;

// Only show for Sign In
if (userNameAlias) {
  const aliasInfo = getAliasInfoFromContext(context);
  label = aliasInfo.label || authInputAttributes['username'].label;
  type = aliasInfo.type;
  name = 'username';
}
label = translate<string>(label);

const fullPhoneNumber = ref({
  country_code: defaultDialCode,
  [name]: '',
});

/**
 * When the field being rendered is for a phone number, this handler is used to prevent change event propagation in
 * order to manually update the state machine with a country code + phone number.
 */
const handlePhoneNumberChange = (event: Event) => {
  event.stopPropagation();

  const target = <HTMLInputElement | HTMLSelectElement>event.target;

  fullPhoneNumber.value[target.name] = target.value;

  const { country_code, [name]: phoneNumber } = fullPhoneNumber.value;

  updateForm({
    name,
    value: country_code + phoneNumber,
  });
};
</script>
