// packages/svelte/src/lib/components/Authenticator/VerifyUser.svelte
<script lang="ts">
	import {
		authenticatorTextUtil,
		censorContactMethod,
		type ContactMethod,
		defaultFormFieldOptions,
		getFormDataFromEvent,
		translate
	} from '@aws-amplify/ui';

	import { useAuthenticator } from '../../stores/authenticator.svelte';
	import { type Components } from '../../types';

	import Wrapper from '../primitives/Wrapper.svelte';
	import Form from '../primitives/Form.svelte';
	import Button from '../controls/Button.svelte';
	import FieldSet from '../primitives/FieldSet.svelte';
	import Heading from '../primitives/Heading.svelte';
	import Footer from '../primitives/Footer.svelte';
	import Alert from '../primitives/Alert.svelte';
	import Text from '../primitives/Text.svelte';
	import Label from '../primitives/Label.svelte';
	import Input from '../primitives/Input.svelte';

	interface Props {
		components?: Omit<Components, 'FormFields'>;
	}

	const { components }: Props = $props();

	const { error, isPending, unverifiedUserAttributes, submitForm, skipVerification, updateForm } =
		$derived(useAuthenticator());

	// Text Util
	const { getAccountRecoveryInfoText, getSkipText, getVerifyText, getVerifyContactText } =
		authenticatorTextUtil;

	// Computed Properties
	const verifyHeading = $derived.by(() => getAccountRecoveryInfoText());
	const skipText = $derived.by(() => getSkipText());
	const verifyText = $derived.by(() => getVerifyText());
	const verifyContactText = $derived.by(() => getVerifyContactText());

	// Methods
	const onInput = (e: Event): void => {
		const { name, value } = e.target as HTMLInputElement;
		updateForm({ name, value });
	};

	const onVerifyUserSubmit = (e: Event): void => {
		e.preventDefault();
		submit(e);
	};

	const submit = (e: Event): void => {
		submitForm(getFormDataFromEvent(e));
	};

	const onSkipClicked = (e: Event): void => {
		e.preventDefault();
		skipVerification();
	};

	const getDefaultFormFieldOption = (key: string) => {
		const k = key as keyof typeof defaultFormFieldOptions;
		return defaultFormFieldOptions[k] as { label: ContactMethod };
	};
</script>

<Wrapper>
	<Form oninput={onInput} onsubmit={onVerifyUserSubmit}>
		<FieldSet disabled={isPending} class="amplify-flex amplify-authenticator__column">
			{#if components?.Header}
				{@render components?.Header()}
			{:else}
				<Heading class="amplify-heading" level="h3">
					{verifyHeading}
				</Heading>
			{/if}
			<Wrapper
				class="amplify-flex amplify-field amplify-radiogroupfield amplify-authenticator__column"
			>
				<!-- TODO(BREAKING): remove hard coded string 493c -->
				<Label class="amplify-visually-hidden amplify-label" id="amplify-field-493c">
					{verifyContactText}
				</Label>
				<Wrapper
					class="amplify-flex amplify-field amplify-radiogroupfield amplify-authenticator__column"
					aria-labelledby="amplify-field-493c"
				>
					{#each Object.entries(unverifiedUserAttributes) as [key, value], index (value)}
						{#if value}
							{@const verificationType = getDefaultFormFieldOption(key).label}
							<Label class="amplify-flex amplify-radio" data-amplify-verify-label>
								<Text class="amplify-text amplify-radio__label">
									{translate(verificationType)}: {censorContactMethod(verificationType, value)}
								</Text>
								<Input
									class="amplify-input amplify-field-group__control amplify-visually-hidden amplify-radio__input"
									aria-invalid="false"
									data-amplify-verify-input
									name="unverifiedAttr"
									type="radio"
									checked={index === 0}
									value={key}
								></Input>
								<Text class="amplify-flex amplify-radio__button" aria-hidden="true" />
							</Label>
						{/if}
					{/each}
				</Wrapper>
			</Wrapper>
			<Footer class="amplify-flex amplify-authenticator__column">
				{#if error}
					<Alert>
						{translate(error)}
					</Alert>
				{/if}
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					variation="primary"
					type="submit"
					disabled={isPending}
				>
					{verifyText}
				</Button>
				<Button
					class="amplify-field-group__control amplify-authenticator__font"
					fullWidth={false}
					size="small"
					variation="link"
					type="button"
					onclick={onSkipClicked}
				>
					{skipText}
				</Button>
				{@render components?.Footer?.()}
			</Footer>
		</FieldSet>
	</Form>
</Wrapper>

// packages/vue/src/components/verify-user.vue
<script setup lang="ts">
import { computed, toRefs, useAttrs } from 'vue';

import {
  authenticatorTextUtil,
  defaultFormFieldOptions,
  LoginMechanism,
  translate,
  getFormDataFromEvent,
  AuthenticatorServiceFacade,
} from '@aws-amplify/ui';

import { useAuthenticator } from '../composables/useAuth';

// `useAuthenticator` is casted for temporary type safety on this file.
const props = useAuthenticator() as AuthenticatorServiceFacade;

const { isPending, unverifiedContactMethods, error } = toRefs(props);
const { skipVerification, submitForm, updateForm } = props;

const attrs = useAttrs();

/** @deprecated Component events are deprecated and not maintained. */
const emit = defineEmits(['verifyUserSubmit', 'skipClicked']);

// Text Util
const {
  getAccountRecoveryInfoText,
  getSkipText,
  getVerifyText,
  getVerifyContactText,
} = authenticatorTextUtil;

// Computed Properties
const verifyHeading = computed(() => getAccountRecoveryInfoText());
const skipText = computed(() => getSkipText());
const verifyText = computed(() => getVerifyText());
const verifyContactText = computed(() => getVerifyContactText());

// Methods
const onInput = (e: Event): void => {
  const { name, value } = e.target as HTMLInputElement;
  updateForm({ name, value });
};

const onVerifyUserSubmit = (e: Event): void => {
  // TODO(BREAKING): remove unused emit
  // istanbul ignore next
  if (attrs?.onVerifyUserSubmit) {
    emit('verifyUserSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  submitForm(getFormDataFromEvent(e));
};

const onSkipClicked = (): void => {
  // TODO(BREAKING): remove unused emit
  // istanbul ignore next
  if (attrs?.onSkipClicked) {
    emit('skipClicked');
  } else {
    skipVerification();
  }
};
</script>

<template>
  <slot name="verifyUserSlotI">
    <base-wrapper>
      <base-form @input="onInput" @submit.prevent="onVerifyUserSubmit">
        <base-field-set
          :disabled="isPending"
          class="amplify-flex amplify-authenticator__column"
        >
          <slot name="header">
            <base-heading class="amplify-heading" :level="3">
              {{ verifyHeading }}
            </base-heading>
          </slot>
          <base-wrapper
            class="amplify-flex amplify-field amplify-radiogroupfield amplify-authenticator__column"
          >
            <base-label
              class="amplify-visually-hidden amplify-label"
              id="amplify-field-493c"
            >
              {{ verifyContactText }}
            </base-label>
            <base-wrapper
              class="amplify-flex amplify-field amplify-radiogroupfield amplify-authenticator__column"
              aria-labelledby="amplify-field-493c"
            >
              <base-label
                class="amplify-flex amplify-radio"
                data-amplify-verify-label
                id="verify"
                v-for="(value, key) in unverifiedContactMethods"
                :key="value"
              >
                <base-input
                  class="amplify-input amplify-field-group__control amplify-visually-hidden amplify-radio__input"
                  aria-invalid="false"
                  data-amplify-verify-input
                  id="verify"
                  name="unverifiedAttr"
                  type="radio"
                  :value="key"
                >
                </base-input>
                <base-text
                  class="amplify-flex amplify-radio__button"
                  aria-hidden="true"
                ></base-text>
                <base-text class="amplify-text amplify-radio__label">
                  {{ defaultFormFieldOptions[key as LoginMechanism].label }}
                </base-text>
              </base-label>
            </base-wrapper>
          </base-wrapper>
          <base-footer class="amplify-flex amplify-authenticator__column">
            <base-alert v-if="error">
              {{ translate(error) }}
            </base-alert>
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              :fullwidth="false"
              :variation="'primary'"
              type="submit"
              :disabled="isPending"
              >{{ verifyText }}</amplify-button
            >
            <amplify-button
              class="amplify-field-group__control amplify-authenticator__font"
              :fullwidth="false"
              :size="'small'"
              :variation="'link'"
              style="font-weight: normal"
              type="button"
              @click.prevent="onSkipClicked"
            >
              {{ skipText }}</amplify-button
            >
            <slot
              name="footer"
              :onSkipClicked="onSkipClicked"
              :onVerifyUserSubmit="onVerifyUserSubmit"
            >
            </slot>
          </base-footer>
        </base-field-set>
      </base-form>
    </base-wrapper>
  </slot>
</template>
