// examples/vue/src/pages/ui/components/authenticator/sign-in-with-email/index.vue
<script setup lang="ts">
import Amplify, { Auth } from 'aws-amplify';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';
import aws_exports from './aws-exports';

Amplify.configure(aws_exports);
</script>

<template>
  <authenticator :hide-sign-up="true">
    <template v-slot="{ user, signOut }">
      <h1>Hello {{ user.username }}!</h1>
      <button @click="signOut">Sign Out</button>
    </template>
  </authenticator>
</template>

// examples/svelte/src/routes/ui/components/authenticator/sign-in-with-email/index.svelte
<script lang="ts">
  import { Amplify } from 'aws-amplify';
  import { Authenticator, authStore } from '@aws-amplify/ui-svelte';
  import '@aws-amplify/ui-svelte/styles.css';
  import aws_exports from './aws-exports';
  Amplify.configure({ ...aws_exports, ssr: true });
  const { signOut, user } = authStore;
</script>

<h1>Welcome to SvelteKit</h1>
<Authenticator>
  <h1>Hello {$user.username}!</h1>
  <button on:click={signOut}>Sign Out</button>
</Authenticator>
