// examples/vue/src/pages/ui/components/authenticator/gen2/i18n/index.vue
<script setup lang="ts">
import { Authenticator, translations } from '@aws-amplify/ui-vue';
import { Amplify } from 'aws-amplify';
import { I18n } from 'aws-amplify/utils';
import '@aws-amplify/ui-vue/styles.css';
import amplifyOutputs from './amplify_outputs';

I18n.putVocabularies(translations);
I18n.setLanguage('ja');
I18n.putVocabulariesForLanguage('ja', {
  'Sign In': 'Sign In Custom',
  'Incorrect username or password.': 'Error with your user',
});

Amplify.configure(amplifyOutputs);
</script>
<template>
  <authenticator initial-state="signUp">
    <template v-slot="{ user, send }">
      <h1 class="mb-10 text-6xl">Hello {{ user.username }}!</h1>
      <button
        className="px-2 bg-white rounded shadow"
        @click="send('SIGN_OUT')"
      >
        Sign Out
      </button>
    </template>
  </authenticator>
</template>

// examples/angular-gen2/src/pages/ui/components/authenticator/i18n/i18n.component.ts
import { Component, OnInit } from '@angular/core';
import { translations } from '@aws-amplify/ui-angular';
import amplifyOutputs from './amplify_outputs';
import { Amplify } from 'aws-amplify';
import { I18n } from 'aws-amplify/utils';
@Component({
  selector: 'i18n',
  templateUrl: 'i18n.component.html',
})
export class I18nComponent implements OnInit {
  constructor() {
    Amplify.configure(amplifyOutputs);
  }

  ngOnInit() {
    I18n.putVocabularies(translations);
    I18n.setLanguage('ja');
    I18n.putVocabulariesForLanguage('ja', {
      'Sign In': 'Sign In Custom',
      'Incorrect username or password.': 'Error with your user',
    });
  }

  ngOnDestroy() {
    I18n.setLanguage('en'); // reset the languages back
  }
}
