// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-in/confirm-sign-in.component.ts
import { Component, HostBinding, OnInit } from '@angular/core';
import { Logger } from 'aws-amplify';
import {
  AuthChallengeNames,
  SortedFormFields,
  getActorContext,
  getFormDataFromEvent,
  getSortedFormFields,
  SignInContext,
} from '@aws-amplify/ui';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { translate } from '@aws-amplify/ui';

const logger = new Logger('ConfirmSignIn');

@Component({
  selector: 'amplify-confirm-sign-in',
  templateUrl: './confirm-sign-in.component.html',
})
export class ConfirmSignInComponent implements OnInit {
  @HostBinding('attr.data-amplify-authenticator-confirmsignin') dataAttr = '';

  // translated texts
  public headerText: string;
  public confirmText = translate('Confirm');
  public backToSignInText = translate('Back to Sign In');
  public sortedFormFields: SortedFormFields;

  constructor(public authenticator: AuthenticatorService) {}

  ngOnInit(): void {
    this.setHeaderText();
    this.setFormFields();
  }

  public setFormFields() {
    const _state = this.authenticator.authState;
    this.sortedFormFields = getSortedFormFields('confirmSignIn', _state);
  }

  public get context() {
    return this.authenticator.slotContext;
  }

  setHeaderText(): void {
    const state = this.authenticator.authState;
    const actorContext = getActorContext(state) as SignInContext;
    const { challengeName } = actorContext;
    switch (challengeName) {
      case AuthChallengeNames.SOFTWARE_TOKEN_MFA:
        this.headerText = translate('Confirm TOTP Code');
        break;
      case AuthChallengeNames.SMS_MFA:
        this.headerText = translate('Confirm SMS Code');
        break;
      default:
        logger.error('Unexpected challengeName', challengeName);
    }
  }

  onInput(event: Event): void {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<div data-amplify-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="authenticator.isPending"
    >
      <amplify-slot name="confirm-sign-in-header" [context]="context">
        <h3 class="amplify-heading">{{ headerText }}</h3>
      </amplify-slot>
      <amplify-form-field
        name="confirmation_code"
        label="Code *"
        type="text"
        autocomplete="one-time-code"
        [labelHidden]="grabField('confirmation_code', 'labelHidden', true)"
        [placeholder]="grabField('confirmation_code', 'placeholder', null)"
        [required]="grabField('confirmation_code', 'required', true)"
        [label]="grabField('confirmation_code', 'label', 'Code *')"
      ></amplify-form-field>

      <button amplify-button variation="primary" fullWidth="true" type="submit">
        {{ confirmText }}
      </button>
      <button
        amplify-button
        size="small"
        variation="link"
        fontWeight="normal"
        fullWidth="true"
        (click)="authenticator.toSignIn()"
      >
        {{ backToSignInText }}
      </button>
      <amplify-error *ngIf="authenticator.error">
        {{ authenticator.error }}
      </amplify-error>
    </fieldset>
    <amplify-slot
      name="confirm-sign-in-footer"
      [context]="context"
    ></amplify-slot>
  </form>
</div>

// packages/svelte/src/components/Authenticator/ConfirmSignIn.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { useAuthenticatorStore } from '../../composables/useAuthenticator';
  import TextField from '../primitives/TextField.svelte';
  import Button from '../primitives/Button.svelte';
  
  const authenticator = useAuthenticatorStore();
  
  let confirmationCode = '';
  
  $: ({
    error,
    isPending,
    submitForm,
    updateForm,
    toSignIn,
    challengeName,
    validationErrors,
  } = $authenticator);
  
  $: challengeMessage = (() => {
    switch (challengeName) {
      case 'SMS_MFA':
        return 'A confirmation code has been sent to your phone';
      case 'SOFTWARE_TOKEN_MFA':
        return 'Enter the code from your authenticator app';
      default:
        return 'Enter your confirmation code';
    }
  })();
  
  function handleCodeInput(event: Event) {
    const target = event.target as HTMLInputElement;
    confirmationCode = target.value;
    updateForm({ name: 'confirmation_code', value: confirmationCode });
  }
  
  function handleSubmit(event: Event) {
    event.preventDefault();
    submitForm({
      confirmation_code: confirmationCode,
    });
  }
  
  function handleBackToSignIn() {
    toSignIn();
  }
  
  onMount(() => {
    confirmationCode = '';
  });
</script>

<div class="amplify-authenticator__confirm-sign-in">
  <form on:submit={handleSubmit} data-amplify-authenticator-confirmsignin>
    <fieldset class="amplify-flex amplify-authenticator__column">
      <div class="amplify-authenticator__header">
        <h3 class="amplify-heading">Confirm Sign In</h3>
        <p class="amplify-text">{challengeMessage}</p>
      </div>
      
      <TextField
        label="Confirmation Code"
        value={confirmationCode}
        on:input={handleCodeInput}
        on:blur={() => updateForm({ name: 'confirmation_code', value: confirmationCode })}
        hasError={!!validationErrors?.confirmation_code}
        errorMessage={validationErrors?.confirmation_code}
        isRequired
        autocomplete="one-time-code"
        placeholder="Enter your code"
      />
      
      {#if error}
        <div class="amplify-alert amplify-alert--error" role="alert">
          {error}
        </div>
      {/if}
      
      <Button
        type="submit"
        isFullWidth
        isLoading={isPending}
        loadingText="Confirming..."
        isDisabled={!confirmationCode}
      >
        Confirm
      </Button>
      
      <Button
        type="button"
        variation="link"
        isFullWidth
        size="small"
        on:click={handleBackToSignIn}
      >
        Back to Sign In
      </Button>
    </fieldset>
  </form>
</div>

<style>
  .amplify-authenticator__confirm-sign-in {
    width: 100%;
  }
  
  form {
    width: 100%;
  }
  
  fieldset {
    border: none;
    margin: 0;
    padding: 0;
    gap: var(--amplify-components-authenticator-form-gap);
  }
  
  .amplify-authenticator__header {
    text-align: center;
    margin-bottom: var(--amplify-space-medium);
  }
  
  .amplify-heading {
    font-size: var(--amplify-font-sizes-xl);
    font-weight: var(--amplify-font-weights-bold);
    margin: 0 0 var(--amplify-space-xs) 0;
    color: var(--amplify-colors-font-primary);
  }
  
  .amplify-text {
    font-size: var(--amplify-font-sizes-medium);
    color: var(--amplify-colors-font-secondary);
    margin: 0;
  }
  
  .amplify-alert {
    background-color: var(--amplify-components-alert-background-color);
    border: var(--amplify-components-alert-border);
    border-radius: var(--amplify-components-alert-border-radius);
    color: var(--amplify-components-alert-color);
    padding: var(--amplify-components-alert-padding);
    position: relative;
  }
  
  .amplify-alert--error {
    background-color: var(--amplify-components-alert-error-background-color);
    border-color: var(--amplify-components-alert-error-border-color);
    color: var(--amplify-components-alert-error-color);
  }
  
  .amplify-flex {
    display: flex;
  }
  
  .amplify-authenticator__column {
    flex-direction: column;
  }
</style>
