// packages/vue/src/components/confirm-reset-password.vue
<script setup lang="ts">
import { computed, ComputedRef, useAttrs, defineEmits } from 'vue';
import {
  getActorContext,
  getActorState,
  ResetPasswordContext,
  ResetPasswordState,
  ValidationError,
  translate,
} from '@aws-amplify/ui';

import { useAuth, useAuthenticator } from '../composables/useAuth';
import PasswordControl from './password-control.vue';

const { state, send } = useAuth();
const props = useAuthenticator();

const attrs = useAttrs();
const emit = defineEmits(['confirmResetPasswordSubmit', 'backToSignInClicked']);

const actorState: ComputedRef<ResetPasswordState> = computed(() =>
  getActorState(state.value)
) as ComputedRef<ResetPasswordState>;

const actorContext = computed(() =>
  getActorContext(state.value)
) as ComputedRef<ResetPasswordContext>;

// Computed Properties
const resendCodeText = computed(() => translate('Resend Code'));
const confirmationCodeText = computed(() => translate('Confirmation Code'));
const confirmResetPasswordHeading = computed(() =>
  translate('Reset your Password')
);
const confirmResetPasswordText = computed(() => translate('Submit'));

const codeText = computed(() => translate('Code'));
const newPasswordLabel = computed(() => translate('New password'));
const confirmPasswordLabel = computed(() => translate('Confirm Password'));

// Methods
const onConfirmResetPasswordSubmit = (e: Event): void => {
  if (attrs?.onConfirmResetPasswordSubmit) {
    emit('confirmResetPasswordSubmit', e);
  } else {
    submit(e);
  }
};

const submit = (e: Event): void => {
  const formData = new FormData(<HTMLFormElement>e.target);
  send({
    type: 'SUBMIT',
    //@ts-ignore
    data: {
      //@ts-ignore
      ...Object.fromEntries(formData),
    },
  });
};

const onLostYourCodeClicked = (): void => {
  send({
    type: 'RESEND',
  });
};

const onInput = (e: Event) => {
  const { name, value } = <HTMLInputElement>e.target;
  send({
    type: 'CHANGE',
    data: { name, value },
  });
};

function onBlur(e: Event) {
  const { name } = <HTMLInputElement>e.target;
  props.updateBlur({ name });
}
</script>

<template>
  <slot v-bind="$attrs" name="confirmResetPasswordSlotI">
    <base-wrapper v-bind="$attrs">
      <base-form
        data-amplify-authenticator-confirmResetpassword
        @input="onInput"
        @submit.prevent="onConfirmResetPasswordSubmit"
      >
        <base-field-set
          class="amplify-flex"
          style="flex-direction: column"
          :disabled="actorState.matches('confirmResetPassword.pending')"
        >
          <slot name="header">
            <base-heading class="amplify-heading" :level="3">
              {{ confirmResetPasswordHeading }}
            </base-heading>
          </slot>

          <base-wrapper class="amplify-flex" style="flex-direction: column">
            <base-wrapper
              class="amplify-flex amplify-field amplify-textfield"
              style="flex-direction: column"
            >
              <base-label
                class="sr-only amplify-label"
                for="amplify-field-d653"
              >
                {{ confirmationCodeText }}
              </base-label>
              <base-wrapper class="amplify-flex">
                <base-input
                  class="amplify-input amplify-field-group__control"
                  id="amplify-field-d653"
                  aria-invalid="false"
                  autocomplete="one-time-code"
                  :placeholder="codeText"
                  name="confirmation_code"
                  required
                  type="number"
                ></base-input>
              </base-wrapper>
            </base-wrapper>
            <base-wrapper
              class="
                amplify-flex
                amplify-field
                amplify-textfield
                amplify-passwordfield
                password-field
              "
              style="flex-direction: column"
            >
              <password-control
                name="password"
                :label="newPasswordLabel"
                autocomplete="current-password"
                :ariainvalid="
                  !!(actorContext.validationError as ValidationError)['confirm_password']
                "
                @blur="onBlur"
              />
            </base-wrapper>
            <base-wrapper
              class="
                amplify-flex
                amplify-field
                amplify-textfield
                amplify-passwordfield
              "
              style="flex-direction: column"
            >
              <password-control
                name="confirm_password"
                :label="confirmPasswordLabel"
                autocomplete="new-password"
                :ariainvalid="
                  !!(actorContext.validationError as ValidationError)['confirm_password']
                "
                @blur="onBlur"
              />
            </base-wrapper>
          </base-wrapper>
          <base-footer class="amplify-flex" style="flex-direction: column">
            <base-box
              data-ui-error
              data-variation="error"
              role="alert"
              class="amplify-text"
              v-if="!!(actorContext.validationError as ValidationError)['confirm_password']"
            >
              {{ (actorContext.validationError as ValidationError)['confirm_password'] }}
            </base-box>
            <base-alert v-if="actorState?.context?.remoteError">
              {{ actorState?.context?.remoteError }}
            </base-alert>
            <amplify-button
              class="amplify-field-group__control"
              data-fullwidth="false"
              data-variation="primary"
              type="submit"
              style="font-weight: normal"
              :disabled="actorState.matches('confirmResetPassword.pending')"
              >{{ confirmResetPasswordText }}</amplify-button
            >
            <amplify-button
              class="amplify-field-group__control"
              data-fullwidth="false"
              data-size="small"
              data-variation="link"
              type="button"
              @click.prevent="onLostYourCodeClicked"
              style="font-weight: normal"
            >
              {{ resendCodeText }}
            </amplify-button>
            <slot
              name="footer"
              :onConfirmResetPasswordSubmit="onConfirmResetPasswordSubmit"
              :onLostYourCodeClicked="onLostYourCodeClicked"
            >
            </slot>
          </base-footer>
        </base-field-set>
      </base-form>
    </base-wrapper>
  </slot>
</template>

// packages/svelte/src/components/Authenticator/ConfirmResetPassword.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { useAuthenticatorStore } from '../../composables/useAuthenticator';
  import TextField from '../primitives/TextField.svelte';
  import PasswordField from '../primitives/PasswordField.svelte';
  import Button from '../primitives/Button.svelte';
  
  const authenticator = useAuthenticatorStore();
  
  let confirmationCode = '';
  let newPassword = '';
  let confirmPassword = '';
  
  $: ({
    error,
    isPending,
    submitForm,
    updateForm,
    resendCode,
    toSignIn,
    username,
    validationErrors,
  } = $authenticator);
  
  $: passwordsMatch = newPassword === confirmPassword;
  $: confirmPasswordError = confirmPassword && !passwordsMatch ? 'Passwords do not match' : '';
  
  function handleInput(event: Event, fieldName: string) {
    const target = event.target as HTMLInputElement;
    const value = target.value;
    
    switch (fieldName) {
      case 'confirmation_code':
        confirmationCode = value;
        break;
      case 'password':
        newPassword = value;
        break;
      case 'confirmPassword':
        confirmPassword = value;
        break;
    }
    
    if (fieldName !== 'confirmPassword') {
      updateForm({ name: fieldName, value });
    }
  }
  
  function handleSubmit(event: Event) {
    event.preventDefault();
    
    if (!passwordsMatch) {
      return;
    }
    
    submitForm({
      username,
      confirmation_code: confirmationCode,
      password: newPassword,
    });
  }
  
  function handleResendCode() {
    resendCode();
  }
  
  onMount(() => {
    confirmationCode = '';
    newPassword = '';
    confirmPassword = '';
  });
</script>

<div class="amplify-authenticator__confirm-reset-password">
  <form on:submit={handleSubmit} data-amplify-authenticator-confirmresetpassword>
    <fieldset class="amplify-flex amplify-authenticator__column">
      <div class="amplify-authenticator__header">
        <h3 class="amplify-heading">Reset your password</h3>
        <p class="amplify-text">
          Enter the code sent to your email along with your new password.
        </p>
      </div>
      
      <TextField
        label="Confirmation Code"
        value={confirmationCode}
        on:input={(e) => handleInput(e, 'confirmation_code')}
        on:blur={() => updateForm({ name: 'confirmation_code', value: confirmationCode })}
        hasError={!!validationErrors?.confirmation_code}
        errorMessage={validationErrors?.confirmation_code}
        isRequired
        autocomplete="one-time-code"
        placeholder="Enter your code"
      />
      
      <PasswordField
        label="New Password"
        value={newPassword}
        on:input={(e) => handleInput(e, 'password')}
        on:blur={() => updateForm({ name: 'password', value: newPassword })}
        hasError={!!validationErrors?.password}
        errorMessage={validationErrors?.password}
        isRequired
        autocomplete="new-password"
        placeholder="Enter your new password"
      />
      
      <PasswordField
        label="Confirm Password"
        value={confirmPassword}
        on:input={(e) => handleInput(e, 'confirmPassword')}
        hasError={!!confirmPasswordError}
        errorMessage={confirmPasswordError}
        isRequired
        autocomplete="new-password"
        placeholder="Confirm your new password"
      />
      
      {#if error}
        <div class="amplify-alert amplify-alert--error" role="alert">
          {error}
        </div>
      {/if}
      
      <Button
        type="submit"
        isFullWidth
        isLoading={isPending}
        loadingText="Resetting..."
        isDisabled={!confirmationCode || !newPassword || !passwordsMatch}
      >
        Submit
      </Button>
      
      <div class="amplify-authenticator__footer">
        <Button
          type="button"
          variation="link"
          size="small"
          on:click={handleResendCode}
          isDisabled={isPending}
        >
          Resend Code
        </Button>
        
        <Button
          type="button"
          variation="link"
          size="small"
          on:click={() => toSignIn()}
        >
          Back to Sign In
        </Button>
      </div>
    </fieldset>
  </form>
</div>

<style>
  .amplify-authenticator__confirm-reset-password {
    width: 100%;
  }
  
  form {
    width: 100%;
  }
  
  fieldset {
    border: none;
    margin: 0;
    padding: 0;
    gap: var(--amplify-components-authenticator-form-gap);
  }
  
  .amplify-authenticator__header {
    text-align: center;
    margin-bottom: var(--amplify-space-medium);
  }
  
  .amplify-heading {
    font-size: var(--amplify-font-sizes-xl);
    font-weight: var(--amplify-font-weights-bold);
    margin: 0 0 var(--amplify-space-xs) 0;
    color: var(--amplify-colors-font-primary);
  }
  
  .amplify-text {
    font-size: var(--amplify-font-sizes-medium);
    color: var(--amplify-colors-font-secondary);
    margin: 0;
  }
  
  .amplify-alert {
    background-color: var(--amplify-components-alert-background-color);
    border: var(--amplify-components-alert-border);
    border-radius: var(--amplify-components-alert-border-radius);
    color: var(--amplify-components-alert-color);
    padding: var(--amplify-components-alert-padding);
    position: relative;
  }
  
  .amplify-alert--error {
    background-color: var(--amplify-components-alert-error-background-color);
    border-color: var(--amplify-components-alert-error-border-color);
    color: var(--amplify-components-alert-error-color);
  }
  
  .amplify-flex {
    display: flex;
  }
  
  .amplify-authenticator__column {
    flex-direction: column;
  }
  
  .amplify-authenticator__footer {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--amplify-space-xs);
  }
</style>
