// packages/svelte/src/lib/components/ConfirmSignUp.svelte
<script lang="ts">
  import {
    authState,
    codeDeliveryDetails,
    updateForm,
    submitForm,
    resendCode,
    error,
    isPending,
  } from '$lib/components/authStore';
  import { translate } from '@aws-amplify/ui';
  import AmplifyFormField from './primitives/AmplifyFormField.svelte';
  import AmplifyButton from './primitives/AmplifyButton.svelte';
  import AmplifyError from './primitives/AmplifyError.svelte';
  // translated texts
  const resendCodeText = translate('Resend Code');
  const confirmText = translate('Confirm');

  let confirmSignUpHeading = '';
  let subtitleText = '';

  $: {
    const { DeliveryMedium = {} } = $codeDeliveryDetails;

    confirmSignUpHeading =
      DeliveryMedium === 'EMAIL'
        ? translate('We Emailed You')
        : DeliveryMedium === 'SMS'
        ? translate('We Texted You')
        : translate('We Sent A Code');
  }

  $: {
    const { DeliveryMedium, Destination } = $codeDeliveryDetails;
    subtitleText =
      DeliveryMedium === 'EMAIL'
        ? `Your code is on the way. To log in, enter the code we emailed to ${Destination}. It may take a minute to arrive.`
        : DeliveryMedium === 'SMS'
        ? `Your code is on the way. To log in, enter the code we texted to ${Destination}. It may take a minute to arrive.`
        : translate(
            `Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.`
          );
  }

  function onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    updateForm({ name, value });
  }

  function onSubmit(event: Event): void {
    event.preventDefault();
    submitForm();
  }
</script>

<div data-amplify-container>
  <form
    data-amplify-form
    on:submit|preventDefault={onSubmit}
    on:input={onInput}
  >
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      disabled={$isPending}
    >
      <h3 class="amplify-heading" style="font-size: 1.5rem">
        {confirmSignUpHeading}
      </h3>
      <span style="margin-bottom: 1rem">
        {subtitleText}
      </span>
      <AmplifyFormField
        name="confirmation_code"
        type="text"
        autocomplete="one-time-code"
      />

      {#if $error}
        <AmplifyError>
          {$error}
        </AmplifyError>
      {/if}

      <AmplifyButton
        amplify-AmplifyButton
        variation="primary"
        fullWidth="true"
        type="submit"
      >
        {confirmText}
      </AmplifyButton>
      <AmplifyButton
        amplify-button
        fontWeight="normal"
        on:click={() => resendCode()}
      >
        {resendCodeText}
      </AmplifyButton>
    </fieldset>
  </form>
</div>

// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { getFormDataFromEvent, translate } from '@aws-amplify/ui';
@Component({
  selector: 'amplify-confirm-sign-up',
  templateUrl: './confirm-sign-up.component.html',
})
export class ConfirmSignUpComponent {
  @Input() headerText = translate('Confirm Sign Up');

  @HostBinding('attr.data-amplify-authenticator-confirmsignup') dataAttr = '';

  // translated texts
  public resendCodeText = translate('Resend Code');
  public confirmText = translate('Confirm');
  public emailMessage = translate(
    'Your code is on the way. To log in, enter the code we emailed to'
  );
  public textedMessage = translate(
    'Your code is on the way. To log in, enter the code we texted to'
  );
  public defaultMessage = translate(
    'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.'
  );
  public minutesMessage = translate('It may take a minute to arrive.');

  constructor(public authenticator: AuthenticatorService) {}

  public get context() {
    return this.authenticator.slotContext;
  }

  public get confirmSignUpHeading(): string {
    const { codeDeliveryDetails: { DeliveryMedium } = {} } = this.authenticator;
    return DeliveryMedium === 'EMAIL'
      ? translate('We Emailed You')
      : DeliveryMedium === 'SMS'
      ? translate('We Texted You')
      : translate('We Sent A Code');
  }

  public get subtitleText(): string {
    const { codeDeliveryDetails: { DeliveryMedium, Destination } = {} } =
      this.authenticator;
    return DeliveryMedium === 'EMAIL'
      ? `${this.emailMessage} ${Destination}. ${this.minutesMessage}`
      : DeliveryMedium === 'SMS'
      ? `${this.textedMessage} ${Destination}. ${this.minutesMessage}`
      : translate(`${this.defaultMessage}`);
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<ng-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="context.isPending"
    >
      <amplify-slot name="confirm-sign-up-header" [context]="context">
        <h3 class="amplify-heading" style="font-size: 1.5rem">
          {{ confirmSignUpHeading }}
        </h3>
      </amplify-slot>
      <amplify-slot name="confirm-sign-up-form-fields" [context]="context">
        <span style="margin-bottom: 1rem">
          {{ subtitleText }}
        </span>
        <amplify-base-form-fields
          route="confirmSignUp"
        ></amplify-base-form-fields>

        <button
          amplify-button
          variation="primary"
          fullWidth="true"
          type="submit"
        >
          {{ confirmText }}
        </button>
        <button
          amplify-button
          fontWeight="normal"
          (click)="authenticator.resendCode()"
        >
          {{ resendCodeText }}
        </button>
      </amplify-slot>
    </fieldset>

    <amplify-error *ngIf="context.error">
      {{ authenticator.error }}
    </amplify-error>
    <amplify-slot
      name="confirm-sign-up-footer"
      [context]="context"
    ></amplify-slot>
  </form>
</ng-container>
