// packages/react/src/components/Authenticator/ConfirmSignUp/ConfirmSignUp.tsx
import { translate } from '@aws-amplify/ui';

import { Button, Flex, Heading, Text } from '../../../primitives';
import {
  useAuthenticator,
  useCustomComponents,
  useFormHandlers,
} from '../hooks';

import { RemoteErrorMessage } from '../shared';
import { FormFields } from '../shared/FormFields';

export function ConfirmSignUp() {
  const {
    isPending,
    resendCode,
    codeDeliveryDetails: { DeliveryMedium, Destination } = {},
  } = useAuthenticator((context) => [
    context.isPending,
    context.resendCode,
    context.codeDeliveryDetails,
  ]);
  const { handleChange, handleSubmit } = useFormHandlers();

  const {
    components: {
      ConfirmSignUp: {
        Header = ConfirmSignUp.Header,
        Footer = ConfirmSignUp.Footer,
      },
    },
  } = useCustomComponents();

  const emailMessage = translate(
    'Your code is on the way. To log in, enter the code we emailed to'
  );
  const textedMessage = translate(
    'Your code is on the way. To log in, enter the code we texted to'
  );
  const defaultMessage = translate(
    'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.'
  );

  const minutesMessage = translate('It may take a minute to arrive.');

  const subtitleText =
    DeliveryMedium === 'EMAIL'
      ? `${emailMessage} ${Destination}. ${minutesMessage}`
      : DeliveryMedium === 'SMS'
      ? `${textedMessage} ${Destination}. ${minutesMessage}`
      : translate(`${defaultMessage}`);

  return (
    // TODO Automatically add these namespaces again from `useAmplify`
    <form
      data-amplify-form=""
      data-amplify-authenticator-confirmsignup=""
      method="post"
      onChange={handleChange}
      onSubmit={handleSubmit}
    >
      <fieldset
        style={{ display: 'flex', flexDirection: 'column' }}
        className="amplify-flex"
        disabled={isPending}
      >
        <Header />

        <Flex direction="column">
          <Text style={{ marginBottom: '1rem' }}>{subtitleText}</Text>

          <FormFields route="confirmSignUp" />

          <RemoteErrorMessage />

          <Button
            variation="primary"
            isDisabled={isPending}
            type="submit"
            loadingText={translate('Confirming')}
            isLoading={isPending}
            fontWeight="normal"
          >
            {translate('Confirm')}
          </Button>

          <Button onClick={resendCode} type="button" fontWeight="normal">
            {translate('Resend Code')}
          </Button>
        </Flex>
        <Footer />
      </fieldset>
    </form>
  );
}

ConfirmSignUp.Header = () => {
  const { codeDeliveryDetails: { DeliveryMedium } = {} } = useAuthenticator(
    (context) => [context.codeDeliveryDetails]
  );

  const confirmSignUpHeading =
    DeliveryMedium === 'EMAIL'
      ? translate('We Emailed You')
      : DeliveryMedium === 'SMS'
      ? translate('We Texted You')
      : translate('We Sent A Code');

  return (
    <Heading level={3} style={{ fontSize: '1.5rem' }}>
      {confirmSignUpHeading}
    </Heading>
  );
};

ConfirmSignUp.Footer = (): JSX.Element => null;

// packages/angular/projects/ui-angular/src/lib/components/authenticator/components/confirm-sign-up/confirm-sign-up.component.ts
import { Component, HostBinding, Input } from '@angular/core';
import { AuthenticatorService } from '../../../../services/authenticator.service';
import { getFormDataFromEvent, translate } from '@aws-amplify/ui';
@Component({
  selector: 'amplify-confirm-sign-up',
  templateUrl: './confirm-sign-up.component.html',
})
export class ConfirmSignUpComponent {
  @Input() headerText = translate('Confirm Sign Up');

  @HostBinding('attr.data-amplify-authenticator-confirmsignup') dataAttr = '';

  // translated texts
  public resendCodeText = translate('Resend Code');
  public confirmText = translate('Confirm');
  public emailMessage = translate(
    'Your code is on the way. To log in, enter the code we emailed to'
  );
  public textedMessage = translate(
    'Your code is on the way. To log in, enter the code we texted to'
  );
  public defaultMessage = translate(
    'Your code is on the way. To log in, enter the code we sent you. It may take a minute to arrive.'
  );
  public minutesMessage = translate('It may take a minute to arrive.');

  constructor(public authenticator: AuthenticatorService) {}

  public get context() {
    return this.authenticator.slotContext;
  }

  public get confirmSignUpHeading(): string {
    const { codeDeliveryDetails: { DeliveryMedium } = {} } = this.authenticator;
    return DeliveryMedium === 'EMAIL'
      ? translate('We Emailed You')
      : DeliveryMedium === 'SMS'
      ? translate('We Texted You')
      : translate('We Sent A Code');
  }

  public get subtitleText(): string {
    const { codeDeliveryDetails: { DeliveryMedium, Destination } = {} } =
      this.authenticator;
    return DeliveryMedium === 'EMAIL'
      ? `${this.emailMessage} ${Destination}. ${this.minutesMessage}`
      : DeliveryMedium === 'SMS'
      ? `${this.textedMessage} ${Destination}. ${this.minutesMessage}`
      : translate(`${this.defaultMessage}`);
  }

  onInput(event: Event) {
    event.preventDefault();
    const { name, value } = <HTMLInputElement>event.target;
    this.authenticator.updateForm({ name, value });
  }

  onSubmit(event: Event): void {
    event.preventDefault();
    this.authenticator.submitForm(getFormDataFromEvent(event));
  }
}

<ng-container>
  <form data-amplify-form (submit)="onSubmit($event)" (input)="onInput($event)">
    <fieldset
      class="amplify-flex"
      style="flex-direction: column"
      data-amplify-fieldset
      [disabled]="context.isPending"
    >
      <amplify-slot name="confirm-sign-up-header" [context]="context">
        <h3 class="amplify-heading" style="font-size: 1.5rem">
          {{ confirmSignUpHeading }}
        </h3>
      </amplify-slot>
      <amplify-slot name="confirm-sign-up-form-fields" [context]="context">
        <span style="margin-bottom: 1rem">
          {{ subtitleText }}
        </span>
        <amplify-base-form-fields
          route="confirmSignUp"
        ></amplify-base-form-fields>

        <button
          amplify-button
          variation="primary"
          fullWidth="true"
          type="submit"
        >
          {{ confirmText }}
        </button>
        <button
          amplify-button
          fontWeight="normal"
          (click)="authenticator.resendCode()"
        >
          {{ resendCodeText }}
        </button>
      </amplify-slot>
    </fieldset>

    <amplify-error *ngIf="context.error">
      {{ authenticator.error }}
    </amplify-error>
    <amplify-slot
      name="confirm-sign-up-footer"
      [context]="context"
    ></amplify-slot>
  </form>
</ng-container>
