// examples/vue/src/pages/ui/components/authenticator/sign-in-with-email-mfa/index.vue
<script setup lang="ts">
import { Amplify } from 'aws-amplify';

import { AuthContext, } from '@aws-amplify/ui';
import { Authenticator } from '@aws-amplify/ui-vue';
import '@aws-amplify/ui-vue/styles.css';

import awsExports from './aws-exports';

Amplify.configure(awsExports);

const customServices: AuthContext['services'] = {
    handleSignIn: async () => {
        return {
            isSignedIn: false,
            nextStep: {
                signInStep: 'CONFIRM_SIGN_IN_WITH_EMAIL_CODE',
                codeDeliveryDetails: {
                    destination: 'a***@e***.com',
                    deliveryMedium: 'EMAIL',
                    attributeName: 'email',
                },
            },
        };
    },
    handleConfirmSignIn: async ({ challengeResponse }) => {
        if (/^\d{6}$/.test(challengeResponse)) {
            return {
                isSignedIn: true,
                nextStep: {
                    signInStep: 'DONE',
                },
            };
        }
        throw new Error('Invalid code or auth state for the user.');
    },
    getCurrentUser: async () => {
        return {
            userId: '******************',
            username: 'james',
        };
    },
};

</script>

<template>
    <authenticator :services="customServices">
        <template v-slot="{ user, signOut }">
            <h1>Hello {{ user.username }}!</h1>
            <button @click="signOut">Sign Out</button>
        </template>
    </authenticator>
</template>

// examples/angular/src/pages/ui/components/authenticator/sign-in-with-email-mfa/sign-in-with-email-mfa.component.ts
import { Component } from '@angular/core';
import { Amplify } from 'aws-amplify';

import awsExports from './aws-exports';
import { AuthContext, emailRegex } from '@aws-amplify/ui';

@Component({
  selector: 'app-sign-in-with-email-mfa',
  templateUrl: './sign-in-with-email-mfa.component.html',
})
export class SignInWithEmailMfaComponent {
  public services: AuthContext['services'] = {
    handleSignIn: async () => {
      return {
        isSignedIn: false,
        nextStep: {
          signInStep: 'CONFIRM_SIGN_IN_WITH_EMAIL_CODE',
          codeDeliveryDetails: {
            destination: 'a***@e***.com',
            deliveryMedium: 'EMAIL',
            attributeName: 'email',
          },
        },
      };
    },
    handleConfirmSignIn: async ({ challengeResponse }) => {
      if (/^\d{6}$/.test(challengeResponse)) {
        return {
          isSignedIn: true,
          nextStep: {
            signInStep: 'DONE',
          },
        };
      }
      throw new Error('Invalid code or auth state for the user.');
    },
    getCurrentUser: async () => {
      return {
        userId: '******************',
        username: 'james',
      };
    },
  };

  constructor() {
    Amplify.configure(awsExports);
  }
}

<amplify-authenticator [services]="services">
    <ng-template
        amplifySlot="authenticated"
        let-user="user"
        let-signOut="signOut"
    >
        <h2>Welcome, {{ user.username }}!</h2>
        <button (click)="signOut()">Sign Out</button>
    </ng-template>
</amplify-authenticator>
